# 0.0. Setup

In [1]:
import os
import copy
import json
import requests
from pathlib import Path

import re
import pickle
import importlib
import numpy as np
import pandas as pd
import openpyxl as opxl
import matplotlib.pyplot as plt
from typing import Optional, Dict, Any, List

# None means 'no limit'
pd.set_option('display.max_columns', None)

PROJECT_DIR = Path.cwd().parent

DATA_DIR = PROJECT_DIR / 'data'
DATA_PUBLIC_DIR = PROJECT_DIR / 'data/public'
DATA_PRIVATE_DIR = PROJECT_DIR / 'data/private'
DATA_PROCESSED_DIR = PROJECT_DIR / 'data/processed'
OUTPUT_DIR = PROJECT_DIR / 'output'

# 1.0. Load data

In [2]:
!ls '{DATA_PRIVATE_DIR}'

'2024-2025 GASTPE Participating Schools Top-up Data.xlsx'
 Alphalist-Schools-Slots-addon_slots.csv
 Alphalist-Schools-Slots-fixed_slots.csv
 Alphalist-Schools-Slots-incentive_slots.csv
 ESC
'ESC and SHSVP Tuition.xlsx'
'Private School Seats and TOSF ao 2025Oct27.xlsx'
 SHSVP
'SUMMARY OF PRIVATE SCHOOL PROFILE.xlsx'
 priv_classroom_furniture.xlsx
 raw_validation_sheets

In [3]:
fnames = [fn for fn in os.listdir(DATA_PRIVATE_DIR) if re.search(r'alphalist-schools', fn, flags=re.IGNORECASE)]
fpaths = [os.path.join(DATA_PRIVATE_DIR, fn) for fn in fnames]
display(fpaths)

['/workspace/project_paaral/data/private/Alphalist-Schools-Slots-addon_slots.csv',
 '/workspace/project_paaral/data/private/Alphalist-Schools-Slots-fixed_slots.csv',
 '/workspace/project_paaral/data/private/Alphalist-Schools-Slots-incentive_slots.csv']

## 1.1. Read all

In [4]:
dfs = []
for fpath in fpaths:
    df = pd.read_csv(fpath)
    dfs.append(df)

## 1.2. Inspect

In [5]:
print(dfs[0].shape)
display(dfs[0].head(2))
display(dfs[0].tail(2))

(4550, 3)

   School ID                                        School Name  Value
0     303929          One La Salle Educational Foundation, Inc.      0
1    1104375  Newfoundland Arts and Science Academy of Tagum...      0

      School ID                                        School Name  Value
4548    1704003                DR. GREGORIO VALDEZ INSTITUTE, INC.      0
4549    1704253  Southwestern Institute of Business and Technol...      0

In [6]:
print(dfs[1].shape)
display(dfs[1].head(2))
display(dfs[1].tail(2))

(4550, 3)

   School ID                                        School Name  Value
0     303929          One La Salle Educational Foundation, Inc.     38
1    1104375  Newfoundland Arts and Science Academy of Tagum...     50

      School ID                                        School Name  Value
4548    1704003                DR. GREGORIO VALDEZ INSTITUTE, INC.     11
4549    1704253  Southwestern Institute of Business and Technol...     50

In [7]:
print(dfs[2].shape)
display(dfs[2].head(2))
display(dfs[2].tail(2))

(4550, 3)

   School ID                                        School Name  Value
0     303929          One La Salle Educational Foundation, Inc.      0
1    1104375  Newfoundland Arts and Science Academy of Tagum...      0

      School ID                                        School Name  Value
4548    1704003                DR. GREGORIO VALDEZ INSTITUTE, INC.      0
4549    1704253  Southwestern Institute of Business and Technol...      0

# 2.0. Process

## 2.1. Aggregate slots

In [8]:
dfs_tmp = copy.copy(dfs)

csv_label = [
    'addon',
    'fixed',
    'incentive'
]

dfs_processed = []
for df, label in zip(dfs_tmp, csv_label):
    df['School ID'] = df['School ID'].astype(str)
    df['Value'] = df['Value'].astype(int)
    
    new_columns = ['esc_school_id','school_name','count']
    df.columns = new_columns
    df.rename(
        columns={
            'count':'count_'+label+'_slots'
        }, inplace=True
    )
    df.set_index(df.columns[0], inplace=True)
    df.drop(columns='school_name', inplace=True)

    dfs_processed.append(df)

dfs_processed = pd.concat(dfs_processed, axis=1)
dfs_processed['total_count_slots'] = dfs_processed.sum(axis=1)

print(dfs_processed.shape)

(4550, 4)

In [9]:
dfs_processed

,count_addon_slots,count_fixed_slots,count_incentive_slots,total_count_slots
esc_school_id,,,,
303929,0,38,0,38
1104375,0,50,0,50
1504390,44,50,0,94
304395,0,50,0,50
1404408,0,50,0,50
...,...,...,...,...
1704000,0,0,0,0
1704001,0,12,0,12
1704002,10,50,0,60
1704003,0,11,0,11
1704253,0,50,0,50

## 2.2. Match ESC IDs

In [10]:
# We'll use the GASTPE dataset to make a DepEd-PEAC school id match
fpath = os.path.join(DATA_PRIVATE_DIR, 'ESC and SHSVP Tuition.xlsx')
gastpe_excel = pd.read_excel(fpath, sheet_name='Tuition', engine='calamine')
print(gastpe_excel.shape)

(5188, 15)

In [11]:
display(gastpe_excel.head(2))

,Region SHS,Program,SUC/LUC,Billed in SY 2024-2025 (ESC),ESC School ID,DepEd School Id,School Name,ESC (Tuition),ESC (Other),ESC (Misc),ESC (Total),SHSVP (Tuition),SHSVP (Other),SHSVP (Misc),SHSVP (Total)
0,Region I,BOTH,NaN,NaN,100008.0,400001,"St. Andrew Academy of Bacarra, Inc.",13353.05,3817.85,2220.0,19390.90,15515.0,3210.0,2220.0,20945.0
1,Region I,BOTH,NaN,NaN,100018.0,400002,"Badoc Junior College, Inc.",9808.26,908.98,0.0,10717.24,15000.0,2658.0,0.0,17658.0

### Process

In [12]:
essential_columns = ['DepEd School Id','ESC School ID']
df_tmp = gastpe_excel[essential_columns].copy()

new_columns = ['school_id','esc_school_id']
df_tmp.columns = new_columns

# ESC School ID columns has NaNs that is why its float
for col in df_tmp.columns:
    df_tmp[col] = df_tmp[col].astype(str)

mask_na = df_tmp['esc_school_id'].str.contains(r'nan', flags=re.IGNORECASE)
df_tmp.loc[~mask_na, 'esc_school_id'] = df_tmp.loc[~mask_na, 'esc_school_id'].apply(lambda x: re.findall(r'(.*).0', x)[0])
df_tmp.loc[mask_na, 'esc_school_id'] = 'No ESC School ID'

print(df_tmp.shape)

# Create dictionary of ESC-DepEd school ID pairs
deped_esc_ids = {k:v for k,v in zip(df_tmp['school_id'], df_tmp['esc_school_id'])}
esc_deped_ids = {v:k for k,v in deped_esc_ids.items()}

(5188, 2)

In [13]:
# # Uncomment to inspect
# display(deped_esc_ids)

### Match

In [14]:
dfs_processed.index.map(esc_deped_ids)

Index(['418013', '408365', '406245', '419005',      nan, '404601', '446545',
       '401884', '406004', '400609',
       ...
       '403425', '403514', '403533', '430502', '430016',      nan, '408013',
       '403391', '407742', '406959'],
      dtype='object', name='esc_school_id', length=4550)

In [15]:
df_match = dfs_processed.copy()
df_match['school_id'] = df_match.index.map(esc_deped_ids)
df_match['school_id'] = df_match['school_id'].astype(str)

df_match['has_deped_school_id'] = None
mask = df_match['school_id'] == 'nan'
df_match.loc[mask, 'has_deped_school_id'] = False
df_match.loc[~mask, 'has_deped_school_id'] = True

df_match.reset_index(inplace=True)
print(df_match.shape)

(4550, 7)

In [16]:
df_match['has_deped_school_id'].sum()

3621

Note: There are ESC schools that did **not** exist yet in SY 2023-2024 hence the False values in `has_deped_school_id`.

In [17]:
display(df_match)

,esc_school_id,count_addon_slots,count_fixed_slots,count_incentive_slots,total_count_slots,school_id,has_deped_school_id
0,303929,0,38,0,38,418013,True
1,1104375,0,50,0,50,408365,True
2,1504390,44,50,0,94,406245,True
3,304395,0,50,0,50,419005,True
4,1404408,0,50,0,50,nan,False
...,...,...,...,...,...,...,...
4545,1704000,0,0,0,0,nan,False
4546,1704001,0,12,0,12,408013,True
4547,1704002,10,50,0,60,403391,True
4548,1704003,0,11,0,11,407742,True
4549,1704253,0,50,0,50,406959,True

### Save

In [72]:
fpath = 'output/processed_esc_slots.parquet'
df_match.to_parquet(fpath)