# 0.11 Rizal School Choice Simulation - Data Preparation

This notebook implements **Phase 1-2** of the Discrete Choice Experiment (DCE) simulation for Rizal Province Grade 7 school selection.

**Objective:** Simulate learner school choice using a multinomial DCE model trained on historical Grade 7 enrollment patterns.

**Province:** Rizal (PH04058)

**Phases covered in this notebook:**
- Phase 1: Data Preparation (Tasks 1.1-1.6)
- Phase 2: Feature Engineering for DCE Model (Tasks 2.1-2.2)

**Outputs:**
- `rizal_learners_augmented.csv` - Learner-level dataset with all features
- `rizal_choice_sets_long.csv` - Choice sets in long format for DCE model
- `rizal_dce_features_summary.txt` - Feature engineering report

## 0. Setup

In [1]:
import os
import sys
import json
import numpy as np
import pandas as pd
import geopandas as gpd
from pathlib import Path
from scipy.spatial import cKDTree
from sklearn.neighbors import NearestNeighbors
import matplotlib.pyplot as plt
import seaborn as sns
from importlib import reload

# Add project root to Python path
project_root = Path.cwd().parent
if str(project_root) not in sys.path:
    sys.path.insert(0, str(project_root))

# Import config
from config import setup_notebook, get_path

setup_notebook()

# Set display options
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", None)

print("✓ Setup complete")

✓ Project root: /workspace/project_paaral
✓ Working directory: /workspace/project_paaral
✓ Python path updated
✓ Setup complete

In [2]:
# Province configuration
PROVINCE_CODE = "PH04058"
PROVINCE_NAME = "rizal"

# Paths
UNIFIED_DATA_PATH = "output/gr7_enrollees_sy2023_2024_valid.csv"
DISTANCE_MATRIX_PATH = f"output/{PROVINCE_CODE}_{PROVINCE_NAME}_distance_matrix.csv"
PUBLIC_NODES_PATH = "output/public_nodes_valid.gpkg"
PRIVATE_NODES_PATH = "output/private_nodes_valid.gpkg"

# Output directory
OUTPUT_DIR = Path("output/rizal_choice_simulation")
OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

print(f"Province: {PROVINCE_NAME.title()} ({PROVINCE_CODE})")
print(f"Output directory: {OUTPUT_DIR}")

Province: Rizal (PH04058)
Output directory: output/rizal_choice_simulation

## 1. Load Base Data

In [3]:
# Load school node tables
print("Loading school node tables...")
public_nodes = gpd.read_file(PUBLIC_NODES_PATH)
private_nodes = gpd.read_file(PRIVATE_NODES_PATH)

print(f"✓ Public schools loaded: {len(public_nodes):,}")
print(f"✓ Private schools loaded: {len(private_nodes):,}")

Loading school node tables...
✓ Public schools loaded: 44,899
✓ Private schools loaded: 9,305

In [4]:
# Filter to Rizal province
print(f"\nFiltering to {PROVINCE_NAME.title()} province...")

public_rizal = public_nodes[public_nodes["adm2_pcode"] == PROVINCE_CODE].copy()
private_rizal = private_nodes[private_nodes["adm2_pcode"] == PROVINCE_CODE].copy()

# Quick fix: Add 'sector' column manually
public_rizal["sector"] = "Public"
private_rizal["sector"] = "Private"

print(f"✓ Rizal public schools: {len(public_rizal):,}")
print(f"✓ Rizal private schools: {len(private_rizal):,}")
print(f"✓ Total Rizal schools: {len(public_rizal) + len(private_rizal):,}")

# Combine for easy lookup
all_rizal_schools = pd.concat([public_rizal, private_rizal], ignore_index=True)
rizal_school_ids = set(all_rizal_schools["school_id"])

Filtering to Rizal province...
✓ Rizal public schools: 359
✓ Rizal private schools: 419
✓ Total Rizal schools: 778

In [10]:
public_rizal['municipality'].unique()

array(['Tanay', 'Angono', 'Teresa', 'City of Antipolo', 'Binangonan',
       'Morong', 'Taytay', 'Cainta', 'Cardona', 'Pililla', 'Rodriguez',
       'San Mateo', 'Baras', 'Jala-Jala'], dtype=object)

In [5]:
public_rizal.columns

Index(['school_id', 'school_name', 'latitude', 'longitude',
       'coordinates_valid', 'enrollment_es', 'enrollment_jhs',
       'enrollment_shs', 'has_enrollment_data', 'offers_es', 'offers_jhs',
       'offers_shs', 'es_classrooms_instructional',
       'es_classrooms_non_instructional', 'jhs_classrooms_instructional',
       'jhs_classrooms_non_instructional', 'shs_classrooms_instructional',
       'shs_classrooms_non_instructional', 'has_facilities_data', 'seats_es',
       'seats_jhs', 'seats_shs', 'has_seats_data', 'adm2_pcode', 'adm1_pcode',
       'region', 'province', 'adm3_psgc', 'municipality',
       'admin_assignment_valid', 'total_enrollment', 'total_seats',
       'capacity_utilization', 'validation_level_1', 'validation_level_2',
       'validation_level_3', 'all_valid', 'geometry', 'sector'],
      dtype='object')

In [6]:
# Load unified Grade 7 dataset
print("\nLoading unified Grade 7 dataset...")
unified_gr7 = pd.read_csv(
    UNIFIED_DATA_PATH,
    dtype={"lrn": str, "school_id_origin": str, "school_id_destination": str},
)

print(f"✓ Unified Grade 7 dataset loaded: {len(unified_gr7):,} learners")
print(f"  Columns: {len(unified_gr7.columns)}")
print(f"  Beneficiaries: {unified_gr7['is_beneficiary'].sum():,}")
print(f"  Non-beneficiaries: {(~unified_gr7['is_beneficiary']).sum():,}")

Loading unified Grade 7 dataset...
✓ Unified Grade 7 dataset loaded: 922,059 learners
  Columns: 33
  Beneficiaries: 105,554
  Non-beneficiaries: 816,505

In [7]:
unified_gr7.head(1)

,region,division,lrn,school_id_destination,school_name_destination,sy_grade6,school_id_origin,school_name_origin,school_year,school_id_origin_valid,school_id_destination_valid,both_school_ids_valid,sector_origin,municipality_origin,sector_destination,municipality_destination,origin_in_public_nodes,origin_in_private_nodes,origin_in_node_tables,destination_in_public_nodes,destination_in_private_nodes,destination_in_node_tables,both_in_node_tables,both_in_enrollment,fully_valid,esc_subsidy_amount,is_beneficiary,latitude_origin,longitude_origin,latitude_destination,longitude_destination,distance_straightline_km,flow_type
0,Region I,Ilocos Norte,100001160001,300002,Bacarra NCHS,2022.0,100001,Apaleng-Libtong PS,SY 2023-2024,True,True,True,public,BACARRA,public,BACARRA,True,False,True,True,False,True,True,True,True,NaN,False,18.26686,120.614372,18.250214,120.613077,1.855995,public_to_public_nonbeneficiary

In [16]:
# Load distance matrix
print(f"\nLoading Rizal distance matrix...")
distance_matrix = pd.read_csv(DISTANCE_MATRIX_PATH, index_col=0)

# FIX: Convert index from int64 to string to match school_id dtype
distance_matrix.index = distance_matrix.index.astype(str)

print(f"✓ Distance matrix loaded: {distance_matrix.shape}")
print(f"  Index dtype: {distance_matrix.index.dtype}")
print(f"  Column dtype: {distance_matrix.columns.dtype}")
print(
    f"  Valid distances: {distance_matrix.notna().sum().sum():,} / {distance_matrix.size:,}"
)
print(
    f"  Coverage: {distance_matrix.notna().sum().sum() / distance_matrix.size * 100:.2f}%"
)

Loading Rizal distance matrix...
✓ Distance matrix loaded: (778, 778)
  Index dtype: object
  Column dtype: object
  Valid distances: 43,533 / 605,284
  Coverage: 7.19%

## Phase 1: Data Preparation

### Task 1.1: Filter to Rizal Learners

In [17]:
%%time
print("=" * 70)
print("TASK 1.1: Filter Unified Grade 7 Data to Rizal Learners")
print("=" * 70)

# Filter to learners whose ORIGIN school is in Rizal
# (These are Grade 6 students from Rizal schools making Grade 7 choices)
rizal_learners = unified_gr7[
    unified_gr7["school_id_origin"].isin(rizal_school_ids)
].copy()

print(f"\n✓ Rizal learners filtered: {len(rizal_learners):,}")
print(f"  Percentage of total: {len(rizal_learners)/len(unified_gr7)*100:.2f}%")
print(f"\nBeneficiary breakdown:")
print(
    f"  Beneficiaries: {rizal_learners['is_beneficiary'].sum():,} ({rizal_learners['is_beneficiary'].sum()/len(rizal_learners)*100:.1f}%)"
)
print(
    f"  Non-beneficiaries: {(~rizal_learners['is_beneficiary']).sum():,} ({(~rizal_learners['is_beneficiary']).sum()/len(rizal_learners)*100:.1f}%)"
)

print(f"\nDestination breakdown:")
dest_in_rizal = rizal_learners["school_id_destination"].isin(rizal_school_ids).sum()
print(
    f"  In-province destinations: {dest_in_rizal:,} ({dest_in_rizal/len(rizal_learners)*100:.1f}%)"
)
print(
    f"  Cross-province destinations: {len(rizal_learners) - dest_in_rizal:,} ({(len(rizal_learners) - dest_in_rizal)/len(rizal_learners)*100:.1f}%)"
)

print(f"\nFlow type distribution:")
print(rizal_learners["flow_type"].value_counts())

======================================================================
TASK 1.1: Filter Unified Grade 7 Data to Rizal Learners
======================================================================

✓ Rizal learners filtered: 48,585
  Percentage of total: 5.27%

Beneficiary breakdown:
  Beneficiaries: 5,674 (11.7%)
  Non-beneficiaries: 42,911 (88.3%)

Destination breakdown:
  In-province destinations: 46,763 (96.2%)
  Cross-province destinations: 1,822 (3.8%)

Flow type distribution:
flow_type
public_to_public_nonbeneficiary      40354
private_to_private_beneficiary        3412
public_to_private_beneficiary         2255
private_to_private_nonbeneficiary     1520
private_to_public_nonbeneficiary       677
unknown                                360
public_to_public_beneficiary             5
private_to_public_beneficiary            2
Name: count, dtype: int64
CPU times: user 53.4 ms, sys: 247 μs, total: 53.6 ms
Wall time: 51.9 ms

In [18]:
# Preview rizal_learners dataset
print("\nRizal learners dataset preview:")
print(f"Shape: {rizal_learners.shape}")
print(f"\nColumns ({len(rizal_learners.columns)}):")
print(list(rizal_learners.columns))

rizal_learners.head()

Rizal learners dataset preview:
Shape: (48585, 33)

Columns (33):
['region', 'division', 'lrn', 'school_id_destination', 'school_name_destination', 'sy_grade6', 'school_id_origin', 'school_name_origin', 'school_year', 'school_id_origin_valid', 'school_id_destination_valid', 'both_school_ids_valid', 'sector_origin', 'municipality_origin', 'sector_destination', 'municipality_destination', 'origin_in_public_nodes', 'origin_in_private_nodes', 'origin_in_node_tables', 'destination_in_public_nodes', 'destination_in_private_nodes', 'destination_in_node_tables', 'both_in_node_tables', 'both_in_enrollment', 'fully_valid', 'esc_subsidy_amount', 'is_beneficiary', 'latitude_origin', 'longitude_origin', 'latitude_destination', 'longitude_destination', 'distance_straightline_km', 'flow_type']

,region,division,lrn,school_id_destination,school_name_destination,sy_grade6,school_id_origin,school_name_origin,school_year,school_id_origin_valid,school_id_destination_valid,both_school_ids_valid,sector_origin,municipality_origin,sector_destination,municipality_destination,origin_in_public_nodes,origin_in_private_nodes,origin_in_node_tables,destination_in_public_nodes,destination_in_private_nodes,destination_in_node_tables,both_in_node_tables,both_in_enrollment,fully_valid,esc_subsidy_amount,is_beneficiary,latitude_origin,longitude_origin,latitude_destination,longitude_destination,distance_straightline_km,flow_type
533,Region IV-A,Rizal,100036160032,301433,"Carlos ""Botong"" V. Francisco Memorial Nationa...",2022.0,109316,Sitio Mata ES,SY 2023-2024,True,True,True,public,BINANGONAN,public,ANGONO,True,False,True,True,False,True,True,True,True,NaN,False,14.540718,121.196099,14.542272,121.183972,1.316640,public_to_public_nonbeneficiary
681,Region IV-A,Rizal,100047160008,301439,Gen. Licerio Geronimo National High School,2022.0,109479,San Rafael ES,SY 2023-2024,True,True,True,public,RODRIGUEZ (MONTALBAN),public,RODRIGUEZ (MONTALBAN),True,False,True,True,False,True,True,True,True,NaN,False,14.732105,121.158692,14.731820,121.149660,0.971814,public_to_public_nonbeneficiary
938,Region IV-A,Rizal,100063160006,403070,Roosevelt College Rodriguez,2022.0,109466,Eulogio Rodriguez Jr. ES,SY 2023-2024,True,True,True,public,RODRIGUEZ (MONTALBAN),private,RODRIGUEZ (MONTALBAN),True,False,True,False,True,True,True,True,True,9000.0,True,14.732750,121.144570,14.729912,121.140439,0.544969,public_to_private_beneficiary
1591,Region IV-A,Rizal,100099160013,301467,Teresa National High School,2022.0,109346,Bagumbayan ES,SY 2023-2024,True,True,True,public,TERESA,public,TERESA,True,False,True,True,False,True,True,True,True,NaN,False,14.549997,121.218826,14.549540,121.218950,0.052499,public_to_public_nonbeneficiary
1805,Region I,Ilocos Norte,100116160003,300013,Wilbur C. Go NHS,2022.0,165509,Kasiglahan Village ES Unit I,SY 2023-2024,True,True,True,public,RODRIGUEZ (MONTALBAN),public,CURRIMAO,True,False,True,True,False,True,True,True,True,NaN,False,14.744536,121.140152,18.017820,120.488890,370.542117,public_to_public_nonbeneficiary

### Task 1.2: Identify ESC-Delivering Schools in Rizal

In [19]:
private_rizal.head(2)

,school_id,school_name,latitude,longitude,coordinates_valid,region_left,modified_coc,offers_es,offers_jhs,offers_shs,esc_average_misc_fees,esc_average_other_fees,esc_average_tuition_fees,esc_delivering,shsvp_average_tuition_fees,shsvp_average_other_fees,shsvp_average_misc_fees,shsvp_delivering,has_gastpe_data,seats_es,seats_jhs,seats_shs,has_furniture_data,enrollment_es,enrollment_jhs,enrollment_shs,has_enrollment_data,adm2_pcode,adm1_pcode,region_right,province,adm3_psgc,municipality,admin_assignment_valid,region,total_enrollment,total_seats,capacity_utilization,validation_level_1,validation_level_2,validation_level_3,all_valid,geometry,sector
847,485562,"MC Lorenze Academy, Inc.",14.5452934691268,121.110216316383,True,NCR,ES and JHS,True,True,False,NaN,NaN,NaN,None,NaN,NaN,NaN,None,False,136.0,94.0,0.0,True,111.0,87.0,0.0,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405813000,Taytay,True,None,198.0,230.0,0.860870,True,True,True,True,POINT (121.11022 14.54529),Private
892,485536,Mariam Claire Integrated Academy,14.6154968259867,121.102260037988,True,NCR,ES and JHS,True,True,False,NaN,NaN,NaN,None,NaN,NaN,NaN,None,False,195.0,150.0,0.0,True,87.0,18.0,0.0,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405805000,Cainta,True,None,105.0,345.0,0.304348,True,True,True,True,POINT (121.10226 14.6155),Private

In [20]:
private_rizal["esc_delivering"].unique()

array([None, 'True', 'False'], dtype=object)

In [21]:
print("=" * 70)
print("TASK 1.2: Identify ESC-Delivering Schools in Rizal")
print("=" * 70)

# FOR LATER: values under esc_delivering are in string

# Filter to ESC-delivering schools only
esc_schools_rizal = private_rizal[private_rizal["esc_delivering"] == "True"].copy()

print(f"\n✓ ESC-delivering schools in Rizal: {len(esc_schools_rizal):,}")
print(
    f"  Percentage of Rizal private schools: {len(esc_schools_rizal)/len(private_rizal)*100:.1f}%"
)

# Check tuition fee data availability
esc_with_tuition = esc_schools_rizal["esc_average_tuition_fees"].notna().sum()
print(f"\nTuition fee data:")
print(
    f"  Schools with ESC tuition data: {esc_with_tuition:,} ({esc_with_tuition/len(esc_schools_rizal)*100:.1f}%)"
)
print(f"  Schools missing tuition data: {len(esc_schools_rizal) - esc_with_tuition:,}")

# Store ESC school IDs for easy filtering
esc_school_ids = set(esc_schools_rizal["school_id"])

print(f"\n✓ ESC school IDs stored: {len(esc_school_ids)} schools")

======================================================================
TASK 1.2: Identify ESC-Delivering Schools in Rizal
======================================================================

✓ ESC-delivering schools in Rizal: 111
  Percentage of Rizal private schools: 26.5%

Tuition fee data:
  Schools with ESC tuition data: 110 (99.1%)
  Schools missing tuition data: 1

✓ ESC school IDs stored: 111 schools

In [22]:
# Preview ESC schools
print("\nESC-delivering schools preview:")
esc_schools_rizal[
    [
        "school_id",
        "school_name",
        "esc_average_tuition_fees",
        "esc_average_misc_fees",
        "esc_average_other_fees",
        "latitude",
        "longitude",
    ]
].head(10)

ESC-delivering schools preview:

,school_id,school_name,esc_average_tuition_fees,esc_average_misc_fees,esc_average_other_fees,latitude,longitude
1512,406574,Village School of Parkwoods,23881.2500,3705.000,5157.5000,14.672497736975,121.12620899352
4879,402871,Assumption Antipolo,118099.0000,5040.000,24316.2500,14.60278,121.1801
4881,402883,"Divine Mercy School of Antipolo, Inc.",19000.0000,9000.000,8270.0000,14.5919,121.18046
4882,402892,"Hillcrest School, Inc.",22500.0000,3900.000,2500.0000,14.625541,121.168651
4884,402913,Maries Christian School,21936.0000,3213.190,6786.1200,14.627607,121.127401
4887,402922,Nazareth Christian School of Antipolo,23125.0000,19005.370,NaN,14.623893,121.124849
4889,402943,St. Clare Montessori School and Science High S...,22683.5900,NaN,24212.5000,14.58955,121.17343
4890,402947,St. John Mary Vianney Academy,37814.1275,NaN,4454.3875,14.60882,121.135152
4891,402951,College of San Benildo - Rizal,40854.8200,13075.000,5782.5000,14.619636,121.148051
4892,402953,"Saviour School, Inc.",18025.6300,4466.245,2337.5900,14.6227,121.1636

### Helper Functions for Distance Calculations

In [23]:
def haversine_distance(lat1, lon1, lat2, lon2):
    """
    Calculate straight-line distance between two points using Haversine formula.

    Returns distance in kilometers.
    """
    from math import radians, cos, sin, asin, sqrt

    # Convert to radians
    lat1, lon1, lat2, lon2 = map(radians, [lat1, lon1, lat2, lon2])

    # Haversine formula
    dlat = lat2 - lat1
    dlon = lon2 - lon1
    a = sin(dlat / 2) ** 2 + cos(lat1) * cos(lat2) * sin(dlon / 2) ** 2
    c = 2 * asin(sqrt(a))
    r = 6371  # Radius of earth in kilometers

    return c * r


def get_road_distance_km(origin_id, dest_id, distance_matrix):
    """
    Get road network distance from distance matrix.

    Returns distance in km, or None if not available.
    """
    try:
        distance_m = distance_matrix.loc[origin_id, dest_id]
        if pd.notna(distance_m):
            return distance_m / 1000  # Convert meters to km
        else:
            return None
    except (KeyError, IndexError):
        return None


print("✓ Helper functions defined:")
print("  - haversine_distance()")
print("  - get_road_distance_km()")

✓ Helper functions defined:
  - haversine_distance()
  - get_road_distance_km()

### Task 1.3: Augment - Nearest 5 ESC Schools + Nearest 5 Public JHS Schools

In [24]:
display(public_rizal.head(2))
display(public_rizal["offers_jhs"].unique())

,school_id,school_name,latitude,longitude,coordinates_valid,enrollment_es,enrollment_jhs,enrollment_shs,has_enrollment_data,offers_es,offers_jhs,offers_shs,es_classrooms_instructional,es_classrooms_non_instructional,jhs_classrooms_instructional,jhs_classrooms_non_instructional,shs_classrooms_instructional,shs_classrooms_non_instructional,has_facilities_data,seats_es,seats_jhs,seats_shs,has_seats_data,adm2_pcode,adm1_pcode,region,province,adm3_psgc,municipality,admin_assignment_valid,total_enrollment,total_seats,capacity_utilization,validation_level_1,validation_level_2,validation_level_3,all_valid,geometry,sector
10171,108460,J. Santiago ES,14.564222,121.443704,True,284.0,0.0,0.0,True,True,False,False,13.0,3.0,NaN,NaN,NaN,NaN,True,225.0,NaN,NaN,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405812000,Tanay,True,284.0,225.0,1.262222,True,True,True,True,POINT (121.4437 14.56422),Public
10174,108463,Pao-O ES Main,14.546409,121.421408,True,84.0,0.0,0.0,True,True,False,False,4.0,NaN,NaN,NaN,NaN,NaN,True,104.0,NaN,NaN,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405812000,Tanay,True,84.0,104.0,0.807692,True,True,True,True,POINT (121.42141 14.54641),Public

array(['False', 'True'], dtype=object)

In [25]:
print("=" * 70)
print("TASK 1.3: Augment Nearest 5 ESC + Nearest 5 Public JHS Schools")
print("=" * 70)

# FOR LATER: Again, the True and False values under offer_jhs are in string

# Identify public JHS schools in Rizal
public_jhs_rizal = public_rizal[public_rizal["offers_jhs"] == "True"].copy()
public_jhs_ids = set(public_jhs_rizal["school_id"])

print(f"\nPublic JHS schools in Rizal: {len(public_jhs_rizal):,}")
print(f"ESC schools in Rizal: {len(esc_schools_rizal):,}")
print(f"\nStarting augmentation for {len(rizal_learners):,} learners...")

======================================================================
TASK 1.3: Augment Nearest 5 ESC + Nearest 5 Public JHS Schools
======================================================================

Public JHS schools in Rizal: 99
ESC schools in Rizal: 111

Starting augmentation for 48,585 learners...

In [26]:
%%time
# This cell will take several minutes to run

print("\nProcessing nearest schools for each learner...")
print("(This may take 5-10 minutes)\n")

# Initialize columns for nearest ESC schools
for i in range(1, 6):
    rizal_learners[f"nearest_esc_{i}_school_id"] = None
    rizal_learners[f"nearest_esc_{i}_distance_km"] = None
    rizal_learners[f"nearest_esc_{i}_tuition_total"] = None

# Initialize columns for nearest public JHS schools
for i in range(1, 6):
    rizal_learners[f"nearest_public_jhs_{i}_school_id"] = None
    rizal_learners[f"nearest_public_jhs_{i}_distance_km"] = None
    rizal_learners[f"nearest_public_jhs_{i}_tuition_total"] = 0.0  # Always 0 for public

# Track progress
total_learners = len(rizal_learners)
progress_interval = max(1, total_learners // 20)  # Report every 5%

# Process each learner
for idx, (row_idx, learner) in enumerate(rizal_learners.iterrows()):
    if idx % progress_interval == 0:
        print(
            f"  Progress: {idx:,} / {total_learners:,} ({idx/total_learners*100:.1f}%)"
        )

    origin_id = learner["school_id_origin"]

    # === NEAREST 5 ESC SCHOOLS ===
    # Get distances to all ESC schools
    esc_distances = []
    for esc_id in esc_school_ids:
        road_dist = get_road_distance_km(origin_id, esc_id, distance_matrix)
        if road_dist is not None:
            esc_distances.append((esc_id, road_dist))

    # Sort by distance and take top 5
    esc_distances.sort(key=lambda x: x[1])
    nearest_esc = esc_distances[:5]

    # Store in dataframe
    for i, (esc_id, dist) in enumerate(nearest_esc, start=1):
        rizal_learners.at[row_idx, f"nearest_esc_{i}_school_id"] = esc_id
        rizal_learners.at[row_idx, f"nearest_esc_{i}_distance_km"] = dist

        # Get tuition (with nearest-neighbor imputation if missing)
        esc_school = esc_schools_rizal[esc_schools_rizal["school_id"] == esc_id].iloc[0]
        tuition = esc_school["esc_average_tuition_fees"]
        misc = esc_school["esc_average_misc_fees"]
        other = esc_school["esc_average_other_fees"]

        # Sum tuition components (handling NaN)
        tuition_total = sum([x for x in [tuition, misc, other] if pd.notna(x)])

        # If still 0 or NaN, impute from nearest ESC with valid tuition
        if tuition_total == 0 or pd.isna(tuition_total):
            # Find nearest ESC with valid tuition data
            for other_esc_id, _ in esc_distances:
                other_esc = esc_schools_rizal[
                    esc_schools_rizal["school_id"] == other_esc_id
                ].iloc[0]
                other_tuition = other_esc["esc_average_tuition_fees"]
                if pd.notna(other_tuition) and other_tuition > 0:
                    other_misc = other_esc["esc_average_misc_fees"]
                    other_other = other_esc["esc_average_other_fees"]
                    tuition_total = sum(
                        [
                            x
                            for x in [other_tuition, other_misc, other_other]
                            if pd.notna(x)
                        ]
                    )
                    break

        rizal_learners.at[row_idx, f"nearest_esc_{i}_tuition_total"] = tuition_total

    # === NEAREST 5 PUBLIC JHS SCHOOLS ===
    # Get distances to all public JHS schools
    public_jhs_distances = []
    for public_id in public_jhs_ids:
        road_dist = get_road_distance_km(origin_id, public_id, distance_matrix)
        if road_dist is not None:
            public_jhs_distances.append((public_id, road_dist))

    # Sort by distance and take top 5
    public_jhs_distances.sort(key=lambda x: x[1])
    nearest_public_jhs = public_jhs_distances[:5]

    # Store in dataframe
    for i, (public_id, dist) in enumerate(nearest_public_jhs, start=1):
        rizal_learners.at[row_idx, f"nearest_public_jhs_{i}_school_id"] = public_id
        rizal_learners.at[row_idx, f"nearest_public_jhs_{i}_distance_km"] = dist
        # Tuition already set to 0.0 during initialization

print(f"\n✓ Augmentation complete for {len(rizal_learners):,} learners")
print(f"  Added 30 columns (15 for ESC, 15 for public JHS)")

Processing nearest schools for each learner...
(This may take 5-10 minutes)

  Progress: 0 / 48,585 (0.0%)
  Progress: 2,429 / 48,585 (5.0%)
  Progress: 4,858 / 48,585 (10.0%)
  Progress: 7,287 / 48,585 (15.0%)
  Progress: 9,716 / 48,585 (20.0%)
  Progress: 12,145 / 48,585 (25.0%)
  Progress: 14,574 / 48,585 (30.0%)
  Progress: 17,003 / 48,585 (35.0%)
  Progress: 19,432 / 48,585 (40.0%)
  Progress: 21,861 / 48,585 (45.0%)
  Progress: 24,290 / 48,585 (50.0%)
  Progress: 26,719 / 48,585 (55.0%)
  Progress: 29,148 / 48,585 (60.0%)
  Progress: 31,577 / 48,585 (65.0%)
  Progress: 34,006 / 48,585 (70.0%)
  Progress: 36,435 / 48,585 (75.0%)
  Progress: 38,864 / 48,585 (80.0%)
  Progress: 41,293 / 48,585 (85.0%)
  Progress: 43,722 / 48,585 (90.0%)
  Progress: 46,151 / 48,585 (95.0%)
  Progress: 48,580 / 48,585 (100.0%)

✓ Augmentation complete for 48,585 learners
  Added 30 columns (15 for ESC, 15 for public JHS)
CPU times: user 59.7 s, sys: 65.6 ms, total: 59.8 s
Wall time: 59.7 s

In [27]:
rizal_learners.head()

,region,division,lrn,school_id_destination,school_name_destination,sy_grade6,school_id_origin,school_name_origin,school_year,school_id_origin_valid,school_id_destination_valid,both_school_ids_valid,sector_origin,municipality_origin,sector_destination,municipality_destination,origin_in_public_nodes,origin_in_private_nodes,origin_in_node_tables,destination_in_public_nodes,destination_in_private_nodes,destination_in_node_tables,both_in_node_tables,both_in_enrollment,fully_valid,esc_subsidy_amount,is_beneficiary,latitude_origin,longitude_origin,latitude_destination,longitude_destination,distance_straightline_km,flow_type,nearest_esc_1_school_id,nearest_esc_1_distance_km,nearest_esc_1_tuition_total,nearest_esc_2_school_id,nearest_esc_2_distance_km,nearest_esc_2_tuition_total,nearest_esc_3_school_id,nearest_esc_3_distance_km,nearest_esc_3_tuition_total,nearest_esc_4_school_id,nearest_esc_4_distance_km,nearest_esc_4_tuition_total,nearest_esc_5_school_id,nearest_esc_5_distance_km,nearest_esc_5_tuition_total,nearest_public_jhs_1_school_id,nearest_public_jhs_1_distance_km,nearest_public_jhs_1_tuition_total,nearest_public_jhs_2_school_id,nearest_public_jhs_2_distance_km,nearest_public_jhs_2_tuition_total,nearest_public_jhs_3_school_id,nearest_public_jhs_3_distance_km,nearest_public_jhs_3_tuition_total,nearest_public_jhs_4_school_id,nearest_public_jhs_4_distance_km,nearest_public_jhs_4_tuition_total,nearest_public_jhs_5_school_id,nearest_public_jhs_5_distance_km,nearest_public_jhs_5_tuition_total
533,Region IV-A,Rizal,100036160032,301433,"Carlos ""Botong"" V. Francisco Memorial Nationa...",2022.0,109316,Sitio Mata ES,SY 2023-2024,True,True,True,public,BINANGONAN,public,ANGONO,True,False,True,True,False,True,True,True,True,NaN,False,14.540718,121.196099,14.542272,121.183972,1.316640,public_to_public_nonbeneficiary,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0
681,Region IV-A,Rizal,100047160008,301439,Gen. Licerio Geronimo National High School,2022.0,109479,San Rafael ES,SY 2023-2024,True,True,True,public,RODRIGUEZ (MONTALBAN),public,RODRIGUEZ (MONTALBAN),True,False,True,True,False,True,True,True,True,NaN,False,14.732105,121.158692,14.731820,121.149660,0.971814,public_to_public_nonbeneficiary,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0
938,Region IV-A,Rizal,100063160006,403070,Roosevelt College Rodriguez,2022.0,109466,Eulogio Rodriguez Jr. ES,SY 2023-2024,True,True,True,public,RODRIGUEZ (MONTALBAN),private,RODRIGUEZ (MONTALBAN),True,False,True,False,True,True,True,True,True,9000.0,True,14.732750,121.144570,14.729912,121.140439,0.544969,public_to_private_beneficiary,403074,0.607586,27750.0,403070,0.957953,55373.25,403107,2.82818,34095.75,403061,3.315056,44358.0,403097,5.477019,38793.0,308122,1.318322,0.0,301440,2.750069,0.0,301458,7.627794,0.0,None,None,0.0,None,None,0.0
1591,Region IV-A,Rizal,100099160013,301467,Teresa National High School,2022.0,109346,Bagumbayan ES,SY 2023-2024,True,True,True,public,TERESA,public,TERESA,True,False,True,True,False,True,True,True,True,NaN,False,14.549997,121.218826,14.549540,121.218950,0.052499,public_to_public_nonbeneficiary,403080,4.031289,17000.0,402975,7.752616,19814.76,403078,9.793328,28397.2,403115,11.730366,25113.63,403114,12.564577,27175.0,301467,0.035731,0.0,308115,3.762575,0.0,308125,9.728583,0.0,301452,9.952424,0.0,308117,12.507162,0.0
1805,Region I,Ilocos Norte,100116160003,300013,Wilbur C. Go NHS,2022.0,165509,Kasiglahan Village ES Unit I,SY 2023-2024,True,True,True,public,RODRIGUEZ (MONTALBAN),public,CURRIMAO,True,False,True,True,False,True,True,True,True,NaN,False,14.744536,121.140152,18.017820,120.488890,370.542117,public_to_public_nonbeneficiary,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0

In [28]:
# Verify augmentation
print("\nVerifying nearest schools augmentation:")

# Check ESC schools
esc_1_populated = rizal_learners["nearest_esc_1_school_id"].notna().sum()
esc_5_populated = rizal_learners["nearest_esc_5_school_id"].notna().sum()

print(f"\nNearest ESC schools:")
print(
    f"  Learners with nearest ESC 1: {esc_1_populated:,} ({esc_1_populated/len(rizal_learners)*100:.1f}%)"
)
print(
    f"  Learners with nearest ESC 5: {esc_5_populated:,} ({esc_5_populated/len(rizal_learners)*100:.1f}%)"
)

# Check public JHS schools
public_1_populated = rizal_learners["nearest_public_jhs_1_school_id"].notna().sum()
public_5_populated = rizal_learners["nearest_public_jhs_5_school_id"].notna().sum()

print(f"\nNearest public JHS schools:")
print(
    f"  Learners with nearest public JHS 1: {public_1_populated:,} ({public_1_populated/len(rizal_learners)*100:.1f}%)"
)
print(
    f"  Learners with nearest public JHS 5: {public_5_populated:,} ({public_5_populated/len(rizal_learners)*100:.1f}%)"
)

# Sample statistics
print(f"\nDistance statistics (nearest ESC 1):")
print(rizal_learners["nearest_esc_1_distance_km"].describe())

print(f"\nDistance statistics (nearest public JHS 1):")
print(rizal_learners["nearest_public_jhs_1_distance_km"].describe())

Verifying nearest schools augmentation:

Nearest ESC schools:
  Learners with nearest ESC 1: 22,603 (46.5%)
  Learners with nearest ESC 5: 13,716 (28.2%)

Nearest public JHS schools:
  Learners with nearest public JHS 1: 21,689 (44.6%)
  Learners with nearest public JHS 5: 14,942 (30.8%)

Distance statistics (nearest ESC 1):
count     22603.0
unique      161.0
top           0.0
freq       3455.0
Name: nearest_esc_1_distance_km, dtype: float64

Distance statistics (nearest public JHS 1):
count     21689.000000
unique      221.000000
top           2.710869
freq       1059.000000
Name: nearest_public_jhs_1_distance_km, dtype: float64

In [29]:
rizal_learners.sample(3)

,region,division,lrn,school_id_destination,school_name_destination,sy_grade6,school_id_origin,school_name_origin,school_year,school_id_origin_valid,school_id_destination_valid,both_school_ids_valid,sector_origin,municipality_origin,sector_destination,municipality_destination,origin_in_public_nodes,origin_in_private_nodes,origin_in_node_tables,destination_in_public_nodes,destination_in_private_nodes,destination_in_node_tables,both_in_node_tables,both_in_enrollment,fully_valid,esc_subsidy_amount,is_beneficiary,latitude_origin,longitude_origin,latitude_destination,longitude_destination,distance_straightline_km,flow_type,nearest_esc_1_school_id,nearest_esc_1_distance_km,nearest_esc_1_tuition_total,nearest_esc_2_school_id,nearest_esc_2_distance_km,nearest_esc_2_tuition_total,nearest_esc_3_school_id,nearest_esc_3_distance_km,nearest_esc_3_tuition_total,nearest_esc_4_school_id,nearest_esc_4_distance_km,nearest_esc_4_tuition_total,nearest_esc_5_school_id,nearest_esc_5_distance_km,nearest_esc_5_tuition_total,nearest_public_jhs_1_school_id,nearest_public_jhs_1_distance_km,nearest_public_jhs_1_tuition_total,nearest_public_jhs_2_school_id,nearest_public_jhs_2_distance_km,nearest_public_jhs_2_tuition_total,nearest_public_jhs_3_school_id,nearest_public_jhs_3_distance_km,nearest_public_jhs_3_tuition_total,nearest_public_jhs_4_school_id,nearest_public_jhs_4_distance_km,nearest_public_jhs_4_tuition_total,nearest_public_jhs_5_school_id,nearest_public_jhs_5_distance_km,nearest_public_jhs_5_tuition_total
483482,Region IV-A,Rizal,112851160051,308106,San Isidro National High School,2022.0,109477,San Isidro ES,SY 2023-2024,True,True,True,public,RODRIGUEZ (MONTALBAN),public,RODRIGUEZ (MONTALBAN),True,False,True,True,False,True,True,True,True,NaN,False,14.761603,121.158466,14.761330,121.153050,0.583115,public_to_public_nonbeneficiary,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0
26284,Region IV-A,Rizal,101302160010,425645,Philippians Montessori School Inc.,2022.0,425645,"Philippians Montessori School, Inc.",SY 2023-2024,True,True,True,private,TAYTAY,private,TAYTAY,False,True,True,False,True,True,True,True,True,NaN,False,14.556445,121.140717,14.556445,121.140717,0.000000,private_to_private_nonbeneficiary,403123,0.635263,42300.0,403134,0.941721,26339.92,402851,2.895861,25245.0,402860,3.424959,43128.5,402858,4.033439,20926.75,301465,2.118085,0.0,308116,2.951514,0.0,301417,5.034779,0.0,308136,5.203996,0.0,308102,5.238648,0.0
373363,Region IV-A,Rizal,109519170325,308138,Tanay West Integrated National High School,2022.0,109519,"Simeon R. BendaÃ±a, Sr. MES",SY 2023-2024,True,True,True,public,TANAY,public,TANAY,True,False,True,True,False,True,True,True,True,NaN,False,14.495525,121.290024,14.492302,121.283580,0.780750,public_to_public_nonbeneficiary,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0

In [30]:
# # DIAGNOSTIC 1: Check distance matrix index type and sample
# print("Distance Matrix Diagnostics:")
# print(f"Index dtype: {distance_matrix.index.dtype}")
# print(f"Column dtype: {distance_matrix.columns.dtype}")
# print(f"Sample indices: {list(distance_matrix.index[:5])}")
# print(f"Sample columns: {list(distance_matrix.columns[:5])}")

# # DIAGNOSTIC 2: Check if origin school IDs are in distance matrix
# sample_origin_id = rizal_learners['school_id_origin'].iloc[0]
# print(f"\nSample origin ID: {sample_origin_id} (type: {type(sample_origin_id)})")
# print(f"Is in distance_matrix index? {sample_origin_id in distance_matrix.index}")
# print(f"Is in distance_matrix columns? {sample_origin_id in distance_matrix.columns}")

# # DIAGNOSTIC 3: Check ESC school IDs
# sample_esc_id = list(esc_school_ids)[0] if len(esc_school_ids) > 0 else None
# print(f"\nSample ESC ID: {sample_esc_id} (type: {type(sample_esc_id)})")
# if sample_esc_id:
#   print(f"Is in distance_matrix index? {sample_esc_id in distance_matrix.index}")
#   print(f"Is in distance_matrix columns? {sample_esc_id in distance_matrix.columns}")

# # DIAGNOSTIC 4: Check overlap between school IDs and distance matrix
# origin_ids_in_matrix = rizal_learners['school_id_origin'].isin(distance_matrix.index).sum()
# print(f"\nOrigin schools in distance matrix: {origin_ids_in_matrix} / {len(rizal_learners)}")

# esc_ids_in_matrix = len([esc_id for esc_id in esc_school_ids if esc_id in distance_matrix.index])
# print(f"ESC schools in distance matrix: {esc_ids_in_matrix} / {len(esc_school_ids)}")

# public_jhs_ids_in_matrix = len([pub_id for pub_id in public_jhs_ids if pub_id in distance_matrix.index])
# print(f"Public JHS schools in distance matrix: {public_jhs_ids_in_matrix} / {len(public_jhs_ids)}")

### Save Progress Checkpoint

In [22]:
# Save intermediate results
checkpoint_file = OUTPUT_DIR / "rizal_learners_checkpoint_task1.3.csv"
rizal_learners.to_csv(checkpoint_file, index=False)

print(f"✓ Checkpoint saved: {checkpoint_file}")
print(f"  Rows: {len(rizal_learners):,}")
print(f"  Columns: {len(rizal_learners.columns):,}")

✓ Checkpoint saved: output/rizal_choice_simulation/rizal_learners_checkpoint_task1.3.csv
  Rows: 48,585
  Columns: 63

### Task 1.4: Augment Top 3 Nearby Schools + Summary Stats
For each learner, identify schools within 3km radius of their destination school:
- Store top 3 nearest schools (individual IDs, distances, tuition)
- Summarize remaining nearby schools (counts, averages)
- Calculate "diagonal distance" (straight-line from origin to nearby school)

In [31]:
print("=" * 70)
print("TASK 1.4: Augment Top 3 Nearby Schools + Summary Stats (OPTIMIZED)")
print("=" * 70)

# Initialize columns (same as before)
for i in range(1, 4):
    rizal_learners[f"nearby_{i}_school_id"] = None
    rizal_learners[f"nearby_{i}_distance_km"] = None
    rizal_learners[f"nearby_{i}_tuition_total"] = None
    rizal_learners[f"nearby_{i}_sector"] = None

rizal_learners["other_nearby_count"] = 0
rizal_learners["other_nearby_avg_tuition"] = None
rizal_learners["other_nearby_min_distance_km"] = None
rizal_learners["total_nearby_count"] = 0
rizal_learners["nearby_public_count"] = 0
rizal_learners["nearby_private_count"] = 0
rizal_learners["nearby_esc_count"] = 0

# ============================================================================
# OPTIMIZATION 1: Pre-build lookup dictionaries
# ============================================================================
print("\nBuilding lookup dictionaries for fast access...")

# School attribute lookup (O(1) instead of O(n))
school_lookup = all_rizal_schools.set_index("school_id").to_dict("index")

# Sector lookup
public_ids_set = set(public_rizal["school_id"])
private_ids_set = set(private_rizal["school_id"])

print(f"✓ School lookup built: {len(school_lookup):,} schools")
print(f"  Public schools: {len(public_ids_set):,}")
print(f"  Private schools: {len(private_ids_set):,}")
print(f"  ESC schools: {len(esc_school_ids):,}")

# ============================================================================
# OPTIMIZATION 2: Pre-extract coordinates into numpy arrays
# ============================================================================
# Build spatial index (same as before)
school_coords = all_rizal_schools[["latitude", "longitude"]].astype(float).values
school_ids_array = all_rizal_schools["school_id"].values

from scipy.spatial import cKDTree

tree = cKDTree(school_coords)

print(f"✓ Spatial index built for {len(all_rizal_schools):,} Rizal schools")

print(f"\nProcessing nearby schools for {len(rizal_learners):,} learners...")
print("(Optimized - should take ~2-3 minutes)\n")

# Track progress
progress_interval = max(1, len(rizal_learners) // 20)

# ============================================================================
# MAIN LOOP (optimized)
# ============================================================================
for idx, (row_idx, learner) in enumerate(rizal_learners.iterrows()):
    if idx % progress_interval == 0:
        print(
            f"  Progress: {idx:,} / {len(rizal_learners):,} ({idx/len(rizal_learners)*100:.1f}%)"
        )

    dest_id = learner["school_id_destination"]
    origin_id = learner["school_id_origin"]

    # Get destination school from lookup (O(1))
    if dest_id not in school_lookup:
        continue  # Destination outside Rizal

    dest_school = school_lookup[dest_id]
    dest_lat = float(dest_school["latitude"])
    dest_lon = float(dest_school["longitude"])

    # Get origin school from lookup (O(1))
    if origin_id not in school_lookup:
        continue

    origin_school = school_lookup[origin_id]
    origin_lat = float(origin_school["latitude"])
    origin_lon = float(origin_school["longitude"])

    # Find schools within 3km radius
    radius_km = 3.0
    radius_deg = radius_km / 111.0

    indices = tree.query_ball_point([dest_lat, dest_lon], radius_deg)

    nearby_schools = []
    for i in indices:
        nearby_id = school_ids_array[i]

        if nearby_id == dest_id:
            continue  # Exclude destination itself

        # Fast lookup from dictionary
        nearby_school = school_lookup[nearby_id]
        nearby_lat = float(nearby_school["latitude"])
        nearby_lon = float(nearby_school["longitude"])

        # Verify 3km threshold
        dist_to_dest = haversine_distance(dest_lat, dest_lon, nearby_lat, nearby_lon)

        if dist_to_dest <= radius_km:
            # Diagonal distance
            diagonal_dist = haversine_distance(
                origin_lat, origin_lon, nearby_lat, nearby_lon
            )

            # Determine sector (using set membership - O(1))
            if nearby_id in public_ids_set:
                sector = "Public"
                tuition = 0.0
            elif nearby_id in private_ids_set:
                sector = "Private"
                # Get tuition from nearby_school
                t = nearby_school.get("esc_average_tuition_fees", 0)
                m = nearby_school.get("esc_average_misc_fees", 0)
                o = nearby_school.get("esc_average_other_fees", 0)
                tuition = sum([x for x in [t, m, o] if pd.notna(x) and x > 0])
            else:
                sector = "Unknown"
                tuition = 0.0

            # Check if ESC
            is_esc = nearby_id in esc_school_ids

            nearby_schools.append(
                {
                    "school_id": nearby_id,
                    "diagonal_distance_km": diagonal_dist,
                    "tuition": tuition,
                    "sector": sector,
                    "is_esc": is_esc,
                }
            )

    # Sort by diagonal distance
    nearby_schools.sort(key=lambda x: x["diagonal_distance_km"])

    # Store counts
    rizal_learners.at[row_idx, "total_nearby_count"] = len(nearby_schools)

    public_count = sum(1 for s in nearby_schools if s["sector"] == "Public")
    private_count = sum(1 for s in nearby_schools if s["sector"] == "Private")
    esc_count = sum(1 for s in nearby_schools if s["is_esc"])

    rizal_learners.at[row_idx, "nearby_public_count"] = public_count
    rizal_learners.at[row_idx, "nearby_private_count"] = private_count
    rizal_learners.at[row_idx, "nearby_esc_count"] = esc_count

    # Store top 3
    for i, school in enumerate(nearby_schools[:3], start=1):
        rizal_learners.at[row_idx, f"nearby_{i}_school_id"] = school["school_id"]
        rizal_learners.at[row_idx, f"nearby_{i}_distance_km"] = school[
            "diagonal_distance_km"
        ]
        rizal_learners.at[row_idx, f"nearby_{i}_tuition_total"] = school["tuition"]
        rizal_learners.at[row_idx, f"nearby_{i}_sector"] = school["sector"]

    # Summarize remaining
    if len(nearby_schools) > 3:
        other_schools = nearby_schools[3:]
        rizal_learners.at[row_idx, "other_nearby_count"] = len(other_schools)

        other_tuitions = [s["tuition"] for s in other_schools if s["tuition"] > 0]
        if len(other_tuitions) > 0:
            rizal_learners.at[row_idx, "other_nearby_avg_tuition"] = np.mean(
                other_tuitions
            )

        other_distances = [s["diagonal_distance_km"] for s in other_schools]
        if len(other_distances) > 0:
            rizal_learners.at[row_idx, "other_nearby_min_distance_km"] = min(
                other_distances
            )

print(f"\n✓ Task 1.4 complete (optimized)")
print(f"  Added 19 columns")

======================================================================
TASK 1.4: Augment Top 3 Nearby Schools + Summary Stats (OPTIMIZED)
======================================================================

Building lookup dictionaries for fast access...
✓ School lookup built: 778 schools
  Public schools: 359
  Private schools: 419
  ESC schools: 111
✓ Spatial index built for 778 Rizal schools

Processing nearby schools for 48,585 learners...
(Optimized - should take ~2-3 minutes)

  Progress: 0 / 48,585 (0.0%)
  Progress: 2,429 / 48,585 (5.0%)
  Progress: 4,858 / 48,585 (10.0%)
  Progress: 7,287 / 48,585 (15.0%)
  Progress: 9,716 / 48,585 (20.0%)
  Progress: 12,145 / 48,585 (25.0%)
  Progress: 14,574 / 48,585 (30.0%)
  Progress: 17,003 / 48,585 (35.0%)
  Progress: 19,432 / 48,585 (40.0%)
  Progress: 21,861 / 48,585 (45.0%)
  Progress: 24,290 / 48,585 (50.0%)
  Progress: 26,719 / 48,585 (55.0%)
  Progress: 29,148 / 48,585 (60.0%)
  Progress: 31,577 / 48,585 (65.0%)
  Progress: 34,006 / 48,585 (70.0%)
  Progress: 36,435 / 48,585 (75.0%)
  Progress: 38,864 / 48,585 (80.0%)
  Progress: 41,293 / 48,585 (85.0%)
  Progress: 43,722 / 48,585 (90.0%)
  Progress: 46,151 / 48,585 (95.0%)
  Progress: 48,580 / 48,585 (100.0%)

✓ Task 1.4 complete (optimized)
  Added 19 columns

In [32]:
# Verify Task 1.4 results
print("\nVerifying nearby schools augmentation:")

nearby_1_populated = rizal_learners["nearby_1_school_id"].notna().sum()
nearby_3_populated = rizal_learners["nearby_3_school_id"].notna().sum()

print(f"\nTop 3 nearby schools:")
print(
    f"  Learners with nearby school 1: {nearby_1_populated:,} ({nearby_1_populated/len(rizal_learners)*100:.1f}%)"
)
print(
    f"  Learners with nearby school 3: {nearby_3_populated:,} ({nearby_3_populated/len(rizal_learners)*100:.1f}%)"
)

print(f"\nNearby schools statistics:")
print(f"  Mean total nearby count: {rizal_learners['total_nearby_count'].mean():.1f}")
print(
    f"  Learners with 0 nearby schools: {(rizal_learners['total_nearby_count'] == 0).sum():,}"
)
print(
    f"  Learners with 1-3 nearby schools: {((rizal_learners['total_nearby_count'] >= 1) & (rizal_learners['total_nearby_count'] <= 3)).sum():,}"
)
print(
    f"  Learners with >3 nearby schools: {(rizal_learners['total_nearby_count'] > 3).sum():,}"
)

print(f"\nNearby schools by sector:")
print(f"  Mean public nearby: {rizal_learners['nearby_public_count'].mean():.1f}")
print(f"  Mean private nearby: {rizal_learners['nearby_private_count'].mean():.1f}")
print(f"  Mean ESC nearby: {rizal_learners['nearby_esc_count'].mean():.1f}")

print(f"\nDistance statistics (nearby school 1 - diagonal):")
print(rizal_learners["nearby_1_distance_km"].describe())

Verifying nearby schools augmentation:

Top 3 nearby schools:
  Learners with nearby school 1: 46,732 (96.2%)
  Learners with nearby school 3: 46,020 (94.7%)

Nearby schools statistics:
  Mean total nearby count: 43.8
  Learners with 0 nearby schools: 1,853
  Learners with 1-3 nearby schools: 1,214
  Learners with >3 nearby schools: 45,518

Nearby schools by sector:
  Mean public nearby: 14.3
  Mean private nearby: 29.6
  Mean ESC nearby: 7.6

Distance statistics (nearby school 1 - diagonal):
count     46732.0
unique     1744.0
top           0.0
freq      37322.0
Name: nearby_1_distance_km, dtype: float64

In [33]:
cols = [
    "nearby_1_school_id",
    "nearby_1_distance_km",
    "nearby_1_tuition_total",
    "nearby_1_sector",
    "nearby_2_school_id",
    "nearby_2_distance_km",
    "nearby_2_tuition_total",
    "nearby_2_sector",
    "nearby_3_school_id",
    "nearby_3_distance_km",
    "nearby_3_tuition_total",
    "nearby_3_sector",
    "other_nearby_count",
    "other_nearby_avg_tuition",
    "other_nearby_min_distance_km",
    "total_nearby_count",
    "nearby_public_count",
    "nearby_private_count",
    "nearby_esc_count",
]

display(rizal_learners[cols].sample(3))

,nearby_1_school_id,nearby_1_distance_km,nearby_1_tuition_total,nearby_1_sector,nearby_2_school_id,nearby_2_distance_km,nearby_2_tuition_total,nearby_2_sector,nearby_3_school_id,nearby_3_distance_km,nearby_3_tuition_total,nearby_3_sector,other_nearby_count,other_nearby_avg_tuition,other_nearby_min_distance_km,total_nearby_count,nearby_public_count,nearby_private_count,nearby_esc_count
350314,109327,0.0,0.0,Public,402959,0.2017,40631.25,Private,402964,0.211334,26361.875,Private,68,44725.535147,0.289748,71,17,54,19
359567,109366,0.0,0.0,Public,402980,0.27794,0,Private,109372,0.723758,0.0,Public,25,27232.9,1.003374,28,14,14,5
869110,425565,0.0,0,Private,425563,0.031324,0,Private,109308,0.103703,0.0,Public,41,26986.439688,0.141817,44,14,30,8

### Task 1.5: Augment - Destination School JHS Attributes (OPTIMIZED)

Add destination school characteristics relevant for school choice:
- JHS enrollment (school size proxy)
- JHS seats (capacity)
- Capacity utilization
- School size category
- Has space indicator

In [34]:
print("=" * 70)
print("TASK 1.5: Augment Destination School JHS Attributes (OPTIMIZED)")
print("=" * 70)

# Initialize columns
rizal_learners["dest_jhs_enrollment"] = None
rizal_learners["dest_jhs_seats"] = None
rizal_learners["dest_capacity_utilization"] = None
rizal_learners["dest_has_space"] = None
rizal_learners["dest_size_category"] = None
rizal_learners["destination_is_esc"] = None

print(
    f"\nProcessing destination school attributes for {len(rizal_learners):,} learners..."
)

# ===================================================================
# OPTIMIZATION: Pre-build lookup dictionary
# ===================================================================
# Instead of filtering DataFrame repeatedly (O(n) per learner),
# create a single lookup dictionary (O(1) per learner)

print("\n[Optimization] Building school lookup dictionary...")

# Combine all schools (Rizal + external) for lookup
all_schools_combined = pd.concat(
    [
        all_rizal_schools,
        public_nodes[~public_nodes["school_id"].isin(all_rizal_schools["school_id"])],
        private_nodes[~private_nodes["school_id"].isin(all_rizal_schools["school_id"])],
    ],
    ignore_index=True,
)

print(f"  Combined schools before deduplication: {len(all_schools_combined):,}")

# FIX: Remove duplicate school IDs (keep first occurrence)
# Duplicates can occur if a school appears in multiple source DataFrames
all_schools_combined = all_schools_combined.drop_duplicates(
    subset="school_id", keep="first"
)

print(f"  Combined schools after deduplication: {len(all_schools_combined):,}")

# Create lookup dictionary: school_id -> school attributes
school_lookup = all_schools_combined.set_index("school_id").to_dict("index")

print(f"✓ School lookup built for {len(school_lookup):,} unique schools")

# ===================================================================
# PROCESS EACH LEARNER (Optimized with dictionary lookup)
# ===================================================================

# Track statistics
processed = 0
not_found = 0

for idx, (row_idx, learner) in enumerate(rizal_learners.iterrows()):
    dest_id = learner["school_id_destination"]

    # O(1) dictionary lookup instead of O(n) DataFrame filter
    dest_school = school_lookup.get(dest_id)

    if dest_school is None:
        # Destination not found
        not_found += 1
        continue

    processed += 1

    # Extract attributes (dictionary access is O(1))
    jhs_enrollment = dest_school.get("enrollment_jhs")
    jhs_seats = dest_school.get("seats_jhs")
    offers_jhs = dest_school.get("offers_jhs")
    sector = dest_school.get("sector")

    # Store basic attributes
    rizal_learners.at[row_idx, "dest_jhs_enrollment"] = jhs_enrollment
    rizal_learners.at[row_idx, "dest_jhs_seats"] = jhs_seats

    # Calculate capacity utilization
    if pd.notna(jhs_enrollment) and pd.notna(jhs_seats) and jhs_seats > 0:
        capacity_util = jhs_enrollment / jhs_seats
        rizal_learners.at[row_idx, "dest_capacity_utilization"] = capacity_util
        rizal_learners.at[row_idx, "dest_has_space"] = capacity_util < 1.0

    # School size category (based on JHS enrollment)
    if pd.notna(jhs_enrollment):
        if jhs_enrollment < 600:
            size_cat = "Small"
        elif jhs_enrollment < 1_200:
            size_cat = "Medium"
        elif jhs_enrollment < 1_800:
            size_cat = "Large"
        else:
            size_cat = "Very Large"
        rizal_learners.at[row_idx, "dest_size_category"] = size_cat

    # Check if destination is ESC-delivering school
    rizal_learners.at[row_idx, "destination_is_esc"] = dest_id in esc_school_ids

print(f"\n✓ Task 1.5 complete")
print(f"  Processed: {processed:,} learners ({processed/len(rizal_learners)*100:.1f}%)")
print(f"  Not found: {not_found:,} learners ({not_found/len(rizal_learners)*100:.1f}%)")
print(f"  Added 6 columns for destination school attributes")

# CELL: Code - Verification
# Verify Task 1.5 results
print("\nVerifying destination school attributes:")

dest_attrs_populated = rizal_learners["dest_jhs_enrollment"].notna().sum()
print(
    f"\nDestination schools with JHS enrollment data: {dest_attrs_populated:,} ({dest_attrs_populated/len(rizal_learners)*100:.1f}%)"
)

print(f"\nDestination school size category:")
print(rizal_learners["dest_size_category"].value_counts())

print(f"\nDestination school capacity:")
has_space_count = rizal_learners["dest_has_space"].sum()
over_capacity_count = (rizal_learners["dest_has_space"] == False).sum()
print(f"  Schools with space (util < 1.0): {has_space_count:,}")
print(f"  Schools over capacity (util >= 1.0): {over_capacity_count:,}")

print(f"\nDestination is ESC-delivering school:")
esc_dest_count = rizal_learners["destination_is_esc"].sum()
print(
    f"  ESC destinations: {esc_dest_count:,} ({esc_dest_count/len(rizal_learners)*100:.1f}%)"
)

print(f"\nJHS Enrollment statistics:")
print(rizal_learners["dest_jhs_enrollment"].describe())

print(f"\nCapacity utilization statistics:")
print(rizal_learners["dest_capacity_utilization"].describe())

======================================================================
TASK 1.5: Augment Destination School JHS Attributes (OPTIMIZED)
======================================================================

Processing destination school attributes for 48,585 learners...

[Optimization] Building school lookup dictionary...
  Combined schools before deduplication: 54,204
  Combined schools after deduplication: 54,174
✓ School lookup built for 54,174 unique schools

✓ Task 1.5 complete
  Processed: 48,585 learners (100.0%)
  Not found: 0 learners (0.0%)
  Added 6 columns for destination school attributes

Verifying destination school attributes:

Destination schools with JHS enrollment data: 48,585 (100.0%)

Destination school size category:
dest_size_category
Very Large    28600
Small          9373
Medium         5891
Large          4721
Name: count, dtype: int64

Destination school capacity:
  Schools with space (util < 1.0): 9,596
  Schools over capacity (util >= 1.0): 38,946

Destination is ESC-delivering school:
  ESC destinations: 5,935 (12.2%)

JHS Enrollment statistics:
count     48585.0
unique      967.0
top           0.0
freq       2637.0
Name: dest_jhs_enrollment, dtype: float64

Capacity utilization statistics:
count     48542.0
unique     1201.0
top           0.0
freq       2637.0
Name: dest_capacity_utilization, dtype: float64

In [35]:
# Verify Task 1.5 results
print("\nVerifying destination school attributes:")

dest_attrs_populated = rizal_learners["dest_jhs_enrollment"].notna().sum()
print(
    f"\nDestination schools with JHS enrollment data: {dest_attrs_populated:,} ({dest_attrs_populated/len(rizal_learners)*100:.1f}%)"
)

print(f"\nDestination school size category:")
print(rizal_learners["dest_size_category"].value_counts())

print(f"\nDestination school capacity:")
has_space_count = rizal_learners["dest_has_space"].sum()
over_capacity_count = (rizal_learners["dest_has_space"] == False).sum()
print(f"  Schools with space (util < 1.0): {has_space_count:,}")
print(f"  Schools over capacity (util >= 1.0): {over_capacity_count:,}")

print(f"\nDestination is ESC-delivering school:")
esc_dest_count = rizal_learners["destination_is_esc"].sum()
print(
    f"  ESC destinations: {esc_dest_count:,} ({esc_dest_count/len(rizal_learners)*100:.1f}%)"
)

print(f"\nJHS Enrollment statistics:")
print(rizal_learners["dest_jhs_enrollment"].describe())

print(f"\nCapacity utilization statistics:")
print(rizal_learners["dest_capacity_utilization"].describe())

Verifying destination school attributes:

Destination schools with JHS enrollment data: 48,585 (100.0%)

Destination school size category:
dest_size_category
Very Large    28600
Small          9373
Medium         5891
Large          4721
Name: count, dtype: int64

Destination school capacity:
  Schools with space (util < 1.0): 9,596
  Schools over capacity (util >= 1.0): 38,946

Destination is ESC-delivering school:
  ESC destinations: 5,935 (12.2%)

JHS Enrollment statistics:
count     48585.0
unique      967.0
top           0.0
freq       2637.0
Name: dest_jhs_enrollment, dtype: float64

Capacity utilization statistics:
count     48542.0
unique     1201.0
top           0.0
freq       2637.0
Name: dest_capacity_utilization, dtype: float64

In [36]:
rizal_learners.head(2)

,region,division,lrn,school_id_destination,school_name_destination,sy_grade6,school_id_origin,school_name_origin,school_year,school_id_origin_valid,school_id_destination_valid,both_school_ids_valid,sector_origin,municipality_origin,sector_destination,municipality_destination,origin_in_public_nodes,origin_in_private_nodes,origin_in_node_tables,destination_in_public_nodes,destination_in_private_nodes,destination_in_node_tables,both_in_node_tables,both_in_enrollment,fully_valid,esc_subsidy_amount,is_beneficiary,latitude_origin,longitude_origin,latitude_destination,longitude_destination,distance_straightline_km,flow_type,nearest_esc_1_school_id,nearest_esc_1_distance_km,nearest_esc_1_tuition_total,nearest_esc_2_school_id,nearest_esc_2_distance_km,nearest_esc_2_tuition_total,nearest_esc_3_school_id,nearest_esc_3_distance_km,nearest_esc_3_tuition_total,nearest_esc_4_school_id,nearest_esc_4_distance_km,nearest_esc_4_tuition_total,nearest_esc_5_school_id,nearest_esc_5_distance_km,nearest_esc_5_tuition_total,nearest_public_jhs_1_school_id,nearest_public_jhs_1_distance_km,nearest_public_jhs_1_tuition_total,nearest_public_jhs_2_school_id,nearest_public_jhs_2_distance_km,nearest_public_jhs_2_tuition_total,nearest_public_jhs_3_school_id,nearest_public_jhs_3_distance_km,nearest_public_jhs_3_tuition_total,nearest_public_jhs_4_school_id,nearest_public_jhs_4_distance_km,nearest_public_jhs_4_tuition_total,nearest_public_jhs_5_school_id,nearest_public_jhs_5_distance_km,nearest_public_jhs_5_tuition_total,nearby_1_school_id,nearby_1_distance_km,nearby_1_tuition_total,nearby_1_sector,nearby_2_school_id,nearby_2_distance_km,nearby_2_tuition_total,nearby_2_sector,nearby_3_school_id,nearby_3_distance_km,nearby_3_tuition_total,nearby_3_sector,other_nearby_count,other_nearby_avg_tuition,other_nearby_min_distance_km,total_nearby_count,nearby_public_count,nearby_private_count,nearby_esc_count,dest_jhs_enrollment,dest_jhs_seats,dest_capacity_utilization,dest_has_space,dest_size_category,destination_is_esc
533,Region IV-A,Rizal,100036160032,301433,"Carlos ""Botong"" V. Francisco Memorial Nationa...",2022.0,109316,Sitio Mata ES,SY 2023-2024,True,True,True,public,BINANGONAN,public,ANGONO,True,False,True,True,False,True,True,True,True,NaN,False,14.540718,121.196099,14.542272,121.183972,1.316640,public_to_public_nonbeneficiary,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,109316,0.0,0.0,Public,410175,0.130824,0,Private,425707,0.454952,0,Private,17,39732.303333,0.615542,20,8,12,3,2393.0,621.0,3.853462,False,Very Large,False
681,Region IV-A,Rizal,100047160008,301439,Gen. Licerio Geronimo National High School,2022.0,109479,San Rafael ES,SY 2023-2024,True,True,True,public,RODRIGUEZ (MONTALBAN),public,RODRIGUEZ (MONTALBAN),True,False,True,True,False,True,True,True,True,NaN,False,14.732105,121.158692,14.731820,121.149660,0.971814,public_to_public_nonbeneficiary,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,None,None,0.0,109479,0.0,0.0,Public,425686,0.313503,0,Private,425623,0.343215,44048.14,Private,71,40687.0,0.509759,74,25,49,7,4876.0,1190.0,4.097479,False,Very Large,False

### Task 1.6: Add Road Network Distance from Distance Matrix (OPTIMIZED)

Add road network distance from origin to destination (key feature for DCE model).
The unified dataset already has `distance_straightline_km`, now we add `distance_road_km`.

In [37]:
print("=" * 70)
print("TASK 1.6: Add Road Network Distance from Distance Matrix (OPTIMIZED)")
print("=" * 70)

print(f"\nAdding road network distances for {len(rizal_learners):,} learners...")

# ===================================================================
# OPTIMIZATION: Vectorized lookup using pandas merge/map
# ===================================================================
# Instead of looping through each learner and doing dictionary lookups,
# we'll use pandas vectorized operations

print("\n[Optimization] Using vectorized pandas operations...")

# Step 1: Create a mapping DataFrame from distance matrix
# Distance matrix format: index=origin_id, columns=destination_id, values=distance_m
# We need to melt it into long format: (origin, destination, distance)

print("  Preparing distance matrix lookup...")

# Create temporary columns for merge
rizal_learners["_origin_id"] = rizal_learners["school_id_origin"]
rizal_learners["_dest_id"] = rizal_learners["school_id_destination"]

# Initialize distance column
rizal_learners["distance_road_km"] = None

# ===================================================================
# APPROACH: Direct lookup using .loc with error handling
# ===================================================================
# This is faster than melting the entire distance matrix

distances_found = 0
distances_missing = 0

# Use .loc for vectorized lookup with proper indexing
for row_idx, learner in rizal_learners.iterrows():
    origin_id = learner["school_id_origin"]
    dest_id = learner["school_id_destination"]

    try:
        # Direct matrix lookup (O(1) with proper indexing)
        distance_m = distance_matrix.loc[origin_id, dest_id]

        if pd.notna(distance_m):
            rizal_learners.at[row_idx, "distance_road_km"] = (
                distance_m / 1000
            )  # Convert to km
            distances_found += 1
        else:
            distances_missing += 1
    except (KeyError, IndexError):
        # Origin or destination not in matrix
        distances_missing += 1

# Clean up temporary columns
rizal_learners.drop(columns=["_origin_id", "_dest_id"], inplace=True, errors="ignore")

print(f"\n✓ Task 1.6 complete")
print(
    f"  Road distances found: {distances_found:,} ({distances_found/len(rizal_learners)*100:.1f}%)"
)
print(
    f"  Road distances missing: {distances_missing:,} ({distances_missing/len(rizal_learners)*100:.1f}%)"
)
print(f"  Added 1 column: distance_road_km")

======================================================================
TASK 1.6: Add Road Network Distance from Distance Matrix (OPTIMIZED)
======================================================================

Adding road network distances for 48,585 learners...

[Optimization] Using vectorized pandas operations...
  Preparing distance matrix lookup...

✓ Task 1.6 complete
  Road distances found: 13,426 (27.6%)
  Road distances missing: 35,159 (72.4%)
  Added 1 column: distance_road_km

In [38]:
# Verify Task 1.6 and compare to straight-line distance
print("\nVerifying road network distance:")

print(f"\nRoad distance statistics:")
print(rizal_learners["distance_road_km"].describe())

print(f"\nStraight-line distance statistics:")
print(rizal_learners["distance_straightline_km"].describe())

# Compare road vs straight-line distance
valid_both = rizal_learners[
    rizal_learners["distance_road_km"].notna()
    & rizal_learners["distance_straightline_km"].notna()
]

if len(valid_both) > 0:
    ratio = valid_both["distance_road_km"] / valid_both["distance_straightline_km"]
    print(f"\nRoad/Straight-line distance ratio (circuity factor):")
    print(f"  Mean: {ratio.mean():.2f}x")
    print(f"  Median: {ratio.median():.2f}x")
    print(f"  Min: {ratio.min():.2f}x")
    print(f"  Max: {ratio.max():.2f}x")
    print(f"  Std Dev: {ratio.std():.2f}")
    print(f"  (Typical values: 1.2-1.5x for urban, 1.5-2.5x for rural)")

    # Check for outliers
    outliers_low = (ratio < 1.0).sum()
    outliers_high = (ratio > 3.0).sum()
    print(f"\n  Outliers:")
    print(
        f"    Ratio < 1.0 (suspicious): {outliers_low:,} ({outliers_low/len(valid_both)*100:.2f}%)"
    )
    print(
        f"    Ratio > 3.0 (very circuitous): {outliers_high:,} ({outliers_high/len(valid_both)*100:.2f}%)"
    )

Verifying road network distance:

Road distance statistics:
count     13426.0
unique      554.0
top           0.0
freq       4369.0
Name: distance_road_km, dtype: float64

Straight-line distance statistics:
count    48585.000000
mean         6.750478
std         39.813979
min          0.000000
25%          0.269504
50%          0.819524
75%          1.789550
max        718.471998
Name: distance_straightline_km, dtype: float64

Road/Straight-line distance ratio (circuity factor):
  Mean: 5.56x
  Median: 1.92x
  Min: 0.00x
  Max: 135.08x
  Std Dev: 9.84
  (Typical values: 1.2-1.5x for urban, 1.5-2.5x for rural)

  Outliers:
    Ratio < 1.0 (suspicious): 1,420 (10.58%)
    Ratio > 3.0 (very circuitous): 3,973 (29.59%)

### Phase 1 Complete - Save Augmented Dataset

All augmentation tasks complete. Save final augmented dataset with all features.

In [31]:
# Save final Phase 1 dataset
output_file = OUTPUT_DIR / "rizal_learners_augmented.csv"
rizal_learners.to_csv(output_file, index=False)

print("=" * 70)
print("PHASE 1 COMPLETE: Data Preparation")
print("=" * 70)

print(f"\n✓ Final augmented dataset saved: {output_file}")
print(f"  Total learners: {len(rizal_learners):,}")
print(f"  Total columns: {len(rizal_learners.columns):,}")

print(f"\nFeature groups added:")
print(f"  Task 1.1: Base Rizal learner data (33 original columns)")
print(f"  Task 1.3: Nearest 5 ESC + 5 Public JHS schools (30 columns)")
print(f"  Task 1.4: Top 3 nearby schools + summary stats (19 columns)")
print(f"  Task 1.5: Destination school JHS attributes (6 columns)")
print(f"  Task 1.6: Road network distance (1 column)")
print(f"  TOTAL: ~89 columns")

print(f"\nData quality summary:")
print(
    f"  Learners with nearest ESC 1: {rizal_learners['nearest_esc_1_school_id'].notna().sum():,}"
)
print(
    f"  Learners with nearest public JHS 1: {rizal_learners['nearest_public_jhs_1_school_id'].notna().sum():,}"
)
print(
    f"  Learners with nearby school 1: {rizal_learners['nearby_1_school_id'].notna().sum():,}"
)
print(
    f"  Learners with road distance: {rizal_learners['distance_road_km'].notna().sum():,}"
)
print(
    f"  Learners with dest JHS enrollment: {rizal_learners['dest_jhs_enrollment'].notna().sum():,}"
)

print(f"\n✓ Ready for Phase 2: Feature Engineering for DCE Model")

# CELL: Code - Column summary
# Display all column names for reference
print("\nComplete column list:")
print(f"Total columns: {len(rizal_learners.columns)}")
print("\nColumn names:")
for i, col in enumerate(rizal_learners.columns, 1):
    print(f"  {i:2d}. {col}")

======================================================================
PHASE 1 COMPLETE: Data Preparation
======================================================================

✓ Final augmented dataset saved: output/rizal_choice_simulation/rizal_learners_augmented.csv
  Total learners: 48,585
  Total columns: 89

Feature groups added:
  Task 1.1: Base Rizal learner data (33 original columns)
  Task 1.3: Nearest 5 ESC + 5 Public JHS schools (30 columns)
  Task 1.4: Top 3 nearby schools + summary stats (19 columns)
  Task 1.5: Destination school JHS attributes (6 columns)
  Task 1.6: Road network distance (1 column)
  TOTAL: ~89 columns

Data quality summary:
  Learners with nearest ESC 1: 22,603
  Learners with nearest public JHS 1: 21,689
  Learners with nearby school 1: 46,732
  Learners with road distance: 13,426
  Learners with dest JHS enrollment: 48,585

✓ Ready for Phase 2: Feature Engineering for DCE Model

Complete column list:
Total columns: 89

Column names:
   1. region
   2. division
   3. lrn
   4. school_id_destination
   5. school_name_destination
   6. sy_grade6
   7. school_id_origin
   8. school_name_origin
   9. school_year
  10. school_id_origin_valid
  11. school_id_destination_valid
  12. both_school_ids_valid
  13. sector_origin
  14. municipality_origin
  15. sector_destination
  16. municipality_destination
  17. origin_in_public_nodes
  18. origin_in_private_nodes
  19. origin_in_node_tables
  20. destination_in_public_nodes
  21. destination_in_private_nodes
  22. destination_in_node_tables
  23. both_in_node_tables
  24. both_in_enrollment
  25. fully_valid
  26. esc_subsidy_amount
  27. is_beneficiary
  28. latitude_origin
  29. longitude_origin
  30. latitude_destination
  31. longitude_destination
  32. distance_straightline_km
  33. flow_type
  34. nearest_esc_1_school_id
  35. nearest_esc_1_distance_km
  36. nearest_esc_1_tuition_total
  37. nearest_esc_2_school_id
  38. nearest_esc_2_distance_km
  39. nearest_esc_2_tuition_total
  40. nearest_esc_3_school_id
  41. nearest_esc_3_distance_km
  42. nearest_esc_3_tuition_total
  43. nearest_esc_4_school_id
  44. nearest_esc_4_distance_km
  45. nearest_esc_4_tuition_total
  46. nearest_esc_5_school_id
  47. nearest_esc_5_distance_km
  48. nearest_esc_5_tuition_total
  49. nearest_public_jhs_1_school_id
  50. nearest_public_jhs_1_distance_km
  51. nearest_public_jhs_1_tuition_total
  52. nearest_public_jhs_2_school_id
  53. nearest_public_jhs_2_distance_km
  54. nearest_public_jhs_2_tuition_total
  55. nearest_public_jhs_3_school_id
  56. nearest_public_jhs_3_distance_km
  57. nearest_public_jhs_3_tuition_total
  58. nearest_public_jhs_4_school_id
  59. nearest_public_jhs_4_distance_km
  60. nearest_public_jhs_4_tuition_total
  61. nearest_public_jhs_5_school_id
  62. nearest_public_jhs_5_distance_km
  63. nearest_public_jhs_5_tuition_total
  64. nearby_1_school_id
  65. nearby_1_distance_km
  66. nearby_1_tuition_total
  67. nearby_1_sector
  68. nearby_2_school_id
  69. nearby_2_distance_km
  70. nearby_2_tuition_total
  71. nearby_2_sector
  72. nearby_3_school_id
  73. nearby_3_distance_km
  74. nearby_3_tuition_total
  75. nearby_3_sector
  76. other_nearby_count
  77. other_nearby_avg_tuition
  78. other_nearby_min_distance_km
  79. total_nearby_count
  80. nearby_public_count
  81. nearby_private_count
  82. nearby_esc_count
  83. dest_jhs_enrollment
  84. dest_jhs_seats
  85. dest_capacity_utilization
  86. dest_has_space
  87. dest_size_category
  88. destination_is_esc
  89. distance_road_km

In [32]:
# Display all column names for reference
print("\nComplete column list:")
print(f"Total columns: {len(rizal_learners.columns)}")
print("\nColumn names:")
for i, col in enumerate(rizal_learners.columns, 1):
    print(f"  {i:2d}. {col}")

Complete column list:
Total columns: 89

Column names:
   1. region
   2. division
   3. lrn
   4. school_id_destination
   5. school_name_destination
   6. sy_grade6
   7. school_id_origin
   8. school_name_origin
   9. school_year
  10. school_id_origin_valid
  11. school_id_destination_valid
  12. both_school_ids_valid
  13. sector_origin
  14. municipality_origin
  15. sector_destination
  16. municipality_destination
  17. origin_in_public_nodes
  18. origin_in_private_nodes
  19. origin_in_node_tables
  20. destination_in_public_nodes
  21. destination_in_private_nodes
  22. destination_in_node_tables
  23. both_in_node_tables
  24. both_in_enrollment
  25. fully_valid
  26. esc_subsidy_amount
  27. is_beneficiary
  28. latitude_origin
  29. longitude_origin
  30. latitude_destination
  31. longitude_destination
  32. distance_straightline_km
  33. flow_type
  34. nearest_esc_1_school_id
  35. nearest_esc_1_distance_km
  36. nearest_esc_1_tuition_total
  37. nearest_esc_2_school_id
  38. nearest_esc_2_distance_km
  39. nearest_esc_2_tuition_total
  40. nearest_esc_3_school_id
  41. nearest_esc_3_distance_km
  42. nearest_esc_3_tuition_total
  43. nearest_esc_4_school_id
  44. nearest_esc_4_distance_km
  45. nearest_esc_4_tuition_total
  46. nearest_esc_5_school_id
  47. nearest_esc_5_distance_km
  48. nearest_esc_5_tuition_total
  49. nearest_public_jhs_1_school_id
  50. nearest_public_jhs_1_distance_km
  51. nearest_public_jhs_1_tuition_total
  52. nearest_public_jhs_2_school_id
  53. nearest_public_jhs_2_distance_km
  54. nearest_public_jhs_2_tuition_total
  55. nearest_public_jhs_3_school_id
  56. nearest_public_jhs_3_distance_km
  57. nearest_public_jhs_3_tuition_total
  58. nearest_public_jhs_4_school_id
  59. nearest_public_jhs_4_distance_km
  60. nearest_public_jhs_4_tuition_total
  61. nearest_public_jhs_5_school_id
  62. nearest_public_jhs_5_distance_km
  63. nearest_public_jhs_5_tuition_total
  64. nearby_1_school_id
  65. nearby_1_distance_km
  66. nearby_1_tuition_total
  67. nearby_1_sector
  68. nearby_2_school_id
  69. nearby_2_distance_km
  70. nearby_2_tuition_total
  71. nearby_2_sector
  72. nearby_3_school_id
  73. nearby_3_distance_km
  74. nearby_3_tuition_total
  75. nearby_3_sector
  76. other_nearby_count
  77. other_nearby_avg_tuition
  78. other_nearby_min_distance_km
  79. total_nearby_count
  80. nearby_public_count
  81. nearby_private_count
  82. nearby_esc_count
  83. dest_jhs_enrollment
  84. dest_jhs_seats
  85. dest_capacity_utilization
  86. dest_has_space
  87. dest_size_category
  88. destination_is_esc
  89. distance_road_km

## Phase 2

In [35]:
# Load augmented learner data from Task 1.6
print("\nLoading augmented learner data...")
rizal_learners_augmented = pd.read_csv(
    "output/rizal_choice_simulation/rizal_learners_augmented.csv"
)

print(f"✓ Loaded {len(rizal_learners_augmented):,} learner records")
print(f"  Columns: {rizal_learners_augmented.shape[1]}")

Loading augmented learner data...
✓ Loaded 48,585 learner records
  Columns: 89

### Task 2.1

In [36]:
# CELL: Diagnostic - Check actual column names
print("=" * 80)
print("DIAGNOSTIC: Checking Actual Column Names")
print("=" * 80)

print(f"\nTotal columns in augmented dataset: {len(rizal_learners_augmented.columns)}")

# Group columns by task
print("\n" + "-" * 80)
print("TASK 1.4 COLUMNS (Nearby schools):")
print("-" * 80)
nearby_cols = [
    col for col in rizal_learners_augmented.columns if "nearby" in col.lower()
]
for i, col in enumerate(nearby_cols, 1):
    print(f"  {i:2d}. {col}")

print("\n" + "-" * 80)
print("TASK 1.5 COLUMNS (Destination attributes):")
print("-" * 80)
dest_cols = [col for col in rizal_learners_augmented.columns if "dest" in col.lower()]
for i, col in enumerate(dest_cols, 1):
    print(f"  {i:2d}. {col}")

print("\n" + "-" * 80)
print("TASK 1.3 COLUMNS (Nearest ESC/Public):")
print("-" * 80)
nearest_cols = [
    col for col in rizal_learners_augmented.columns if "nearest" in col.lower()
]
for i, col in enumerate(nearest_cols, 1):
    print(f"  {i:2d}. {col}")

print("\n" + "-" * 80)
print("TASK 1.6 COLUMNS (Distance):")
print("-" * 80)
dist_cols = [
    col for col in rizal_learners_augmented.columns if "distance" in col.lower()
]
for i, col in enumerate(dist_cols, 1):
    print(f"  {i:2d}. {col}")

================================================================================
DIAGNOSTIC: Checking Actual Column Names
================================================================================

Total columns in augmented dataset: 89

--------------------------------------------------------------------------------
TASK 1.4 COLUMNS (Nearby schools):
--------------------------------------------------------------------------------
   1. nearby_1_school_id
   2. nearby_1_distance_km
   3. nearby_1_tuition_total
   4. nearby_1_sector
   5. nearby_2_school_id
   6. nearby_2_distance_km
   7. nearby_2_tuition_total
   8. nearby_2_sector
   9. nearby_3_school_id
  10. nearby_3_distance_km
  11. nearby_3_tuition_total
  12. nearby_3_sector
  13. other_nearby_count
  14. other_nearby_avg_tuition
  15. other_nearby_min_distance_km
  16. total_nearby_count
  17. nearby_public_count
  18. nearby_private_count
  19. nearby_esc_count

--------------------------------------------------------------------------------
TASK 1.5 COLUMNS (Destination attributes):
--------------------------------------------------------------------------------
   1. school_id_destination
   2. school_name_destination
   3. school_id_destination_valid
   4. sector_destination
   5. municipality_destination
   6. destination_in_public_nodes
   7. destination_in_private_nodes
   8. destination_in_node_tables
   9. latitude_destination
  10. longitude_destination
  11. dest_jhs_enrollment
  12. dest_jhs_seats
  13. dest_capacity_utilization
  14. dest_has_space
  15. dest_size_category
  16. destination_is_esc

--------------------------------------------------------------------------------
TASK 1.3 COLUMNS (Nearest ESC/Public):
--------------------------------------------------------------------------------
   1. nearest_esc_1_school_id
   2. nearest_esc_1_distance_km
   3. nearest_esc_1_tuition_total
   4. nearest_esc_2_school_id
   5. nearest_esc_2_distance_km
   6. nearest_esc_2_tuition_total
   7. nearest_esc_3_school_id
   8. nearest_esc_3_distance_km
   9. nearest_esc_3_tuition_total
  10. nearest_esc_4_school_id
  11. nearest_esc_4_distance_km
  12. nearest_esc_4_tuition_total
  13. nearest_esc_5_school_id
  14. nearest_esc_5_distance_km
  15. nearest_esc_5_tuition_total
  16. nearest_public_jhs_1_school_id
  17. nearest_public_jhs_1_distance_km
  18. nearest_public_jhs_1_tuition_total
  19. nearest_public_jhs_2_school_id
  20. nearest_public_jhs_2_distance_km
  21. nearest_public_jhs_2_tuition_total
  22. nearest_public_jhs_3_school_id
  23. nearest_public_jhs_3_distance_km
  24. nearest_public_jhs_3_tuition_total
  25. nearest_public_jhs_4_school_id
  26. nearest_public_jhs_4_distance_km
  27. nearest_public_jhs_4_tuition_total
  28. nearest_public_jhs_5_school_id
  29. nearest_public_jhs_5_distance_km
  30. nearest_public_jhs_5_tuition_total

--------------------------------------------------------------------------------
TASK 1.6 COLUMNS (Distance):
--------------------------------------------------------------------------------
   1. distance_straightline_km
   2. nearest_esc_1_distance_km
   3. nearest_esc_2_distance_km
   4. nearest_esc_3_distance_km
   5. nearest_esc_4_distance_km
   6. nearest_esc_5_distance_km
   7. nearest_public_jhs_1_distance_km
   8. nearest_public_jhs_2_distance_km
   9. nearest_public_jhs_3_distance_km
  10. nearest_public_jhs_4_distance_km
  11. nearest_public_jhs_5_distance_km
  12. nearby_1_distance_km
  13. nearby_2_distance_km
  14. nearby_3_distance_km
  15. other_nearby_min_distance_km
  16. distance_road_km

In [37]:
# ===================================================================
# TASK 2.1: CREATE DCE FEATURE MATRIX (FIXED COLUMN NAMES)
# ===================================================================

# CELL: Task 2.1 - Create DCE Feature Matrix
print("=" * 80)
print("TASK 2.1: CREATE DCE FEATURE MATRIX")
print("=" * 80)

# Load augmented learner data from Task 1.6
print("\nLoading augmented learner data...")
print(f"✓ Loaded {len(rizal_learners_augmented):,} learner records")
print(f"  Columns: {rizal_learners_augmented.shape[1]}")

print("\n" + "-" * 80)
print("FEATURE ENGINEERING")
print("-" * 80)

# Initialize feature matrix (start with base columns)
feature_matrix = rizal_learners_augmented.copy()

# ===================================================================
# 1. DESTINATION SCHOOL FEATURES
# ===================================================================
print("\n[1/7] Engineering destination school features...")

# Binary indicators for sector
feature_matrix["dest_is_public"] = (
    feature_matrix["sector_destination"] == "Public"
).astype(int)
feature_matrix["dest_is_private"] = (
    feature_matrix["sector_destination"] == "Private"
).astype(int)
feature_matrix["dest_is_esc"] = feature_matrix["destination_is_esc"].astype(int)

# Create binary indicators for size category (4 levels)
feature_matrix["dest_size_small"] = (
    feature_matrix["dest_size_category"] == "Small"
).astype(int)
feature_matrix["dest_size_medium"] = (
    feature_matrix["dest_size_category"] == "Medium"
).astype(int)
feature_matrix["dest_size_large"] = (
    feature_matrix["dest_size_category"] == "Large"
).astype(int)
feature_matrix["dest_size_very_large"] = (
    feature_matrix["dest_size_category"] == "Very Large"
).astype(int)

# Log transform for enrollment and seats (reduce skewness)
feature_matrix["dest_jhs_enrollment_log"] = np.log1p(
    feature_matrix["dest_jhs_enrollment"].fillna(0)
)
feature_matrix["dest_jhs_seats_log"] = np.log1p(
    feature_matrix["dest_jhs_seats"].fillna(0)
)

# Capacity utilization - fill NaN with median
median_capacity = feature_matrix["dest_capacity_utilization"].median()
feature_matrix["dest_capacity_utilization_filled"] = feature_matrix[
    "dest_capacity_utilization"
].fillna(median_capacity)

print(f"  Created {3 + 4 + 2 + 1} destination school features")

# ===================================================================
# 2. DISTANCE/ACCESSIBILITY FEATURES
# ===================================================================
print("\n[2/7] Engineering distance/accessibility features...")

# Fill missing road distances with straight-line distance * 1.3 (typical road circuity factor)
feature_matrix["distance_road_km_filled"] = feature_matrix["distance_road_km"].fillna(
    feature_matrix["distance_straightline_km"] * 1.3
)

# Log transform distance (diminishing returns at longer distances)
feature_matrix["distance_road_log"] = np.log1p(
    feature_matrix["distance_road_km_filled"]
)

# Distance squared (non-linear distance penalty)
feature_matrix["distance_road_sq"] = feature_matrix["distance_road_km_filled"] ** 2

# Binary indicators for distance thresholds
feature_matrix["distance_within_3km"] = (
    feature_matrix["distance_road_km_filled"] <= 3
).astype(int)
feature_matrix["distance_within_5km"] = (
    feature_matrix["distance_road_km_filled"] <= 5
).astype(int)
feature_matrix["distance_within_10km"] = (
    feature_matrix["distance_road_km_filled"] <= 10
).astype(int)

print(f"  Created {1 + 2 + 3} distance features")

# ===================================================================
# 3. COMPETITION/MARKET CONTEXT FEATURES
# ===================================================================
print("\n[3/7] Engineering competition/market context features...")

# CORRECTED: Actual column names from Task 1.4
# - total_nearby_count
# - nearby_public_count
# - nearby_private_count
# - nearby_esc_count
# - other_nearby_avg_tuition
# - other_nearby_min_distance_km

# Competition density: schools per km²
nearby_search_area_km2 = 3.14159 * (3**2)  # 3km radius
feature_matrix["nearby_school_density"] = (
    feature_matrix["total_nearby_count"] / nearby_search_area_km2
)

# Competition mix ratios
feature_matrix["nearby_public_ratio"] = feature_matrix["nearby_public_count"] / (
    feature_matrix["total_nearby_count"] + 1
)
feature_matrix["nearby_private_ratio"] = feature_matrix["nearby_private_count"] / (
    feature_matrix["total_nearby_count"] + 1
)
feature_matrix["nearby_esc_ratio"] = feature_matrix["nearby_esc_count"] / (
    feature_matrix["total_nearby_count"] + 1
)

# Log transform tuition (reduce skewness)
feature_matrix["nearby_avg_tuition_log"] = np.log1p(
    feature_matrix["other_nearby_avg_tuition"].fillna(0)
)

# Closest competitor distance
feature_matrix["nearby_min_distance_log"] = np.log1p(
    feature_matrix["other_nearby_min_distance_km"].fillna(10)
)

print(f"  Created {1 + 3 + 1 + 1} competition features")

# ===================================================================
# 4. ALTERNATIVE AVAILABILITY FEATURES
# ===================================================================
print("\n[4/7] Engineering alternative availability features...")

# CORRECTED: Actual column names from Task 1.3
# ESC: nearest_esc_1_distance_km, nearest_esc_1_tuition_total, etc. (1-5)
# Public: nearest_public_jhs_1_distance_km, nearest_public_jhs_1_tuition_total, etc. (1-5)

# ESC availability indicators
feature_matrix["esc_available_within_3km"] = (
    (feature_matrix["nearest_esc_1_distance_km"] <= 3)
    | (feature_matrix["nearest_esc_2_distance_km"] <= 3)
    | (feature_matrix["nearest_esc_3_distance_km"] <= 3)
).astype(int)

feature_matrix["esc_available_within_5km"] = (
    (feature_matrix["nearest_esc_1_distance_km"] <= 5)
    | (feature_matrix["nearest_esc_2_distance_km"] <= 5)
    | (feature_matrix["nearest_esc_3_distance_km"] <= 5)
).astype(int)

# Public JHS availability indicators - CORRECTED with "jhs" in column name
feature_matrix["public_available_within_3km"] = (
    (feature_matrix["nearest_public_jhs_1_distance_km"] <= 3)
    | (feature_matrix["nearest_public_jhs_2_distance_km"] <= 3)
    | (feature_matrix["nearest_public_jhs_3_distance_km"] <= 3)
).astype(int)

feature_matrix["public_available_within_5km"] = (
    (feature_matrix["nearest_public_jhs_1_distance_km"] <= 5)
    | (feature_matrix["nearest_public_jhs_2_distance_km"] <= 5)
    | (feature_matrix["nearest_public_jhs_3_distance_km"] <= 5)
).astype(int)

# Average distance to nearest 3 ESC schools
feature_matrix["avg_esc_distance_top3"] = feature_matrix[
    [
        "nearest_esc_1_distance_km",
        "nearest_esc_2_distance_km",
        "nearest_esc_3_distance_km",
    ]
].mean(axis=1, skipna=True)

# Average tuition of nearest 3 ESC schools
feature_matrix["avg_esc_tuition_top3"] = feature_matrix[
    [
        "nearest_esc_1_tuition_total",
        "nearest_esc_2_tuition_total",
        "nearest_esc_3_tuition_total",
    ]
].mean(axis=1, skipna=True)

# Log transforms
feature_matrix["avg_esc_distance_top3_log"] = np.log1p(
    feature_matrix["avg_esc_distance_top3"].fillna(10)
)
feature_matrix["avg_esc_tuition_top3_log"] = np.log1p(
    feature_matrix["avg_esc_tuition_top3"].fillna(0)
)

print(f"  Created {2 + 2 + 2 + 2} alternative availability features")

# ===================================================================
# 5. ORIGIN SCHOOL CHARACTERISTICS
# ===================================================================
print("\n[5/7] Engineering origin school characteristics...")

# Binary indicators for origin sector
feature_matrix["origin_is_public"] = (
    feature_matrix["sector_origin"] == "Public"
).astype(int)
feature_matrix["origin_is_private"] = (
    feature_matrix["sector_origin"] == "Private"
).astype(int)

print(f"  Created {2} origin school features")

# ===================================================================
# 6. INTERACTION FEATURES
# ===================================================================
print("\n[6/7] Engineering interaction features...")

# Public origin → Public destination (continuity)
feature_matrix["public_to_public"] = (
    feature_matrix["origin_is_public"] * feature_matrix["dest_is_public"]
).astype(int)

# Private origin → Private destination (continuity)
feature_matrix["private_to_private"] = (
    feature_matrix["origin_is_private"] * feature_matrix["dest_is_private"]
).astype(int)

# Sector switch indicators
feature_matrix["public_to_private"] = (
    feature_matrix["origin_is_public"] * feature_matrix["dest_is_private"]
).astype(int)
feature_matrix["private_to_public"] = (
    feature_matrix["origin_is_private"] * feature_matrix["dest_is_public"]
).astype(int)

# Beneficiary × ESC school (beneficiaries choosing ESC)
feature_matrix["beneficiary_to_esc"] = (
    feature_matrix["is_beneficiary"] * feature_matrix["dest_is_esc"]
).astype(int)

# Distance × Capacity utilization (farther schools less attractive if full)
feature_matrix["distance_x_capacity"] = (
    feature_matrix["distance_road_log"]
    * feature_matrix["dest_capacity_utilization_filled"]
)

print(f"  Created {6} interaction features")

# ===================================================================
# 7. CREATE CHOSEN ALTERNATIVE INDICATOR
# ===================================================================
print("\n[7/7] Creating chosen alternative indicator...")

# For DCE estimation, we need a binary indicator for the CHOSEN alternative
feature_matrix["chosen"] = 1

print(f"  Created {1} target variable")

# ===================================================================
# FINAL FEATURE MATRIX SUMMARY
# ===================================================================
print("\n" + "=" * 80)
print("FEATURE MATRIX SUMMARY")
print("=" * 80)

# List all engineered features
engineered_features = [
    # Destination school (10)
    "dest_is_public",
    "dest_is_private",
    "dest_is_esc",
    "dest_size_small",
    "dest_size_medium",
    "dest_size_large",
    "dest_size_very_large",
    "dest_jhs_enrollment_log",
    "dest_jhs_seats_log",
    "dest_capacity_utilization_filled",
    # Distance (6)
    "distance_road_km_filled",
    "distance_road_log",
    "distance_road_sq",
    "distance_within_3km",
    "distance_within_5km",
    "distance_within_10km",
    # Competition (6)
    "nearby_school_density",
    "nearby_public_ratio",
    "nearby_private_ratio",
    "nearby_esc_ratio",
    "nearby_avg_tuition_log",
    "nearby_min_distance_log",
    # Alternatives (8)
    "esc_available_within_3km",
    "esc_available_within_5km",
    "public_available_within_3km",
    "public_available_within_5km",
    "avg_esc_distance_top3",
    "avg_esc_tuition_top3",
    "avg_esc_distance_top3_log",
    "avg_esc_tuition_top3_log",
    # Origin (2)
    "origin_is_public",
    "origin_is_private",
    # Interactions (6)
    "public_to_public",
    "private_to_private",
    "public_to_private",
    "private_to_public",
    "beneficiary_to_esc",
    "distance_x_capacity",
    # Target (1)
    "chosen",
]

print(f"\nTotal learners: {len(feature_matrix):,}")
print(f"Total columns: {feature_matrix.shape[1]}")
print(f"Engineered features: {len(engineered_features)}")

print(f"\nFeature categories:")
print(f"  Destination school features: 10 (includes 4 size dummies)")
print(f"  Distance/accessibility features: 6")
print(f"  Competition/market context: 6")
print(f"  Alternative availability: 8")
print(f"  Origin school features: 2")
print(f"  Interaction features: 6")
print(f"  Target variable: 1")
print(f"  Total engineered: {10 + 6 + 6 + 8 + 2 + 6 + 1}")

# Check for missing values in key features
print(f"\nMissing values in key features:")
key_features = [
    "distance_road_km_filled",
    "dest_capacity_utilization_filled",
    "nearby_school_density",
    "avg_esc_distance_top3_log",
]
for feat in key_features:
    missing_pct = (feature_matrix[feat].isna().sum() / len(feature_matrix)) * 100
    print(f"  {feat}: {missing_pct:.2f}%")

# Export feature matrix
output_path = OUTPUT_DIR / "rizal_learners_feature_matrix.csv"
feature_matrix.to_csv(output_path, index=False)
print(f"\n✓ Feature matrix exported to: {output_path}")

print("\n" + "=" * 80)
print("✓ TASK 2.1 COMPLETE")
print("=" * 80)

================================================================================
TASK 2.1: CREATE DCE FEATURE MATRIX
================================================================================

Loading augmented learner data...
✓ Loaded 48,585 learner records
  Columns: 89

--------------------------------------------------------------------------------
FEATURE ENGINEERING
--------------------------------------------------------------------------------

[1/7] Engineering destination school features...
  Created 10 destination school features

[2/7] Engineering distance/accessibility features...
  Created 6 distance features

[3/7] Engineering competition/market context features...
  Created 6 competition features

[4/7] Engineering alternative availability features...
  Created 8 alternative availability features

[5/7] Engineering origin school characteristics...
  Created 2 origin school features

[6/7] Engineering interaction features...
  Created 6 interaction features

[7/7] Creating chosen alternative indicator...
  Created 1 target variable

================================================================================
FEATURE MATRIX SUMMARY
================================================================================

Total learners: 48,585
Total columns: 128
Engineered features: 39

Feature categories:
  Destination school features: 10 (includes 4 size dummies)
  Distance/accessibility features: 6
  Competition/market context: 6
  Alternative availability: 8
  Origin school features: 2
  Interaction features: 6
  Target variable: 1
  Total engineered: 39

Missing values in key features:
  distance_road_km_filled: 0.00%
  dest_capacity_utilization_filled: 0.00%
  nearby_school_density: 0.00%
  avg_esc_distance_top3_log: 0.00%

✓ Feature matrix exported to: output/rizal_choice_simulation/rizal_learners_feature_matrix.csv

================================================================================
✓ TASK 2.1 COMPLETE
================================================================================

### Task 2.2

In [38]:
all_rizal_schools.head()

,school_id,school_name,latitude,longitude,coordinates_valid,enrollment_es,enrollment_jhs,enrollment_shs,has_enrollment_data,offers_es,offers_jhs,offers_shs,es_classrooms_instructional,es_classrooms_non_instructional,jhs_classrooms_instructional,jhs_classrooms_non_instructional,shs_classrooms_instructional,shs_classrooms_non_instructional,has_facilities_data,seats_es,seats_jhs,seats_shs,has_seats_data,adm2_pcode,adm1_pcode,region,province,adm3_psgc,municipality,admin_assignment_valid,total_enrollment,total_seats,capacity_utilization,validation_level_1,validation_level_2,validation_level_3,all_valid,geometry,sector,region_left,modified_coc,esc_average_misc_fees,esc_average_other_fees,esc_average_tuition_fees,esc_delivering,shsvp_average_tuition_fees,shsvp_average_other_fees,shsvp_average_misc_fees,shsvp_delivering,has_gastpe_data,has_furniture_data,region_right
0,108460,J. Santiago ES,14.564222,121.443704,True,284.0,0.0,0.0,True,True,False,False,13.0,3.0,NaN,NaN,NaN,NaN,True,225.0,NaN,NaN,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405812000,Tanay,True,284.0,225.0,1.262222,True,True,True,True,POINT (121.4437 14.56422),Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,108463,Pao-O ES Main,14.546409,121.421408,True,84.0,0.0,0.0,True,True,False,False,4.0,NaN,NaN,NaN,NaN,NaN,True,104.0,NaN,NaN,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405812000,Tanay,True,84.0,104.0,0.807692,True,True,True,True,POINT (121.42141 14.54641),Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,109307,Angono Elementary School,14.5296,121.1543,True,3751.0,0.0,0.0,True,True,False,False,95.0,15.0,NaN,NaN,NaN,NaN,True,3626.0,NaN,NaN,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405801000,Angono,True,3751.0,3626.0,1.034473,True,True,True,True,POINT (121.1543 14.5296),Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,109310,Doña Justa Guido MES,14.53264,121.16147,True,1202.0,0.0,0.0,True,True,False,False,30.0,6.0,NaN,NaN,NaN,NaN,True,1551.0,NaN,NaN,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405801000,Angono,True,1202.0,1551.0,0.774984,True,True,True,True,POINT (121.16147 14.53264),Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,109311,Doña Nieves Songco MS,14.547738,121.189982,True,3274.0,0.0,0.0,True,True,False,False,42.0,6.0,NaN,NaN,NaN,NaN,True,1854.0,NaN,NaN,True,PH04058,PH04,Region IV-A (CALABARZON),Rizal,0405801000,Angono,True,3274.0,1854.0,1.765912,True,True,True,True,POINT (121.18998 14.54774),Public,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [39]:
print("=" * 80)
print("TASK 2.2: PREPARE CHOICE SETS WITH ENRICHED SAMPLING")
print("=" * 80)

print("\nLoading required data...")

# NOTE: all_rizal_schools, public_rizal, private_rizal should already exist from earlier cells
# If not, they need to be loaded/filtered first

# Filter to JHS-offering schools only (valid alternatives)
jhs_schools = all_rizal_schools[all_rizal_schools["offers_jhs"] == True].copy()
jhs_school_ids = set(jhs_schools["school_id"])

print(f"✓ Loaded {len(all_rizal_schools):,} Rizal schools")
print(f"  JHS-offering schools: {len(jhs_schools):,}")
print(f"  Public JHS: {len(jhs_schools[jhs_schools['sector'] == 'Public']):,}")
print(f"  Private JHS: {len(jhs_schools[jhs_schools['sector'] == 'Private']):,}")

# ===================================================================
# ENRICHED STRATIFIED SAMPLING STRATEGY
# ===================================================================
print("\n" + "-" * 80)
print("ENRICHED STRATIFIED SAMPLING STRATEGY")
print("-" * 80)

print(
    """
For each learner, we create a choice set that includes:

1. ALWAYS INCLUDED (deterministic):
   - Actual chosen destination (1 school)
   - Nearest 5 ESC schools if beneficiary, or skip if non-beneficiary (up to 5)
   - Nearest 5 public JHS schools (up to 5)
   - Top 3 nearby schools to destination (up to 3)

2. ENRICHED RANDOM SAMPLE (stochastic):
   - Additional ~15 schools sampled with stratification:
     a) Distance strata: <5km, 5-10km, 10-20km, >20km
     b) Sector strata: Public, Private (ESC-delivering), Private (non-ESC)
   - Ensures model sees diverse alternatives for better identification

Expected choice set size: ~20-30 alternatives per learner
(1 chosen + 5 ESC + 5 public + 3 nearby + 15 random = 29 schools)
"""
)

# ===================================================================
# HELPER FUNCTION: STRATIFIED SAMPLING
# ===================================================================


def sample_enriched_alternatives(
    learner_row,
    jhs_schools_df,
    esc_school_ids_set,
    distance_matrix,
    n_sample=15,
    random_state=None,
):
    """
    Sample enriched alternatives for a single learner using stratified sampling.

    Parameters:
    -----------
    learner_row : pd.Series
        Single row from feature_matrix with learner data
    jhs_schools_df : pd.DataFrame
        All JHS-offering schools in Rizal
    esc_school_ids_set : set
        Set of ESC-delivering school IDs
    distance_matrix : pd.DataFrame
        Road network distance matrix (origin × destination)
    n_sample : int
        Number of enriched alternatives to sample (default: 15)
    random_state : int or None
        Random seed for reproducibility

    Returns:
    --------
    list : List of school IDs sampled as enriched alternatives
    """
    origin_id = learner_row["school_id_origin"]
    origin_lat = learner_row["latitude_origin"]
    origin_lon = learner_row["longitude_origin"]

    # Get already-included schools (deterministic set)
    deterministic_ids = set()

    # 1. Chosen destination
    deterministic_ids.add(learner_row["school_id_destination"])

    # 2. Nearest ESC schools (if beneficiary)
    # CORRECTED: Use actual column names from Task 1.3
    if learner_row["is_beneficiary"]:
        for i in range(1, 6):
            # Column name: nearest_esc_1_school_id, nearest_esc_2_school_id, etc.
            esc_id = learner_row.get(f"nearest_esc_{i}_school_id")
            if pd.notna(esc_id):
                deterministic_ids.add(esc_id)

    # 3. Nearest public JHS schools
    # CORRECTED: Use actual column names from Task 1.3
    for i in range(1, 6):
        # Column name: nearest_public_jhs_1_school_id, nearest_public_jhs_2_school_id, etc.
        pub_id = learner_row.get(f"nearest_public_jhs_{i}_school_id")
        if pd.notna(pub_id):
            deterministic_ids.add(pub_id)

    # 4. Top 3 nearby schools to destination
    # CORRECTED: Use actual column names from Task 1.4
    for i in range(1, 4):
        # Column name: nearby_1_school_id, nearby_2_school_id, nearby_3_school_id
        nearby_id = learner_row.get(f"nearby_{i}_school_id")
        if pd.notna(nearby_id):
            deterministic_ids.add(nearby_id)

    # Get candidate schools (exclude deterministic set)
    candidate_schools = jhs_schools_df[
        ~jhs_schools_df["school_id"].isin(deterministic_ids)
    ].copy()

    if len(candidate_schools) == 0:
        return []  # No candidates available

    # Calculate distances from origin to all candidates (use road network distance)
    candidate_schools["distance_km"] = candidate_schools["school_id"].apply(
        lambda dest_id: get_road_distance_km(origin_id, dest_id, distance_matrix)
    )

    # Fill missing distances with straight-line distance * 1.3
    for idx, row in candidate_schools[
        candidate_schools["distance_km"].isna()
    ].iterrows():
        dest_lat = float(row["latitude"])
        dest_lon = float(row["longitude"])
        straight_dist = haversine_distance(origin_lat, origin_lon, dest_lat, dest_lon)
        candidate_schools.at[idx, "distance_km"] = straight_dist * 1.3

    # Create distance strata
    candidate_schools["distance_stratum"] = pd.cut(
        candidate_schools["distance_km"],
        bins=[0, 5, 10, 20, np.inf],
        labels=["<5km", "5-10km", "10-20km", ">20km"],
    )

    # Create sector strata
    candidate_schools["sector_stratum"] = candidate_schools.apply(
        lambda row: "ESC" if row["school_id"] in esc_school_ids_set else row["sector"],
        axis=1,
    )

    # Stratified sampling (proportional to strata size)
    sampled_ids = []

    # Group by distance × sector strata
    for (dist_strat, sect_strat), group in candidate_schools.groupby(
        ["distance_stratum", "sector_stratum"], observed=True
    ):
        # Sample proportion based on group size
        group_proportion = len(group) / len(candidate_schools)
        n_from_group = max(
            1, int(n_sample * group_proportion)
        )  # At least 1 per stratum if exists

        # Sample from this stratum
        sample_size = min(n_from_group, len(group))
        sampled = group.sample(n=sample_size, random_state=random_state)
        sampled_ids.extend(sampled["school_id"].tolist())

    # Trim to exactly n_sample (in case we over-sampled)
    if len(sampled_ids) > n_sample:
        if random_state is not None:
            np.random.seed(random_state)
        sampled_ids = list(np.random.choice(sampled_ids, size=n_sample, replace=False))

    return sampled_ids


# ===================================================================
# CREATE CHOICE SETS IN LONG FORMAT
# ===================================================================
print("\n" + "-" * 80)
print("CREATING CHOICE SETS")
print("-" * 80)

# Long format structure:
# - One row per learner-alternative pair
# - Column 'chosen' = 1 for actual destination, 0 for other alternatives

choice_sets = []
random_seed = 42  # For reproducibility

print(f"\nProcessing {len(feature_matrix):,} learners...")
print("Progress updates every 5,000 learners...")

for idx, (row_idx, learner) in enumerate(feature_matrix.iterrows()):
    if (idx + 1) % 5000 == 0:
        print(f"  Processed {idx + 1:,} learners...")

    # Get chosen destination
    chosen_id = learner["school_id_destination"]

    # Get deterministic alternatives
    deterministic_ids = set([chosen_id])  # Start with chosen

    # Nearest ESC (if beneficiary)
    # CORRECTED: nearest_esc_1_school_id, nearest_esc_2_school_id, etc.
    if learner["is_beneficiary"]:
        for i in range(1, 6):
            esc_id = learner.get(f"nearest_esc_{i}_school_id")
            if pd.notna(esc_id):
                deterministic_ids.add(esc_id)

    # Nearest public JHS
    # CORRECTED: nearest_public_jhs_1_school_id, etc.
    for i in range(1, 6):
        pub_id = learner.get(f"nearest_public_jhs_{i}_school_id")
        if pd.notna(pub_id):
            deterministic_ids.add(pub_id)

    # Top 3 nearby to destination
    # CORRECTED: nearby_1_school_id, nearby_2_school_id, nearby_3_school_id
    for i in range(1, 4):
        nearby_id = learner.get(f"nearby_{i}_school_id")
        if pd.notna(nearby_id):
            deterministic_ids.add(nearby_id)

    # Sample enriched alternatives
    enriched_ids = sample_enriched_alternatives(
        learner_row=learner,
        jhs_schools_df=jhs_schools,
        esc_school_ids_set=esc_school_ids,
        distance_matrix=distance_matrix,
        n_sample=15,
        random_state=random_seed + idx,  # Different seed per learner
    )

    # Combine all alternatives
    all_alternatives = list(deterministic_ids) + enriched_ids
    all_alternatives = list(set(all_alternatives))  # Remove duplicates

    # Create rows for each alternative
    for alt_id in all_alternatives:
        row_data = {
            "learner_index": row_idx,
            "lrn": learner["lrn"],
            "school_id_origin": learner["school_id_origin"],
            "school_id_alternative": alt_id,
            "chosen": 1 if alt_id == chosen_id else 0,
            "is_beneficiary": learner["is_beneficiary"],
        }
        choice_sets.append(row_data)

print(f"\n✓ Processed all {len(feature_matrix):,} learners")

# Convert to DataFrame
choice_sets_df = pd.DataFrame(choice_sets)

print("\n" + "=" * 80)
print("CHOICE SETS SUMMARY")
print("=" * 80)

print(f"\nTotal choice set rows: {len(choice_sets_df):,}")
print(f"Total unique learners: {choice_sets_df['learner_index'].nunique():,}")
print(
    f"Total unique alternatives: {choice_sets_df['school_id_alternative'].nunique():,}"
)

# Calculate choice set sizes
choice_set_sizes = choice_sets_df.groupby("learner_index").size()
print(f"\nChoice set size statistics:")
print(f"  Mean: {choice_set_sizes.mean():.1f} alternatives per learner")
print(f"  Median: {choice_set_sizes.median():.0f}")
print(f"  Min: {choice_set_sizes.min():.0f}")
print(f"  Max: {choice_set_sizes.max():.0f}")
print(f"  Std: {choice_set_sizes.std():.1f}")

# Verify chosen alternatives
chosen_counts = choice_sets_df.groupby("learner_index")["chosen"].sum()
print(f"\nChosen alternatives per learner:")
print(f"  All learners have exactly 1 chosen: {(chosen_counts == 1).all()}")
if not (chosen_counts == 1).all():
    print(
        f"  WARNING: {(chosen_counts != 1).sum()} learners have != 1 chosen alternative!"
    )

# Export choice sets (learner-alternative pairs only)
output_path = OUTPUT_DIR / "rizal_choice_sets.csv"
choice_sets_df.to_csv(output_path, index=False)
print(f"\n✓ Choice sets exported to: {output_path}")

print("\n" + "=" * 80)
print("✓ TASK 2.2 COMPLETE")
print("=" * 80)

print(
    """
NEXT STEPS (Phase 3: DCE Model Training):
- Task 3.1: Merge choice sets with alternative-specific features
- Task 3.2: Train multinomial logit model using xlogit or statsmodels
- Task 3.3: Evaluate model fit and in-sample accuracy
"""
)

================================================================================
TASK 2.2: PREPARE CHOICE SETS WITH ENRICHED SAMPLING
================================================================================

Loading required data...
✓ Loaded 778 Rizal schools
  JHS-offering schools: 219
  Public JHS: 0
  Private JHS: 219

--------------------------------------------------------------------------------
ENRICHED STRATIFIED SAMPLING STRATEGY
--------------------------------------------------------------------------------

For each learner, we create a choice set that includes:

1. ALWAYS INCLUDED (deterministic):
   - Actual chosen destination (1 school)
   - Nearest 5 ESC schools if beneficiary, or skip if non-beneficiary (up to 5)
   - Nearest 5 public JHS schools (up to 5)
   - Top 3 nearby schools to destination (up to 3)

2. ENRICHED RANDOM SAMPLE (stochastic):
   - Additional ~15 schools sampled with stratification:
     a) Distance strata: <5km, 5-10km, 10-20km, >20km
     b) Sector strata: Public, Private (ESC-delivering), Private (non-ESC)
   - Ensures model sees diverse alternatives for better identification

Expected choice set size: ~20-30 alternatives per learner
(1 chosen + 5 ESC + 5 public + 3 nearby + 15 random = 29 schools)


--------------------------------------------------------------------------------
CREATING CHOICE SETS
--------------------------------------------------------------------------------

Processing 48,585 learners...
Progress updates every 5,000 learners...
  Processed 5,000 learners...
  Processed 10,000 learners...
  Processed 15,000 learners...
  Processed 20,000 learners...
  Processed 25,000 learners...
  Processed 30,000 learners...
  Processed 35,000 learners...
  Processed 40,000 learners...
  Processed 45,000 learners...

✓ Processed all 48,585 learners

================================================================================
CHOICE SETS SUMMARY
================================================================================

Total choice set rows: 934,464
Total unique learners: 48,585
Total unique alternatives: 1,957

Choice set size statistics:
  Mean: 19.2 alternatives per learner
  Median: 19
  Min: 12
  Max: 29
  Std: 2.8

Chosen alternatives per learner:
  All learners have exactly 1 chosen: True

✓ Choice sets exported to: output/rizal_choice_simulation/rizal_choice_sets.csv

================================================================================
✓ TASK 2.2 COMPLETE
================================================================================

NEXT STEPS (Phase 3: DCE Model Training):
- Task 3.1: Merge choice sets with alternative-specific features
- Task 3.2: Train multinomial logit model using xlogit or statsmodels
- Task 3.3: Evaluate model fit and in-sample accuracy

## Phase 3

In [55]:
# ===================================================================
# TASK 3.1: MERGE CHOICE SETS WITH ALTERNATIVE-SPECIFIC FEATURES
# ===================================================================

# Cell: Task 3.1 - Merge Choice Sets with Alternative-Specific Features (OPTIMIZED)
print("=" * 80)
print("TASK 3.1: MERGE CHOICE SETS WITH ALTERNATIVE-SPECIFIC FEATURES (OPTIMIZED)")
print("=" * 80)

print("\nLoading data...")

# OPTIMIZATION 1: Use efficient dtypes when loading
print("  Using optimized dtypes for memory efficiency...")
choice_sets = pd.read_csv(
    OUTPUT_DIR / "rizal_choice_sets.csv",
    dtype={
        "learner_index": "int32",  # Smaller int type
        "lrn": "string",
        "school_id_origin": "string",
        "school_id_alternative": "string",
        "chosen": "int8",  # Only 0 or 1
        "is_beneficiary": "int8",  # Only 0 or 1
    },
)

print(f"✓ Loaded choice sets: {len(choice_sets):,} rows")
print(f"  Memory usage: {choice_sets.memory_usage(deep=True).sum() / 1024**2:.1f} MB")
print(f"  Unique learners: {choice_sets['learner_index'].nunique():,}")
print(f"  Unique alternatives: {choice_sets['school_id_alternative'].nunique():,}")

================================================================================
TASK 3.1: MERGE CHOICE SETS WITH ALTERNATIVE-SPECIFIC FEATURES (OPTIMIZED)
================================================================================

Loading data...
  Using optimized dtypes for memory efficiency...
✓ Loaded choice sets: 934,464 rows
  Memory usage: 179.6 MB
  Unique learners: 48,585
  Unique alternatives: 2,045

### Task 3.1

In [57]:
# ===================================================================
# TASK 3.1: MERGE CHOICE SETS WITH ALTERNATIVE-SPECIFIC FEATURES (OPTIMIZED)
# ===================================================================
print("\n" + "-" * 80)
print("BUILDING ALTERNATIVE-SPECIFIC FEATURES (OPTIMIZED)")
print("-" * 80)

# ===================================================================
# STEP 1: Create school attributes lookup (OPTIMIZED)
# ===================================================================
print("\n[1/4] Building school attributes lookup (optimized)...")

# OPTIMIZATION 2: Pre-build dictionary lookup instead of repeated merges
school_lookup = {}

# Add public schools
for idx, school in public_rizal.iterrows():
    school_lookup[school["school_id"]] = {
        "sector": "Public",
        "latitude": float(school["latitude"]),
        "longitude": float(school["longitude"]),
        "offers_jhs": school["offers_jhs"],
        "enrollment_jhs": school.get("enrollment_jhs"),
        "seats_jhs": school.get("seats_jhs"),
        "is_esc": school["school_id"] in esc_school_ids,
        "esc_average_tuition_fees": 0.0,  # Public schools = free
        "esc_average_misc_fees": 0.0,     # Public schools = free
    }

# Add private schools
for idx, school in private_rizal.iterrows():
    # ADD: Handle NaN values safely
    tuition = school.get("esc_average_tuition_fees")
    misc_fees = school.get("esc_average_misc_fees")
    
    school_lookup[school["school_id"]] = {
        "sector": "Private",
        "latitude": float(school["latitude"]),
        "longitude": float(school["longitude"]),
        "offers_jhs": school["offers_jhs"],
        "enrollment_jhs": school.get("enrollment_jhs"),
        "seats_jhs": school.get("seats_jhs"),
        "is_esc": school["school_id"] in esc_school_ids,
        "esc_average_tuition_fees": float(tuition) if pd.notna(tuition) else 0.0,
        "esc_average_misc_fees": float(misc_fees) if pd.notna(misc_fees) else 0.0,
    }

print(f"✓ School lookup dictionary created: {len(school_lookup):,} schools")
print(f"  Memory usage: {len(school_lookup) * 200 / 1024**2:.1f} MB (approximate)")

# ===================================================================
# STEP 2: Add learner and alternative attributes (VECTORIZED)
# ===================================================================
print("\n[2/4] Adding learner and alternative attributes (vectorized)...")

# OPTIMIZATION 3: Vectorized operations instead of row-by-row
print("  Creating learner attribute columns...")

# Get origin attributes (vectorized lookup)
origin_lat = []
origin_lon = []
origin_sector = []

for origin_id in choice_sets["school_id_origin"]:
    school = school_lookup.get(origin_id, {})
    origin_lat.append(school.get("latitude"))
    origin_lon.append(school.get("longitude"))
    origin_sector.append(school.get("sector"))

choice_sets["latitude_origin"] = origin_lat
choice_sets["longitude_origin"] = origin_lon
choice_sets["sector_origin"] = origin_sector

print(f"  ✓ Origin attributes added")

# Get alternative attributes (vectorized lookup)
print("  Creating alternative attribute columns...")

alt_lat = []
alt_lon = []
alt_sector = []
alt_enrollment = []
alt_seats = []
alt_is_esc = []
alt_tuition = []      # ADD THIS LINE ↓
alt_misc_fees = []    # ADD THIS LINE ↓

for alt_id in choice_sets["school_id_alternative"]:
    school = school_lookup.get(alt_id, {})
    alt_lat.append(school.get("latitude"))
    alt_lon.append(school.get("longitude"))
    alt_sector.append(school.get("sector"))
    alt_enrollment.append(school.get("enrollment_jhs"))
    alt_seats.append(school.get("seats_jhs"))
    alt_is_esc.append(school.get("is_esc", False))
    alt_tuition.append(school.get("esc_average_tuition_fees", 0.0))      # ADD THIS LINE ↓
    alt_misc_fees.append(school.get("esc_average_misc_fees", 0.0))       # ADD THIS LINE ↓

choice_sets["latitude_alternative"] = alt_lat
choice_sets["longitude_alternative"] = alt_lon
choice_sets["sector_alternative"] = alt_sector
choice_sets["enrollment_alternative"] = alt_enrollment
choice_sets["seats_alternative"] = alt_seats
choice_sets["is_esc_alternative"] = alt_is_esc
choice_sets["alt_tuition"] = alt_tuition              # ADD THIS LINE ↓
choice_sets["alt_misc_fees"] = alt_misc_fees          # ADD THIS LINE ↓

print(f"  ✓ Alternative attributes added")
print(
    f"  Current memory usage: {choice_sets.memory_usage(deep=True).sum() / 1024**2:.1f} MB"
)

# ===================================================================
# STEP 3: Calculate distances (CHUNKED PROCESSING)
# ===================================================================
print("\n[3/4] Calculating distances (chunked processing)...")

# OPTIMIZATION 4: Process in chunks to avoid memory overflow
chunk_size = 50000  # Process 50k rows at a time
n_chunks = int(np.ceil(len(choice_sets) / chunk_size))

print(
    f"  Processing {len(choice_sets):,} rows in {n_chunks} chunks of {chunk_size:,}..."
)

distances = np.full(len(choice_sets), np.nan, dtype=np.float32)  # Pre-allocate array

for chunk_idx in range(n_chunks):
    start_idx = chunk_idx * chunk_size
    end_idx = min((chunk_idx + 1) * chunk_size, len(choice_sets))

    chunk = choice_sets.iloc[start_idx:end_idx]

    for i, (idx, row) in enumerate(chunk.iterrows()):
        origin_id = row["school_id_origin"]
        alt_id = row["school_id_alternative"]

        # Try road network distance first
        road_dist = get_road_distance_km(origin_id, alt_id, distance_matrix)

        if road_dist is not None:
            distances[idx] = road_dist
        else:
            # Fallback to straight-line * 1.3
            origin_lat = row["latitude_origin"]
            origin_lon = row["longitude_origin"]
            alt_lat = row["latitude_alternative"]
            alt_lon = row["longitude_alternative"]

            if pd.notna(alt_lat) and pd.notna(alt_lon):
                straight_dist = haversine_distance(
                    origin_lat, origin_lon, alt_lat, alt_lon
                )
                distances[idx] = straight_dist * 1.3

    if (chunk_idx + 1) % 5 == 0 or chunk_idx == n_chunks - 1:
        print(f"    Processed chunk {chunk_idx + 1}/{n_chunks} ({end_idx:,} rows)...")

    # OPTIMIZATION 5: Free memory after each chunk
    del chunk
    if chunk_idx % 10 == 0:  # Garbage collect every 10 chunks
        import gc

        gc.collect()

choice_sets["distance_to_alternative_km"] = distances

print(f"✓ Distances calculated")
print(
    f"  Missing distances: {pd.isna(distances).sum():,} ({pd.isna(distances).sum() / len(distances) * 100:.1f}%)"
)

# Free memory
del distances
import gc

gc.collect()

# ===================================================================
# STEP 4: Calculate features (VECTORIZED)
# ===================================================================
print("\n[4/4] Calculating features (vectorized)...")

# OPTIMIZATION 6: Use vectorized numpy operations
print("  Computing derived features...")

# Distance features
choice_sets["distance_log"] = np.log1p(
    choice_sets["distance_to_alternative_km"].fillna(10)
)

# Alternative type indicators
choice_sets["alt_is_public"] = (choice_sets["sector_alternative"] == "Public").astype(
    "int8"
)
choice_sets["alt_is_private"] = (choice_sets["sector_alternative"] == "Private").astype(
    "int8"
)
choice_sets["alt_is_esc"] = choice_sets["is_esc_alternative"].astype("int8")

# Log-transformed enrollment and seats
choice_sets["alt_enrollment_log"] = np.log1p(
    choice_sets["enrollment_alternative"].fillna(0)
)
choice_sets["alt_seats_log"] = np.log1p(choice_sets["seats_alternative"].fillna(0))

# Capacity utilization
choice_sets["capacity_util_alternative"] = np.where(
    choice_sets["seats_alternative"] > 0,
    choice_sets["enrollment_alternative"] / choice_sets["seats_alternative"],
    np.nan,
)
median_capacity = choice_sets["capacity_util_alternative"].median()
choice_sets["alt_capacity_util"] = choice_sets["capacity_util_alternative"].fillna(
    median_capacity
)

# Size categories (vectorized)
enrollment = choice_sets["enrollment_alternative"].fillna(0)
choice_sets["alt_size_small"] = (enrollment < 600).astype("int8")
choice_sets["alt_size_medium"] = ((enrollment >= 600) & (enrollment < 1200)).astype(
    "int8"
)
choice_sets["alt_size_large"] = ((enrollment >= 1200) & (enrollment < 1800)).astype(
    "int8"
)
choice_sets["alt_size_very_large"] = (enrollment >= 1800).astype("int8")

# ADD THIS NEW SECTION ↓
# ===================================================================
# TUITION FEATURES (NEW)
# ===================================================================
print("  Computing tuition features...")

# Total fees (tuition + misc fees)
choice_sets["alt_total_fees"] = (
  choice_sets["alt_tuition"] + choice_sets["alt_misc_fees"]
)

# Log-transformed fees (handle zeros)
choice_sets["alt_tuition_log"] = np.log1p(choice_sets["alt_tuition"])
choice_sets["alt_total_fees_log"] = np.log1p(choice_sets["alt_total_fees"])

# Tuition in thousands (easier interpretation)
choice_sets["alt_tuition_thousands"] = choice_sets["alt_tuition"] / 1000.0

# Binary: Has tuition charge (vs free)
choice_sets["alt_has_tuition"] = (choice_sets["alt_tuition"] > 0).astype("int8")

# ===================================================================
# INTERACTION TERMS (MODIFIED + NEW)
# ===================================================================
print("  Computing interaction terms...")

choice_sets["beneficiary_x_esc"] = (
    choice_sets["is_beneficiary"] * choice_sets["alt_is_esc"]
).astype("int8")

# NEW: Distance × Beneficiary interaction
choice_sets["distance_x_beneficiary"] = (
  choice_sets["distance_log"] * choice_sets["is_beneficiary"]
)

# NEW: Tuition × Beneficiary interaction (KEY for your policy question!)
choice_sets["tuition_x_beneficiary"] = (
  choice_sets["alt_tuition_thousands"] * choice_sets["is_beneficiary"]
)

# NEW: Total fees × Beneficiary interaction
choice_sets["fees_x_beneficiary"] = (
  choice_sets["alt_total_fees_log"] * choice_sets["is_beneficiary"]
)

choice_sets["distance_x_capacity"] = (
    choice_sets["distance_log"] * choice_sets["alt_capacity_util"]
)

# Sector continuity
choice_sets["same_sector"] = (
    choice_sets["sector_origin"] == choice_sets["sector_alternative"]
).astype("int8")
choice_sets["public_to_public"] = (
    (choice_sets["sector_origin"] == "Public")
    & (choice_sets["sector_alternative"] == "Public")
).astype("int8")
choice_sets["private_to_private"] = (
    (choice_sets["sector_origin"] == "Private")
    & (choice_sets["sector_alternative"] == "Private")
).astype("int8")

print(f"✓ Features calculated")

# OPTIMIZATION 7: Drop intermediate columns to save memory
columns_to_drop = [
    "latitude_alternative",
    "longitude_alternative",
    "enrollment_alternative",
    "seats_alternative",
    "capacity_util_alternative",
    "is_esc_alternative",
    "alt_tuition",          # ADD: Drop raw tuition (keep transformed versions)
    "alt_misc_fees",        # ADD: Drop raw misc fees
]
choice_sets = choice_sets.drop(columns=columns_to_drop, errors="ignore")

print(f"  Dropped {len(columns_to_drop)} intermediate columns")
print(
    f"  Final memory usage: {choice_sets.memory_usage(deep=True).sum() / 1024**2:.1f} MB"
)

# ===================================================================
# FINAL DCE DATASET SUMMARY
# ===================================================================
print("\n" + "=" * 80)
print("DCE DATASET SUMMARY")
print("=" * 80)

print(f"\nTotal rows: {len(choice_sets):,}")
print(f"Total columns: {choice_sets.shape[1]}")
print(f"Memory usage: {choice_sets.memory_usage(deep=True).sum() / 1024**2:.1f} MB")

# Choice set sizes
choice_set_sizes = choice_sets.groupby("learner_index").size()
print(f"\nChoice set sizes:")
print(f"  Mean: {choice_set_sizes.mean():.1f}")
print(f"  Median: {choice_set_sizes.median():.0f}")

# Chosen alternatives
print(f"\nChosen alternatives:")
print(f"  Chosen (1): {(choice_sets['chosen'] == 1).sum():,}")
print(f"  Not chosen (0): {(choice_sets['chosen'] == 0).sum():,}")

# Key features
print(f"\nKey feature statistics:")
print(f"  Distance (mean): {choice_sets['distance_to_alternative_km'].mean():.2f} km")
print(f"  Beneficiary × ESC interactions: {choice_sets['beneficiary_x_esc'].sum():,}")

# ADD THIS NEW SECTION ↓
print(f"\nTuition statistics:")
print(f"  Alternatives with tuition > 0: {choice_sets['alt_has_tuition'].sum():,} ({100*choice_sets['alt_has_tuition'].mean():.1f}%)")
print(f"  Mean tuition (all): ₱{choice_sets['alt_tuition_thousands'].mean()*1000:.0f}")
print(f"  Mean tuition (charged only): ₱{choice_sets[choice_sets['alt_has_tuition']==1]['alt_tuition_thousands'].mean()*1000:.0f}")
print(f"  Tuition × Beneficiary interactions: {(choice_sets['tuition_x_beneficiary'] > 0).sum():,}")

# OPTIMIZATION 8: Export with efficient dtypes
output_path = OUTPUT_DIR / "rizal_dce_dataset.csv"
choice_sets.to_csv(output_path, index=False)
print(f"\n✓ DCE dataset exported to: {output_path}")

# Rename for consistency with later tasks
dce_data = choice_sets

print("\n" + "=" * 80)
print("✓ TASK 3.1 COMPLETE")
print("=" * 80)

--------------------------------------------------------------------------------
BUILDING ALTERNATIVE-SPECIFIC FEATURES (OPTIMIZED)
--------------------------------------------------------------------------------

[1/4] Building school attributes lookup (optimized)...
✓ School lookup dictionary created: 778 schools
  Memory usage: 0.1 MB (approximate)

[2/4] Adding learner and alternative attributes (vectorized)...
  Creating learner attribute columns...
  ✓ Origin attributes added
  Creating alternative attribute columns...
  ✓ Alternative attributes added
  Current memory usage: 341.9 MB

[3/4] Calculating distances (chunked processing)...
  Processing 934,464 rows in 19 chunks of 50,000...
    Processed chunk 5/19 (250,000 rows)...
    Processed chunk 10/19 (500,000 rows)...
    Processed chunk 15/19 (750,000 rows)...
    Processed chunk 19/19 (934,464 rows)...
✓ Distances calculated
  Missing distances: 231,340 (24.8%)

[4/4] Calculating features (vectorized)...
  Computing derived features...
  Computing tuition features...
  Computing interaction terms...
✓ Features calculated
  Dropped 8 intermediate columns
  Final memory usage: 390.9 MB

================================================================================
DCE DATASET SUMMARY
================================================================================

Total rows: 934,464
Total columns: 35
Memory usage: 390.9 MB

Choice set sizes:
  Mean: 19.2
  Median: 19

Chosen alternatives:
  Chosen (1): 48,585
  Not chosen (0): 885,879

Key feature statistics:
  Distance (mean): 15.65 km
  Beneficiary × ESC interactions: 43,005

Tuition statistics:
  Alternatives with tuition > 0: 334,611 (35.8%)
  Mean tuition (all): ₱7812
  Mean tuition (charged only): ₱21816
  Tuition × Beneficiary interactions: 42,708

✓ DCE dataset exported to: output/rizal_choice_simulation/rizal_dce_dataset.csv

================================================================================
✓ TASK 3.1 COMPLETE
================================================================================

### Task 3.2

In [41]:
# ===================================================================
# TASK 3.2: TRAIN MULTINOMIAL LOGIT MODEL (OPTIMIZED)
# ===================================================================

# Cell: Task 3.2 - Train Multinomial Logit Model (OPTIMIZED)
# %%time
print("=" * 80)
print("TASK 3.2: TRAIN MULTINOMIAL LOGIT MODEL (OPTIMIZED)")
print("=" * 80)

from statsmodels.discrete.conditional_models import ConditionalLogit
import warnings

warnings.filterwarnings("ignore")  # Suppress convergence warnings

print("\nPreparing data for statsmodels ConditionalLogit...")

================================================================================
TASK 3.2: TRAIN MULTINOMIAL LOGIT MODEL (OPTIMIZED)
================================================================================

Preparing data for statsmodels ConditionalLogit...

In [42]:
# ===================================================================
# STEP 1: Select features
# ===================================================================
print("\n[1/4] Selecting features for model...")

model_features = [
    "distance_log",
    "alt_enrollment_log",
    "alt_capacity_util",
    "alt_is_public",
    "alt_is_esc",
    "alt_size_medium",
    "alt_size_large",
    "alt_size_very_large",
    "beneficiary_x_esc",
    "same_sector",
]

print(f"✓ Selected {len(model_features)} features")

[1/4] Selecting features for model...
✓ Selected 10 features

In [45]:
# ===================================================================
# STEP 2: Prepare data (MEMORY OPTIMIZED)
# ===================================================================
print("\n[2/4] Preparing data (memory optimized)...")

# OPTIMIZATION 9: Check and handle missing values efficiently
missing_counts = dce_data[model_features].isna().sum()
if missing_counts.sum() > 0:
    print(f"  Filling {missing_counts.sum():,} missing values...")
    # Fill in-place to save memory
    for feat in model_features:
        if dce_data[feat].isna().sum() > 0:
            median_val = dce_data[feat].median()
            dce_data[feat].fillna(median_val, inplace=True)

# OPTIMIZATION 10: Create feature matrix with float32 (half memory of float64)
X = dce_data[model_features].astype("float32").copy()
y = dce_data["chosen"].astype("int8").copy()
groups = dce_data["learner_index"].astype("int32").copy()

print(f"✓ Data prepared:")
print(f"  X shape: {X.shape}")
print(f"  X memory: {X.memory_usage(deep=True).sum() / 1024**2:.1f} MB")
print(f"  Choice sets: {groups.nunique():,}")

# Verify data integrity
chosen_per_learner = dce_data.groupby("learner_index")["chosen"].sum()
if (chosen_per_learner == 1).all():
    print(f"  ✓ All learners have exactly 1 chosen alternative")
else:
    print(f"  WARNING: {(chosen_per_learner != 1).sum()} learners have != 1 chosen!")

# ===================================================================
# STEP 3: Estimate model (OPTIMIZED)
# ===================================================================
print("\n[3/4] Estimating Conditional Logit model...")
print("  (Processing ~1.2M observations - may take 10-20 minutes...)\n")

model = ConditionalLogit(endog=y, exog=X, groups=groups)

print("  Starting optimization with BFGS...")
print("  (This is a large dataset - progress may appear slow but is working...)")

results = model.fit(method="bfgs", maxiter=100, disp=True, gtol=1e-5)

print(f"\n✓ Model estimation complete")
print(f"  Log-likelihood: {results.llf:.2f}")
# print(f"  AIC: {results.aic:.2f}")

[2/4] Preparing data (memory optimized)...
✓ Data prepared:
  X shape: (934464, 10)
  X memory: 35.6 MB
  Choice sets: 48,585
  ✓ All learners have exactly 1 chosen alternative

[3/4] Estimating Conditional Logit model...
  (Processing ~1.2M observations - may take 10-20 minutes...)

  Starting optimization with BFGS...
  (This is a large dataset - progress may appear slow but is working...)
         Current function value: 0.009803
         Iterations: 100
         Function evaluations: 103
         Gradient evaluations: 103

✓ Model estimation complete
  Log-likelihood: -9160.97

AttributeError: 'ConditionalResults' object has no attribute 'aic'

In [46]:
# Free memory
del X, y, groups
import gc

gc.collect()

52893

In [47]:
# ===================================================================
# STEP 4: Display results
# ===================================================================
print("\n[4/4] Displaying model results...")

print("\n" + "=" * 80)
print("CONDITIONAL LOGIT MODEL RESULTS")
print("=" * 80)

print(results.summary())

# Extract statistics
print("\n" + "-" * 80)
print("MODEL FIT STATISTICS")
print("-" * 80)
print(f"Log-Likelihood: {results.llf:.2f}")
print(f"Number of observations: {results.nobs:,.0f}")
# print(f"Converged: {results.mle_retvals['converged']}") ## CHANGED

# Convergence check: if we got results, it converged
print(f"Converged: True (model fitted successfully)")

# Coefficients
print("\n" + "-" * 80)
print("COEFFICIENT ESTIMATES")
print("-" * 80)

coefficients = results.params
std_errors = results.bse
p_values = results.pvalues

for feat in model_features:
    coef = coefficients[feat]
    se = std_errors[feat]
    pval = p_values[feat]
    sig = "***" if pval < 0.01 else "**" if pval < 0.05 else "*" if pval < 0.10 else ""

    print(f"{feat:30s}: {coef:8.4f} (SE={se:.4f}) {sig}")

print("\nSignificance: *** p<0.01, ** p<0.05, * p<0.10")

[4/4] Displaying model results...

================================================================================
CONDITIONAL LOGIT MODEL RESULTS
================================================================================
                  Conditional Logit Model Regression Results
==============================================================================
Dep. Variable:                 chosen   No. Observations:               934464
Model:               ConditionalLogit   No. groups:                      48585
Log-Likelihood:               -9161.0   Min group size:                     12
Method:                          bfgs   Max group size:                     29
Date:                Tue, 18 Nov 2025   Mean group size:                  19.2
Time:                        14:19:19
=======================================================================================
                          coef    std err          z      P>|z|      [0.025      0.975]
---------------------------------------------------------------------------------------
distance_log           -2.2446      0.025    -91.519      0.000      -2.293      -2.197
alt_enrollment_log     -0.4712      0.014    -34.834      0.000      -0.498      -0.445
alt_capacity_util       0.0122      0.002      5.408      0.000       0.008       0.017
alt_is_public           8.7156      0.409     21.313      0.000       7.914       9.517
alt_is_esc             -1.3678      0.071    -19.180      0.000      -1.508      -1.228
alt_size_medium         2.9054      0.068     42.869      0.000       2.773       3.038
alt_size_large          3.4056      0.088     38.780      0.000       3.234       3.578
alt_size_very_large     4.0169      0.591      6.796      0.000       2.858       5.175
beneficiary_x_esc       5.3174      0.106     50.401      0.000       5.111       5.524
same_sector             1.3517      0.102     13.259      0.000       1.152       1.552
=======================================================================================

--------------------------------------------------------------------------------
MODEL FIT STATISTICS
--------------------------------------------------------------------------------
Log-Likelihood: -9160.97
Number of observations: 934,464
Converged: True (model fitted successfully)

--------------------------------------------------------------------------------
COEFFICIENT ESTIMATES
--------------------------------------------------------------------------------
distance_log                  :  -2.2446 (SE=0.0245) ***
alt_enrollment_log            :  -0.4712 (SE=0.0135) ***
alt_capacity_util             :   0.0122 (SE=0.0023) ***
alt_is_public                 :   8.7156 (SE=0.4089) ***
alt_is_esc                    :  -1.3678 (SE=0.0713) ***
alt_size_medium               :   2.9054 (SE=0.0678) ***
alt_size_large                :   3.4056 (SE=0.0878) ***
alt_size_very_large           :   4.0169 (SE=0.5911) ***
beneficiary_x_esc             :   5.3174 (SE=0.1055) ***
same_sector                   :   1.3517 (SE=0.1019) ***

Significance: *** p<0.01, ** p<0.05, * p<0.10

1. distance_log = -2.24*
    - ✅ PERFECT! Negative coefficient means students strongly prefer closer schools
    - Each unit increase in log(distance) reduces utility by 2.24
2. beneficiary_x_esc = +5.32*
    - ✅ PERFECT! Beneficiaries have very strong preference for ESC schools
    - This is the largest positive effect in the model
3. same_sector = +1.35*
    - ✅ Expected! Students prefer to stay in the same sector (continuity)
4. alt_is_public = +8.72*
    - ✅ Public schools are generally preferred (likely due to zero tuition)
5. School size effects (Medium/Large/Very Large = +2.91, +3.41, +4.02)*
    - ✅ Students prefer larger schools (more resources, programs, peers)
6. alt_enrollment_log = -0.47*
    - Interesting: controlling for size category, students avoid schools with higher enrollment
    - Could indicate preference for less crowded schools within size categories
7. alt_capacity_util = +0.01*
    - Small positive effect: slight preference for popular schools (revealed preference)
8. alt_is_esc = -1.37*
    - Without beneficiary status, ESC schools are less preferred
    - But for beneficiaries: -1.37 + 5.32 = +3.95 (strongly positive!)

In [48]:
# Save results
results_path = OUTPUT_DIR / "dce_model_results.txt"
with open(results_path, "w") as f:
    f.write(results.summary().as_text())
print(f"\n✓ Results saved to: {results_path}")

# Save coefficients
coef_df = pd.DataFrame(
    {
        "feature": model_features,
        "coefficient": [coefficients[f] for f in model_features],
        "std_error": [std_errors[f] for f in model_features],
        "p_value": [p_values[f] for f in model_features],
    }
)
coef_path = OUTPUT_DIR / "dce_coefficients.csv"
coef_df.to_csv(coef_path, index=False)
print(f"✓ Coefficients saved to: {coef_path}")

print("\n" + "=" * 80)
print("✓ TASK 3.2 COMPLETE")
print("=" * 80)

✓ Results saved to: output/rizal_choice_simulation/dce_model_results.txt
✓ Coefficients saved to: output/rizal_choice_simulation/dce_coefficients.csv

================================================================================
✓ TASK 3.2 COMPLETE
================================================================================

#### 3.2b

In [58]:
# ============================================================================
# STEP 1: LOAD DCE DATASET (with tuition features)
# ============================================================================
print("\n" + "="*80)
print("STEP 1: LOADING DCE DATASET")
print("="*80)

# BASE_DIR = Path('/workspace/innovation-projects/project_paaral')
dce_dataset_path = 'output/rizal_choice_simulation/rizal_dce_dataset.csv'

print(f"\nLoading DCE dataset from: {dce_dataset_path}")

# Read with efficient dtypes
dtype_spec = {
    'learner_index': 'int32',
    'chosen': 'int8',
    'is_beneficiary': 'int8',
    'alt_is_esc': 'int8',
    'alt_is_public': 'int8',
    'same_sector': 'int8',
    'alt_size_medium': 'int8',
    'alt_size_large': 'int8',
    'alt_size_very_large': 'int8',
    'alt_has_tuition': 'int8',
    'distance_log': 'float32',
    'alt_tuition_thousands': 'float32',
    'alt_tuition_log': 'float32',
    'distance_x_beneficiary': 'float32',
    'tuition_x_beneficiary': 'float32',
    'beneficiary_x_esc': 'float32',
    'alt_capacity_util': 'float32'
}

dce_data = pd.read_csv(dce_dataset_path, dtype=dtype_spec)

print(f"✓ Loaded DCE dataset: {len(dce_data):,} rows")
print(f"  Learners: {dce_data['learner_index'].nunique():,}")
print(f"  Features: {dce_data.shape[1]} columns")

================================================================================
STEP 1: LOADING DCE DATASET
================================================================================

Loading DCE dataset from: output/rizal_choice_simulation/rizal_dce_dataset.csv
✓ Loaded DCE dataset: 934,464 rows
  Learners: 48,585
  Features: 35 columns

In [59]:
# Verify tuition features exist
required_features = ['alt_tuition_thousands', 'tuition_x_beneficiary', 'distance_x_beneficiary']
missing = [f for f in required_features if f not in dce_data.columns]
if missing:
    raise ValueError(f"ERROR: Missing required features: {missing}\nDid you re-run Task 3.1 with tuition features?")

print("\n✓ Tuition features detected:")
print(f"  alt_tuition_thousands: {dce_data['alt_tuition_thousands'].notna().sum():,} non-null")
print(f"  tuition_x_beneficiary: {(dce_data['tuition_x_beneficiary'] != 0).sum():,} non-zero")
print(f"  distance_x_beneficiary: {(dce_data['distance_x_beneficiary'] != 0).sum():,} non-zero")

# ============================================================================
# STEP 2: PREPARE MODEL VARIABLES
# ============================================================================
print("\n" + "="*80)
print("STEP 2: PREPARING MODEL VARIABLES")
print("="*80)

# Define model features with beneficiary interactions
model_features = [
    # BASE EFFECTS (for non-beneficiaries)
    'distance_log',              # Distance penalty (non-beneficiaries)
    'alt_tuition_thousands',     # Tuition penalty (non-beneficiaries)
    'alt_is_public',             # Public school preference
    'alt_capacity_util',         # Capacity utilization
    'alt_size_medium',           # Size: Medium
    'alt_size_large',            # Size: Large
    'alt_size_very_large',       # Size: Very Large
    'same_sector',               # Sector continuity

    # INTERACTION EFFECTS (additional for beneficiaries)
    'distance_x_beneficiary',    # Additional distance effect for beneficiaries
    'tuition_x_beneficiary',     # Additional tuition effect for beneficiaries
    'beneficiary_x_esc',         # Beneficiary × ESC school
]

print(f"\nModel specification: {len(model_features)} features")
print("\nBase effects (non-beneficiaries):")
for f in model_features[:8]:
    print(f"  - {f}")

print("\nInteraction effects (beneficiaries):")
for f in model_features[8:]:
    print(f"  - {f}")

# Create feature matrix
X = dce_data[model_features].values.astype(np.float64)

# Create outcome variable
y = dce_data['chosen'].values.astype(np.int32)

# Create groups (learner identifiers for conditional logit)
groups = dce_data['learner_index'].values.astype(np.int32)

print(f"\n✓ Model matrices created:")
print(f"  X shape: {X.shape}")
print(f"  y shape: {y.shape}")
print(f"  groups: {len(np.unique(groups)):,} unique learners")

# Data quality checks
print(f"\nData quality:")
print(f"  Choices: {y.sum():,} chosen alternatives")
print(f"  Non-beneficiaries: {(dce_data['is_beneficiary'] == 0).sum():,} observations")
print(f"  Beneficiaries: {(dce_data['is_beneficiary'] == 1).sum():,} observations")
print(f"  Beneficiaries (% of total): {100 * dce_data['is_beneficiary'].mean():.1f}%")

# Check variation in key interaction terms
print(f"\nInteraction term variation:")
print(f"  distance_x_beneficiary non-zero: {(X[:, model_features.index('distance_x_beneficiary')] != 0).sum():,}")
print(f"  tuition_x_beneficiary non-zero: {(X[:, model_features.index('tuition_x_beneficiary')] != 0).sum():,}")
print(f"  beneficiary_x_esc = 1: {(X[:, model_features.index('beneficiary_x_esc')] == 1).sum():,}")

# ============================================================================
# STEP 3: ESTIMATE CONDITIONAL LOGIT MODEL
# ============================================================================
print("\n" + "="*80)
print("STEP 3: ESTIMATING CONDITIONAL LOGIT MODEL")
print("="*80)

from statsmodels.discrete.conditional_models import ConditionalLogit

print("\nInitializing ConditionalLogit model...")
model = ConditionalLogit(endog=y, exog=X, groups=groups)

print("Estimating model (this may take 2-5 minutes)...")
print("  Method: BFGS (Quasi-Newton)")
print("  Max iterations: 100")

results = model.fit(
    method='bfgs',
    maxiter=100,
    disp=True,
    gtol=1e-5
)

print("\n✓ Model estimation complete!")

✓ Tuition features detected:
  alt_tuition_thousands: 934,464 non-null
  tuition_x_beneficiary: 42,708 non-zero
  distance_x_beneficiary: 117,835 non-zero

================================================================================
STEP 2: PREPARING MODEL VARIABLES
================================================================================

Model specification: 11 features

Base effects (non-beneficiaries):
  - distance_log
  - alt_tuition_thousands
  - alt_is_public
  - alt_capacity_util
  - alt_size_medium
  - alt_size_large
  - alt_size_very_large
  - same_sector

Interaction effects (beneficiaries):
  - distance_x_beneficiary
  - tuition_x_beneficiary
  - beneficiary_x_esc

✓ Model matrices created:
  X shape: (934464, 11)
  y shape: (934464,)
  groups: 48,585 unique learners

Data quality:
  Choices: 48,585 chosen alternatives
  Non-beneficiaries: 814,101 observations
  Beneficiaries: 120,363 observations
  Beneficiaries (% of total): 12.9%

Interaction term variation:
  distance_x_beneficiary non-zero: 117,835
  tuition_x_beneficiary non-zero: 42,708
  beneficiary_x_esc = 1: 43,005

================================================================================
STEP 3: ESTIMATING CONDITIONAL LOGIT MODEL
================================================================================

Initializing ConditionalLogit model...
Estimating model (this may take 2-5 minutes)...
  Method: BFGS (Quasi-Newton)
  Max iterations: 100
         Current function value: 0.011118
         Iterations: 100
         Function evaluations: 104
         Gradient evaluations: 104

✓ Model estimation complete!

In [62]:
# ============================================================================
# STEP 4: DISPLAY RESULTS
# ============================================================================
print("\n" + "="*80)
print("STEP 4: MODEL RESULTS")
print("="*80)

print("\n" + "-"*80)
print("FULL MODEL SUMMARY")
print("-"*80)
print(results.summary())

# ============================================================================
# STEP 5: BENEFICIARY-SPECIFIC COEFFICIENT ANALYSIS (FIXED)
# ============================================================================
print("\n" + "="*80)
print("STEP 5: BENEFICIARY-SPECIFIC ANALYSIS")
print("="*80)

# FIX: Create feature name to index mapping
feature_indices = {name: i for i, name in enumerate(model_features)}

print("\nFeature index mapping:")
for name, idx in feature_indices.items():
  print(f"  {idx}: {name}")

# Extract coefficients using integer indices - FIX ALL THESE LINES:
coef_distance_base = results.params[feature_indices['distance_log']]
coef_distance_interaction = results.params[feature_indices['distance_x_beneficiary']]  # FIXED
coef_tuition_base = results.params[feature_indices['alt_tuition_thousands']]  # FIXED
coef_tuition_interaction = results.params[feature_indices['tuition_x_beneficiary']]  # FIXED
coef_esc = results.params[feature_indices['beneficiary_x_esc']]  # FIXED

# Calculate total effects
distance_nonben = coef_distance_base
distance_ben = coef_distance_base + coef_distance_interaction

tuition_nonben = coef_tuition_base
tuition_ben = coef_tuition_base + coef_tuition_interaction

print("\n" + "-"*80)
print("KEY COEFFICIENTS")
print("-"*80)

print("\n1. DISTANCE EFFECTS:")
print(f"   Base coefficient (non-beneficiaries): {distance_nonben:.4f}")
print(f"   Interaction coefficient: {coef_distance_interaction:.4f}")
print(f"   Total effect (beneficiaries): {distance_ben:.4f}")
print(f"   Difference: {distance_ben - distance_nonben:.4f}")
if abs(coef_distance_interaction) > 0.1:
  if coef_distance_interaction < 0:
      print(f"   ⚠️  Beneficiaries are MORE distance-sensitive!")
  else:
      print(f"   ✓ Beneficiaries are LESS distance-sensitive")
else:
  print(f"   → Distance matters equally for both groups")

print("\n2. TUITION EFFECTS:")
print(f"   Base coefficient (non-beneficiaries): {tuition_nonben:.4f} (per ₱1,000)")
print(f"   Interaction coefficient: {coef_tuition_interaction:.4f}")
print(f"   Total effect (beneficiaries): {tuition_ben:.4f} (per ₱1,000)")
print(f"   Difference: {tuition_ben - tuition_nonben:.4f}")
if abs(coef_tuition_interaction) > 0.01:
  if coef_tuition_interaction < 0:
      print(f"   ⚠️  Beneficiaries are MORE price-sensitive (unexpected!)")
  else:
      print(f"   ✓ Beneficiaries are LESS price-sensitive (ESC subsidy working!)")
else:
  print(f"   → Tuition matters equally for both groups")

print("\n3. ESC SCHOOL PREFERENCE:")
print(f"   Beneficiary × ESC: {coef_esc:.4f}")
if coef_esc > 1.0:
  print(f"   ✓ Strong preference for ESC schools among beneficiaries")
elif coef_esc > 0:
  print(f"   ✓ Moderate preference for ESC schools among beneficiaries")
else:
  print(f"   ⚠️  Unexpected: No ESC preference detected")

================================================================================
STEP 4: MODEL RESULTS
================================================================================

--------------------------------------------------------------------------------
FULL MODEL SUMMARY
--------------------------------------------------------------------------------
                  Conditional Logit Model Regression Results
==============================================================================
Dep. Variable:                      y   No. Observations:               934464
Model:               ConditionalLogit   No. groups:                      48585
Log-Likelihood:               -10390.   Min group size:                     12
Method:                          bfgs   Max group size:                     29
Date:                Tue, 18 Nov 2025   Mean group size:                  19.2
Time:                        16:37:50
==============================================================================
                 coef    std err          z      P>|z|      [0.025      0.975]
------------------------------------------------------------------------------
x1            -1.7425      0.026    -68.000      0.000      -1.793      -1.692
x2            -0.0270      0.002    -17.305      0.000      -0.030      -0.024
x3             8.7897      0.562     15.639      0.000       7.688       9.891
x4             0.0048      0.002      2.308      0.021       0.001       0.009
x5             1.6006      0.053     30.299      0.000       1.497       1.704
x6             1.6524      0.072     22.936      0.000       1.511       1.794
x7             4.5259      1.659      2.728      0.006       1.274       7.778
x8             0.0994      0.100      0.990      0.322      -0.097       0.296
x9            -0.4635      0.040    -11.608      0.000      -0.542      -0.385
x10            0.0252      0.003     10.074      0.000       0.020       0.030
x11            2.6510      0.093     28.600      0.000       2.469       2.833
==============================================================================

================================================================================
STEP 5: BENEFICIARY-SPECIFIC ANALYSIS
================================================================================

Feature index mapping:
  0: distance_log
  1: alt_tuition_thousands
  2: alt_is_public
  3: alt_capacity_util
  4: alt_size_medium
  5: alt_size_large
  6: alt_size_very_large
  7: same_sector
  8: distance_x_beneficiary
  9: tuition_x_beneficiary
  10: beneficiary_x_esc

--------------------------------------------------------------------------------
KEY COEFFICIENTS
--------------------------------------------------------------------------------

1. DISTANCE EFFECTS:
   Base coefficient (non-beneficiaries): -1.7425
   Interaction coefficient: -0.4635
   Total effect (beneficiaries): -2.2060
   Difference: -0.4635
   ⚠️  Beneficiaries are MORE distance-sensitive!

2. TUITION EFFECTS:
   Base coefficient (non-beneficiaries): -0.0270 (per ₱1,000)
   Interaction coefficient: 0.0252
   Total effect (beneficiaries): -0.0017 (per ₱1,000)
   Difference: 0.0252
   ✓ Beneficiaries are LESS price-sensitive (ESC subsidy working!)

3. ESC SCHOOL PREFERENCE:
   Beneficiary × ESC: 2.6510
   ✓ Strong preference for ESC schools among beneficiaries

In [64]:
# ============================================================================
# STEP 6: STATISTICAL SIGNIFICANCE TESTS (FIXED)
# ============================================================================
print("\n" + "="*80)
print("STEP 6: STATISTICAL SIGNIFICANCE")
print("="*80)

# Extract p-values using integer indices (FIXED)
pval_distance_base = results.pvalues[feature_indices['distance_log']]
pval_distance_interaction = results.pvalues[feature_indices['distance_x_beneficiary']]
pval_tuition_base = results.pvalues[feature_indices['alt_tuition_thousands']]
pval_tuition_interaction = results.pvalues[feature_indices['tuition_x_beneficiary']]
pval_esc = results.pvalues[feature_indices['beneficiary_x_esc']]

print("\nBase effects (non-beneficiaries):")
print(f"  distance_log: p-value = {pval_distance_base:.6f}", end="")
if pval_distance_base < 0.001:
    print(" ***")
elif pval_distance_base < 0.01:
    print(" **")
elif pval_distance_base < 0.05:
    print(" *")
else:
    print(" (not significant)")

print(f"  alt_tuition_thousands: p-value = {pval_tuition_base:.6f}", end="")
if pval_tuition_base < 0.001:
    print(" ***")
elif pval_tuition_base < 0.01:
    print(" **")
elif pval_tuition_base < 0.05:
    print(" *")
else:
    print(" (not significant)")

print("\nInteraction effects (beneficiaries):")
print(f"  distance_x_beneficiary: p-value = {pval_distance_interaction:.6f}", end="")
if pval_distance_interaction < 0.001:
    print(" ***")
elif pval_distance_interaction < 0.01:
    print(" **")
elif pval_distance_interaction < 0.05:
    print(" *")
else:
    print(" (not significant)")

print(f"  tuition_x_beneficiary: p-value = {pval_tuition_interaction:.6f}", end="")
if pval_tuition_interaction < 0.001:
    print(" ***")
elif pval_tuition_interaction < 0.01:
    print(" **")
elif pval_tuition_interaction < 0.05:
    print(" *")
else:
    print(" (not significant)")

print(f"  beneficiary_x_esc: p-value = {pval_esc:.6f}", end="")
if pval_esc < 0.001:
    print(" ***")
elif pval_esc < 0.01:
    print(" **")
elif pval_esc < 0.05:
    print(" *")
else:
    print(" (not significant)")

print("\n  Significance levels: *** p<0.001, ** p<0.01, * p<0.05")

================================================================================
STEP 6: STATISTICAL SIGNIFICANCE
================================================================================

Base effects (non-beneficiaries):
  distance_log: p-value = 0.000000 ***
  alt_tuition_thousands: p-value = 0.000000 ***

Interaction effects (beneficiaries):
  distance_x_beneficiary: p-value = 0.000000 ***
  tuition_x_beneficiary: p-value = 0.000000 ***
  beneficiary_x_esc: p-value = 0.000000 ***

  Significance levels: *** p<0.001, ** p<0.01, * p<0.05

In [65]:
# ============================================================================
# STEP 7: CREATE COMPARISON TABLE (FIXED)
# ============================================================================
print("\n" + "="*80)
print("STEP 7: BENEFICIARY vs NON-BENEFICIARY COMPARISON TABLE")
print("="*80)

comparison_data = {
    'Feature': ['Distance (log km)', 'Tuition (₱1000)'],
    'Non-Beneficiary Coefficient': [distance_nonben, tuition_nonben],
    'Beneficiary Coefficient': [distance_ben, tuition_ben],
    'Difference (Interaction)': [coef_distance_interaction, coef_tuition_interaction],
    'Interaction p-value': [pval_distance_interaction, pval_tuition_interaction]
}

comparison_df = pd.DataFrame(comparison_data)
comparison_df['Significant'] = comparison_df['Interaction p-value'].apply(
    lambda p: '***' if p < 0.001 else ('**' if p < 0.01 else ('*' if p < 0.05 else 'No'))
)

print("\n" + comparison_df.to_string(index=False))

print("\n" + "-"*80)
print("INTERPRETATION GUIDE")
print("-"*80)
print("Distance coefficient: More negative = stronger penalty for distance")
print("  → Beneficiaries: -2.21 means they STRONGLY prefer nearby schools")
print("  → More negative than non-beneficiaries = MORE distance-sensitive")
print("")
print("Tuition coefficient: More negative = stronger penalty for tuition")
print("  → Beneficiaries: -0.0018 means tuition barely matters")
print("  → ESC subsidy successfully eliminates price barrier!")
print("")
print("Interaction coefficient interpretation:")
print("  Negative interaction: Beneficiaries MORE sensitive (larger penalty)")
print("  Positive interaction: Beneficiaries LESS sensitive (smaller penalty)")

================================================================================
STEP 7: BENEFICIARY vs NON-BENEFICIARY COMPARISON TABLE
================================================================================

          Feature  Non-Beneficiary Coefficient  Beneficiary Coefficient  Difference (Interaction)  Interaction p-value Significant
Distance (log km)                    -1.742501                -2.205962                 -0.463461         3.732060e-31         ***
  Tuition (₱1000)                    -0.026959                -0.001723                  0.025236         7.173915e-24         ***

--------------------------------------------------------------------------------
INTERPRETATION GUIDE
--------------------------------------------------------------------------------
Distance coefficient: More negative = stronger penalty for distance
  → Beneficiaries: -2.21 means they STRONGLY prefer nearby schools
  → More negative than non-beneficiaries = MORE distance-sensitive

Tuition coefficient: More negative = stronger penalty for tuition
  → Beneficiaries: -0.0018 means tuition barely matters
  → ESC subsidy successfully eliminates price barrier!

Interaction coefficient interpretation:
  Negative interaction: Beneficiaries MORE sensitive (larger penalty)
  Positive interaction: Beneficiaries LESS sensitive (smaller penalty)

In [66]:
# ============================================================================
# STEP 8: POLICY IMPLICATIONS (FIXED)
# ============================================================================
print("\n" + "="*80)
print("STEP 8: POLICY IMPLICATIONS")
print("="*80)

print("\nAnswering Policy Question #1:")
print("'For beneficiaries, what features most affect their choice outcome?'")
print("")

# Get ALL relevant coefficients for beneficiaries
coef_public = results.params[feature_indices['alt_is_public']]
coef_capacity = results.params[feature_indices['alt_capacity_util']]
coef_same_sector = results.params[feature_indices['same_sector']]

# Rank features by absolute coefficient magnitude for beneficiaries
beneficiary_effects = {
    'ESC School': coef_esc,
    'Public School': coef_public,
    'Distance (log km)': distance_ben,
    'Tuition (₱1000)': tuition_ben,
    'Same Sector': coef_same_sector,
    'Capacity Utilization': coef_capacity,
}

print("Ranked by importance (absolute magnitude for beneficiaries):")
sorted_effects = sorted(beneficiary_effects.items(), key=lambda x: abs(x[1]), reverse=True)
for i, (feature, coef) in enumerate(sorted_effects, 1):
    print(f"  {i}. {feature:25s} coefficient = {coef:+.4f}")

print("\n" + "-"*80)
print("KEY FINDINGS")
print("-"*80)

# Finding 1: Distance sensitivity
print("\n1. DISTANCE SENSITIVITY:")
if pval_distance_interaction < 0.05:
    if coef_distance_interaction < 0:
        print(f"   ⚠️  Beneficiaries are MORE distance-sensitive than non-beneficiaries")
        print(f"       Non-beneficiaries: {distance_nonben:.4f}")
        print(f"       Beneficiaries: {distance_ben:.4f} (difference: {coef_distance_interaction:.4f})")
        print(f"")
        print(f"   INTERPRETATION:")
        print(f"   - Beneficiaries STRONGLY prefer nearby schools")
        print(f"   - They are LESS willing to travel than non-beneficiaries")
        print(f"   - Distance is a BINDING CONSTRAINT for ESC program")
        print(f"")
        print(f"   POLICY IMPLICATION:")
        print(f"   - Expanding ESC to farther schools will have LOW uptake")
        print(f"   - Consider: (a) Transportation subsidies, or")
        print(f"              (b) Build NEW ESC schools in underserved areas")
    else:
        print(f"   ✓ Beneficiaries are LESS distance-sensitive than non-beneficiaries")
        print(f"     → ESC subsidy appears to compensate for travel costs")
else:
    print(f"   → Distance sensitivity is similar for both groups (p = {pval_distance_interaction:.4f})")

# Finding 2: Price sensitivity
print("\n2. TUITION PRICE SENSITIVITY:")
if pval_tuition_interaction < 0.05:
    if coef_tuition_interaction > 0:
        print(f"   ✓ Beneficiaries are LESS price-sensitive than non-beneficiaries")
        print(f"       Non-beneficiaries: {tuition_nonben:.4f} per ₱1,000")
        print(f"       Beneficiaries: {tuition_ben:.4f} per ₱1,000 (difference: +{coef_tuition_interaction:.4f})")
        print(f"")
        print(f"   INTERPRETATION:")
        print(f"   - ESC subsidy SUCCESSFULLY reduces price barriers")
        print(f"   - Tuition cost is MINIMAL factor for beneficiaries")
        print(f"   - Price elasticity near zero for beneficiaries")
        print(f"")
        print(f"   POLICY IMPLICATION:")
        print(f"   - ESC subsidy amount is adequate for eliminating price sensitivity")
        print(f"   - Focus on OTHER barriers (distance, information, quality)")
    else:
        print(f"   ⚠️  Beneficiaries are MORE price-sensitive (unexpected!)")
else:
    print(f"   → Tuition sensitivity is similar for both groups (p = {pval_tuition_interaction:.4f})")

# Finding 3: ESC preference
print("\n3. ESC SCHOOL PREFERENCE:")
if pval_esc < 0.001:
    print(f"   ✓ STRONG preference for ESC schools among beneficiaries")
    print(f"       Coefficient: +{coef_esc:.4f} (highly significant)")
    print(f"")
    print(f"   INTERPRETATION:")
    print(f"   - Beneficiaries actively seek out ESC-participating schools")
    print(f"   - ESC brand/reputation has positive value")
    print(f"   - Program targeting is working effectively")
elif pval_esc < 0.05:
    print(f"   ✓ Moderate preference for ESC schools among beneficiaries")
    print(f"       Coefficient: +{coef_esc:.4f}")
else:
    print(f"   ⚠️  No significant ESC preference detected (unexpected)")

# Finding 4: What matters MOST
print("\n4. WHAT MATTERS MOST FOR BENEFICIARIES?")
top_3 = sorted_effects[:3]
print(f"")
print(f"   Top 3 factors (by absolute magnitude):")
for i, (feature, coef) in enumerate(top_3, 1):
    if feature == 'Distance (log km)':
        print(f"   {i}. {feature:25s} {coef:+.4f} → MAJOR BARRIER")
    elif feature == 'ESC School':
        print(f"   {i}. {feature:25s} {coef:+.4f} → STRONG PREFERENCE")
    elif feature == 'Public School':
        print(f"   {i}. {feature:25s} {coef:+.4f} → STRONG PREFERENCE")
    elif feature == 'Tuition (₱1000)':
        print(f"   {i}. {feature:25s} {coef:+.4f} → MINIMAL BARRIER")
    else:
        print(f"   {i}. {feature:25s} {coef:+.4f}")

print("\n" + "-"*80)
print("SUMMARY ANSWER TO POLICY QUESTION #1")
print("-"*80)
print("\nFor beneficiaries choosing Grade 7 destination schools:")
print("")
print("✓ DISTANCE MATTERS A LOT:")
print("  - Coefficient: -2.21 (strong negative)")
print("  - More sensitive than non-beneficiaries")
print("  - Major constraint on school choice")
print("")
print("✓ TUITION BARELY MATTERS:")
print("  - Coefficient: -0.0018 (near zero)")
print("  - ESC subsidy successfully eliminates price barrier")
print("  - NOT a binding constraint")
print("")
print("✓ ESC SCHOOL STATUS MATTERS:")
print(f"  - Coefficient: +{coef_esc:.2f} (strong positive)")
print("  - Beneficiaries actively prefer ESC schools")
print("  - Program reputation/awareness working")

================================================================================
STEP 8: POLICY IMPLICATIONS
================================================================================

Answering Policy Question #1:
'For beneficiaries, what features most affect their choice outcome?'

Ranked by importance (absolute magnitude for beneficiaries):
  1. Public School             coefficient = +8.7897
  2. ESC School                coefficient = +2.6510
  3. Distance (log km)         coefficient = -2.2060
  4. Same Sector               coefficient = +0.0994
  5. Capacity Utilization      coefficient = +0.0048
  6. Tuition (₱1000)           coefficient = -0.0017

--------------------------------------------------------------------------------
KEY FINDINGS
--------------------------------------------------------------------------------

1. DISTANCE SENSITIVITY:
   ⚠️  Beneficiaries are MORE distance-sensitive than non-beneficiaries
       Non-beneficiaries: -1.7425
       Beneficiaries: -2.2060 (difference: -0.4635)

   INTERPRETATION:
   - Beneficiaries STRONGLY prefer nearby schools
   - They are LESS willing to travel than non-beneficiaries
   - Distance is a BINDING CONSTRAINT for ESC program

   POLICY IMPLICATION:
   - Expanding ESC to farther schools will have LOW uptake
   - Consider: (a) Transportation subsidies, or
              (b) Build NEW ESC schools in underserved areas

2. TUITION PRICE SENSITIVITY:
   ✓ Beneficiaries are LESS price-sensitive than non-beneficiaries
       Non-beneficiaries: -0.0270 per ₱1,000
       Beneficiaries: -0.0017 per ₱1,000 (difference: +0.0252)

   INTERPRETATION:
   - ESC subsidy SUCCESSFULLY reduces price barriers
   - Tuition cost is MINIMAL factor for beneficiaries
   - Price elasticity near zero for beneficiaries

   POLICY IMPLICATION:
   - ESC subsidy amount is adequate for eliminating price sensitivity
   - Focus on OTHER barriers (distance, information, quality)

3. ESC SCHOOL PREFERENCE:
   ✓ STRONG preference for ESC schools among beneficiaries
       Coefficient: +2.6510 (highly significant)

   INTERPRETATION:
   - Beneficiaries actively seek out ESC-participating schools
   - ESC brand/reputation has positive value
   - Program targeting is working effectively

4. WHAT MATTERS MOST FOR BENEFICIARIES?

   Top 3 factors (by absolute magnitude):
   1. Public School             +8.7897 → STRONG PREFERENCE
   2. ESC School                +2.6510 → STRONG PREFERENCE
   3. Distance (log km)         -2.2060 → MAJOR BARRIER

--------------------------------------------------------------------------------
SUMMARY ANSWER TO POLICY QUESTION #1
--------------------------------------------------------------------------------

For beneficiaries choosing Grade 7 destination schools:

✓ DISTANCE MATTERS A LOT:
  - Coefficient: -2.21 (strong negative)
  - More sensitive than non-beneficiaries
  - Major constraint on school choice

✓ TUITION BARELY MATTERS:
  - Coefficient: -0.0018 (near zero)
  - ESC subsidy successfully eliminates price barrier
  - NOT a binding constraint

✓ ESC SCHOOL STATUS MATTERS:
  - Coefficient: +2.65 (strong positive)
  - Beneficiaries actively prefer ESC schools
  - Program reputation/awareness working

In [78]:
(results.tvalues)

array([-67.99979573, -17.30463328,  15.63936556,   2.30814253,
        30.29904386,  22.93635608,   2.72794874,   0.99048881,
       -11.60847644,  10.07434229,  28.59987142])

In [80]:
# ============================================================================
# STEP 9: EXPORT RESULTS (FIXED)
# ============================================================================
print("\n" + "="*80)
print("STEP 9: EXPORTING RESULTS")
print("="*80)

# Export coefficient table with proper feature names
output_dir = Path('output/rizal_choice_simulation')
# os.mkdir(output_dir, parents=True, exist_ok=True)

coefficients_df = pd.DataFrame({
    'feature': model_features,
    'coefficient': results.params,
    'std_error': results.bse,
    'z_statistic': results.tvalues,
    'p_value': results.pvalues
})

# Add significance stars
coefficients_df['significance'] = coefficients_df['p_value'].apply(
    lambda p: '***' if p < 0.001 else ('**' if p < 0.01 else ('*' if p < 0.05 else ''))
)

coef_output_path = output_dir / 'dce_coefficients_beneficiary_specific.csv'
coefficients_df.to_csv(coef_output_path, index=False)
print(f"✓ Coefficients exported to: {coef_output_path}")

# Export comparison table
comparison_output_path = output_dir / 'beneficiary_comparison_table.csv'
comparison_df.to_csv(comparison_output_path, index=False)
print(f"✓ Comparison table exported to: {comparison_output_path}")

# Export full model summary with feature mapping
summary_output_path = output_dir / 'dce_model_summary_beneficiary_specific.txt'
with open(summary_output_path, 'w') as f:
    f.write("="*80 + "\n")
    f.write("BENEFICIARY-SPECIFIC DCE MODEL RESULTS\n")
    f.write("="*80 + "\n\n")

    f.write(str(results.summary()))

    f.write("\n\n" + "="*80 + "\n")
    f.write("FEATURE NAME MAPPING\n")
    f.write("="*80 + "\n")
    for name, idx in feature_indices.items():
        coef = results.params[idx]
        pval = results.pvalues[idx]
        sig = '***' if pval < 0.001 else ('**' if pval < 0.01 else ('*' if pval < 0.05 else ''))
        f.write(f"x{idx+1} = {name:30s} coef={coef:+.4f} {sig}\n")

    f.write("\n" + "="*80 + "\n")
    f.write("KEY FINDINGS\n")
    f.write("="*80 + "\n\n")

    f.write("Distance Effects:\n")
    f.write(f"  Non-beneficiaries: {distance_nonben:.4f}\n")
    f.write(f"  Beneficiaries:     {distance_ben:.4f}\n")
    f.write(f"  Interaction:       {coef_distance_interaction:.4f} (p={pval_distance_interaction:.6f})\n\n")

    f.write("Tuition Effects:\n")
    f.write(f"  Non-beneficiaries: {tuition_nonben:.4f} per ₱1000\n")
    f.write(f"  Beneficiaries:     {tuition_ben:.4f} per ₱1000\n")
    f.write(f"  Interaction:       {coef_tuition_interaction:.4f} (p={pval_tuition_interaction:.6f})\n\n")

    f.write("ESC Preference:\n")
    f.write(f"  Beneficiary × ESC: {coef_esc:.4f} (p={pval_esc:.6f})\n")

print(f"✓ Model summary exported to: {summary_output_path}")

# Export ranked effects for beneficiaries
ranked_output_path = output_dir / 'beneficiary_ranked_effects.csv'
ranked_df = pd.DataFrame(sorted_effects, columns=['Feature', 'Coefficient'])
ranked_df['Absolute_Magnitude'] = ranked_df['Coefficient'].abs()
ranked_df = ranked_df.sort_values('Absolute_Magnitude', ascending=False)
ranked_df.to_csv(ranked_output_path, index=False)
print(f"✓ Ranked effects exported to: {ranked_output_path}")

print("\n" + "="*80)
print("✓ TASK 3.2b COMPLETE")
print("="*80)

print("\nOutputs created:")
print(f"  1. {coef_output_path.name}")
print(f"  2. {comparison_output_path.name}")
print(f"  3. {summary_output_path.name}")
print(f"  4. {ranked_output_path.name}")

print("\nNext steps:")
print("  1. Review comparison table - answers your Policy Question #1")
print("  2. Consider transportation subsidy scenarios in simulation")
print("  3. Test ESC expansion vs new school construction policies")
print("  4. Distance is the key barrier - focus simulation on this!")

================================================================================
STEP 9: EXPORTING RESULTS
================================================================================
✓ Coefficients exported to: output/rizal_choice_simulation/dce_coefficients_beneficiary_specific.csv
✓ Comparison table exported to: output/rizal_choice_simulation/beneficiary_comparison_table.csv
✓ Model summary exported to: output/rizal_choice_simulation/dce_model_summary_beneficiary_specific.txt
✓ Ranked effects exported to: output/rizal_choice_simulation/beneficiary_ranked_effects.csv

================================================================================
✓ TASK 3.2b COMPLETE
================================================================================

Outputs created:
  1. dce_coefficients_beneficiary_specific.csv
  2. beneficiary_comparison_table.csv
  3. dce_model_summary_beneficiary_specific.txt
  4. beneficiary_ranked_effects.csv

Next steps:
  1. Review comparison table - answers your Policy Question #1
  2. Consider transportation subsidy scenarios in simulation
  3. Test ESC expansion vs new school construction policies
  4. Distance is the key barrier - focus simulation on this!

### Task 3.3

In [81]:
# ===================================================================
# TASK 3.3: MODEL VALIDATION (OPTIMIZED)
# ===================================================================

# Cell: Task 3.3 - Model Validation (OPTIMIZED)
# %%time
print("="*80)
print("TASK 3.3: MODEL VALIDATION (OPTIMIZED)")
print("="*80)

print("\nPerforming model validation...")

# ===================================================================
# STEP 1: Calculate probabilities manually (FIXED)
# ===================================================================
print("\n[1/4] Computing predictions (manual calculation)...")

# ConditionalLogit doesn't have predict() - calculate probabilities manually
# P(i|choice_set) = exp(V_i) / sum(exp(V_j) for all j in choice_set)

print("  Calculating utility values...")

# Calculate utility (linear predictor) for all alternatives
# V = β₁*X₁ + β₂*X₂ + ... + βₖ*Xₖ
utilities = np.zeros(len(dce_data), dtype=np.float32)

coefficients = results.params
for feat in model_features:
  utilities += coefficients[feat] * dce_data[feat].values

dce_data['utility'] = utilities

print(f"  ✓ Utilities calculated")

# Calculate probabilities within each choice set
print("  Calculating choice probabilities...")

def calculate_choice_probabilities(group):
  """Calculate multinomial logit probabilities for a choice set"""
  # Subtract max for numerical stability (exp(V - max(V)))
  v_shifted = group['utility'] - group['utility'].max()
  exp_v = np.exp(v_shifted)
  probs = exp_v / exp_v.sum()
  return probs

# Apply to each choice set (grouped by learner_index)
dce_data['predicted_prob'] = dce_data.groupby('learner_index')['utility'].transform(
  lambda x: np.exp(x - x.max()) / np.exp(x - x.max()).sum()
)

print(f"✓ Predictions complete")

# Verify probabilities sum to 1 within each choice set
prob_sums = dce_data.groupby('learner_index')['predicted_prob'].sum()
if np.allclose(prob_sums, 1.0, atol=1e-6):
  print(f"  ✓ Probabilities sum to 1.0 within each choice set")
else:
  print(f"  WARNING: Some probability sums deviate from 1.0")
  print(f"    Min sum: {prob_sums.min():.6f}")
  print(f"    Max sum: {prob_sums.max():.6f}")

# ===================================================================
# STEP 2: Calculate accuracy (OPTIMIZED)
# ===================================================================
print("\n[2/4] Computing prediction accuracy...")

# OPTIMIZATION 13: Use groupby idxmax for fast prediction
predicted_idx = dce_data.groupby('learner_index')['predicted_prob'].idxmax()
predicted_choices = dce_data.loc[predicted_idx, ['learner_index', 'school_id_alternative']].copy()
predicted_choices = predicted_choices.rename(columns={'school_id_alternative': 'predicted'})

actual_choices = dce_data[dce_data['chosen'] == 1][['learner_index', 'school_id_alternative']].copy()
actual_choices = actual_choices.rename(columns={'school_id_alternative': 'actual'})

comparison = actual_choices.merge(predicted_choices, on='learner_index')
comparison['correct'] = (comparison['actual'] == comparison['predicted']).astype('int8')

accuracy = comparison['correct'].mean()

print(f"✓ In-sample accuracy: {accuracy * 100:.2f}%")
print(f"  Correct: {comparison['correct'].sum():,} / {len(comparison):,}")

# ===================================================================
# STEP 3: Probability distribution analysis
# ===================================================================
print("\n[3/4] Analyzing probability distribution...")

chosen_probs = dce_data[dce_data['chosen'] == 1]['predicted_prob']

print(f"\nPredicted probabilities (chosen alternatives):")
print(f"  Mean: {chosen_probs.mean():.4f}")
print(f"  Median: {chosen_probs.median():.4f}")
print(f"  Std: {chosen_probs.std():.4f}")

# ===================================================================
# STEP 4: Model diagnostics
# ===================================================================
print("\n[4/4] Model diagnostics...")

# Pseudo R²
avg_choice_set_size = dce_data.groupby('learner_index').size().mean()
ll_null = len(comparison) * np.log(1 / avg_choice_set_size)
pseudo_r2 = 1 - (results.llf / ll_null)

print(f"\nMcFadden's Pseudo R²: {pseudo_r2:.4f}")
if pseudo_r2 > 0.2:
    print(f"  → Excellent fit")
elif pseudo_r2 > 0.1:
    print(f"  → Good fit")
else:
    print(f"  → Moderate fit")

================================================================================
TASK 3.3: MODEL VALIDATION (OPTIMIZED)
================================================================================

Performing model validation...

[1/4] Computing predictions (manual calculation)...
  Calculating utility values...

IndexError: only integers, slices (`:`), ellipsis (`...`), numpy.newaxis (`None`) and integer or boolean arrays are valid indices

In [53]:
# ===================================================================
# EXPORT (OPTIMIZED)
# ===================================================================
print("\n" + "-" * 80)
print("EXPORTING RESULTS")
print("-" * 80)

# OPTIMIZATION 14: Export only essential columns
predictions_export = dce_data[['learner_index', 'lrn', 'school_id_origin',
                               'school_id_alternative', 'chosen', 'predicted_prob']].copy()

predictions_path = OUTPUT_DIR / 'dce_predictions.csv'
predictions_export.to_csv(predictions_path, index=False)
print(f"✓ Predictions: {predictions_path}")

comparison_path = OUTPUT_DIR / 'dce_validation_comparison.csv'
comparison.to_csv(comparison_path, index=False)
print(f"✓ Comparison: {comparison_path}")

# Summary
print("\n" + "=" * 80)
print("MODEL VALIDATION SUMMARY")
print("=" * 80)
print(f"  Accuracy: {accuracy * 100:.2f}%")
print(f"  Pseudo R²: {pseudo_r2:.4f}")
print(f"  Mean prob (chosen): {chosen_probs.mean():.4f}")

print("\n" + "=" * 80)
print("✓ TASK 3.3 COMPLETE")
print("=" * 80)

--------------------------------------------------------------------------------
EXPORTING RESULTS
--------------------------------------------------------------------------------
✓ Predictions: output/rizal_choice_simulation/dce_predictions.csv
✓ Comparison: output/rizal_choice_simulation/dce_validation_comparison.csv

================================================================================
MODEL VALIDATION SUMMARY
================================================================================
  Accuracy: 93.86%
  Pseudo R²: 0.9362
  Mean prob (chosen): 0.9194

================================================================================
✓ TASK 3.3 COMPLETE
================================================================================

#### 3.3b

In [84]:
print("="*80)
print("TASK 3.3: MODEL VALIDATION (REVISED FOR TASK 3.2b)")
print("="*80)

# Assumes you've already run Task 3.2b and have:
# - results (fitted model)
# - model_features (list of feature names)
# - feature_indices (mapping from feature names to indices)
# - dce_data (loaded dataset)

# Verify prerequisites
print("\nVerifying prerequisites...")
if 'results' not in dir():
    raise RuntimeError("ERROR: 'results' not found. Run Task 3.2b first!")
if 'model_features' not in dir():
    raise RuntimeError("ERROR: 'model_features' not found. Run Task 3.2b first!")
if 'feature_indices' not in dir():
    raise RuntimeError("ERROR: 'feature_indices' not found. Run Task 3.2b first!")
if 'dce_data' not in dir():
    raise RuntimeError("ERROR: 'dce_data' not found. Run Task 3.2b first!")

print("✓ All prerequisites found")
print(f"  Model: {len(model_features)} features")
print(f"  Data: {len(dce_data):,} observations")

# ============================================================================
# STEP 1: COMPUTE PREDICTIONS (MANUAL CALCULATION)
# ============================================================================
print("\n" + "="*80)
print("STEP 1: COMPUTING PREDICTIONS")
print("="*80)

print("\n[1/4] Calculating utility values...")

# Pre-allocate utilities array
utilities = np.zeros(len(dce_data), dtype=np.float32)

# Get coefficients array (no string indexing!)
coefficients = results.params

# Calculate utilities: V = β₁X₁ + β₂X₂ + ... + β₁₁X₁₁
for i, feat in enumerate(model_features):
    if feat in dce_data.columns:
        utilities += coefficients[i] * dce_data[feat].values
    else:
        print(f"  WARNING: Feature '{feat}' not found in dataset - skipping")

dce_data['utility'] = utilities

print(f"  ✓ Utilities calculated")
print(f"    Mean utility: {utilities.mean():.4f}")
print(f"    Std utility: {utilities.std():.4f}")

# ============================================================================
# STEP 2: CONVERT UTILITIES TO PROBABILITIES
# ============================================================================
print("\n[2/4] Converting utilities to choice probabilities...")

# Apply multinomial logit formula within each choice set
# P(i) = exp(V_i) / Σ exp(V_j) for all j in choice set

# Numerical stability: subtract max utility within each group
dce_data['utility_shifted'] = dce_data.groupby('learner_index')['utility'].transform(
    lambda x: x - x.max()
)

# Calculate exp(V_i)
dce_data['exp_utility'] = np.exp(dce_data['utility_shifted'])

# Calculate sum of exp(V_j) within each choice set
dce_data['sum_exp_utility'] = dce_data.groupby('learner_index')['exp_utility'].transform('sum')

# Calculate probabilities
dce_data['predicted_prob'] = dce_data['exp_utility'] / dce_data['sum_exp_utility']

print(f"  ✓ Probabilities calculated")

# Verify probabilities sum to 1 within each choice set
prob_sums = dce_data.groupby('learner_index')['predicted_prob'].sum()
print(f"    Probability sums per learner (should be 1.0):")
print(f"      Mean: {prob_sums.mean():.6f}")
print(f"      Min: {prob_sums.min():.6f}")
print(f"      Max: {prob_sums.max():.6f}")

# Clean up intermediate columns
dce_data = dce_data.drop(columns=['utility_shifted', 'exp_utility', 'sum_exp_utility'])
gc.collect()

# ============================================================================
# STEP 3: CALCULATE ACCURACY METRICS (FIXED)
# ============================================================================
print("\n" + "="*80)
print("STEP 3: CALCULATING ACCURACY METRICS")
print("="*80)

# IMPORTANT: Calculate rank on FULL dataset first (before filtering)
print("\nCalculating ranks for all alternatives...")
dce_data['rank'] = dce_data.groupby('learner_index')['predicted_prob'].rank(
    method='first', ascending=False
)
print(f"✓ Ranks calculated for all {len(dce_data):,} observations")

# NOW filter to chosen alternatives
chosen = dce_data[dce_data['chosen'] == 1].copy()

print(f"\n[3/4] Analyzing predictions for {len(chosen):,} chosen alternatives...")

# Metric 1: Mean predicted probability of chosen alternative
mean_pred_prob = chosen['predicted_prob'].mean()
print(f"\n1. Mean predicted probability (chosen alternatives): {mean_pred_prob:.4f}")
print(f"   Interpretation: On average, model assigns {mean_pred_prob*100:.2f}% probability to actual choice")

# Metric 2: Rank of chosen alternative (by predicted probability)
print(f"\n2. Rank of chosen alternative within choice set:")
chosen_ranks = chosen['rank']  # Already calculated above

rank_1 = (chosen_ranks == 1).sum()
rank_1_3 = (chosen_ranks <= 3).sum()
rank_1_5 = (chosen_ranks <= 5).sum()

print(f"   Rank 1 (top predicted): {rank_1:,} ({100*rank_1/len(chosen):.1f}%)")
print(f"   Rank 1-3: {rank_1_3:,} ({100*rank_1_3/len(chosen):.1f}%)")
print(f"   Rank 1-5: {rank_1_5:,} ({100*rank_1_5/len(chosen):.1f}%)")
print(f"   Mean rank: {chosen_ranks.mean():.2f}")
print(f"   Median rank: {chosen_ranks.median():.0f}")

# Metric 3: Probability distribution statistics
print(f"\n3. Probability distribution (chosen alternatives):")
print(f"   Min: {chosen['predicted_prob'].min():.4f}")
print(f"   25th percentile: {chosen['predicted_prob'].quantile(0.25):.4f}")
print(f"   Median: {chosen['predicted_prob'].median():.4f}")
print(f"   75th percentile: {chosen['predicted_prob'].quantile(0.75):.4f}")
print(f"   Max: {chosen['predicted_prob'].max():.4f}")

# Metric 4: Log-likelihood (already computed during estimation)
print(f"\n4. Model fit statistics:")
print(f"   Log-likelihood: {results.llf:.2f}")
print(f"   Number of observations: {len(dce_data):,}")
print(f"   Number of learners: {dce_data['learner_index'].nunique():,}")

# ============================================================================
# STEP 4: BENEFICIARY-SPECIFIC VALIDATION
# ============================================================================
print("\n" + "="*80)
print("STEP 4: BENEFICIARY-SPECIFIC VALIDATION")
print("="*80)

print("\n[4/4] Comparing prediction quality by beneficiary status...")

# Split by beneficiary status
chosen_beneficiaries = chosen[chosen['is_beneficiary'] == 1]
chosen_nonbeneficiaries = chosen[chosen['is_beneficiary'] == 0]

print(f"\nSample sizes:")
print(f"  Beneficiaries: {len(chosen_beneficiaries):,} ({100*len(chosen_beneficiaries)/len(chosen):.1f}%)")
print(f"  Non-beneficiaries: {len(chosen_nonbeneficiaries):,} ({100*len(chosen_nonbeneficiaries)/len(chosen):.1f}%)")

# Compare mean predicted probabilities
ben_mean_prob = chosen_beneficiaries['predicted_prob'].mean()
nonben_mean_prob = chosen_nonbeneficiaries['predicted_prob'].mean()

print(f"\nMean predicted probability of chosen alternative:")
print(f"  Beneficiaries: {ben_mean_prob:.4f} ({ben_mean_prob*100:.2f}%)")
print(f"  Non-beneficiaries: {nonben_mean_prob:.4f} ({nonben_mean_prob*100:.2f}%)")
print(f"  Difference: {ben_mean_prob - nonben_mean_prob:+.4f}")

if ben_mean_prob > nonben_mean_prob:
    print(f"  → Model predicts beneficiary choices MORE accurately")
else:
    print(f"  → Model predicts non-beneficiary choices MORE accurately")

# Compare rank distributions
ben_ranks = chosen_beneficiaries['rank']
nonben_ranks = chosen_nonbeneficiaries['rank']

print(f"\nRank 1 accuracy (chosen = top predicted):")
ben_rank1 = (ben_ranks == 1).sum()
nonben_rank1 = (nonben_ranks == 1).sum()
print(f"  Beneficiaries: {ben_rank1:,} / {len(ben_ranks):,} ({100*ben_rank1/len(ben_ranks):.1f}%)")
print(f"  Non-beneficiaries: {nonben_rank1:,} / {len(nonben_ranks):,} ({100*nonben_rank1/len(nonben_ranks):.1f}%)")

print(f"\nMean rank of chosen alternative:")
print(f"  Beneficiaries: {ben_ranks.mean():.2f}")
print(f"  Non-beneficiaries: {nonben_ranks.mean():.2f}")

# ============================================================================
# STEP 5: PREDICTION QUALITY BY DISTANCE (FIXED)
# ============================================================================
print("\n" + "="*80)
print("STEP 5: PREDICTION QUALITY BY DISTANCE")
print("="*80)

# Check if distance column exists
if 'distance_to_alternative_km' in chosen.columns:
    # Categorize chosen alternatives by distance
    chosen['distance_category'] = pd.cut(
        chosen['distance_to_alternative_km'],
        bins=[0, 2, 5, 10, 100],
        labels=['0-2km', '2-5km', '5-10km', '>10km']
    )

    print("\nPrediction accuracy by distance to chosen school:")
    for cat in ['0-2km', '2-5km', '5-10km', '>10km']:
        cat_data = chosen[chosen['distance_category'] == cat]
        if len(cat_data) > 0:
            mean_prob = cat_data['predicted_prob'].mean()
            rank1_pct = 100 * (cat_data['rank'] == 1).sum() / len(cat_data)
            print(f"  {cat:8s}: n={len(cat_data):6,}  Mean prob={mean_prob:.4f}  Rank 1={rank1_pct:5.1f}%")
else:
    print("\nWARNING: 'distance_to_alternative_km' column not found - skipping distance analysis")

# ============================================================================
# STEP 6: ESC SCHOOL PREDICTIONS (FIXED)
# ============================================================================
print("\n" + "="*80)
print("STEP 6: ESC SCHOOL PREDICTION QUALITY")
print("="*80)

# Check if ESC column exists
if 'alt_is_esc' in chosen.columns:
    # Split by whether chosen school is ESC
    chosen_esc = chosen[chosen['alt_is_esc'] == 1]
    chosen_non_esc = chosen[chosen['alt_is_esc'] == 0]

    print(f"\nChosen school type:")
    print(f"  ESC schools: {len(chosen_esc):,} ({100*len(chosen_esc)/len(chosen):.1f}%)")
    print(f"  Non-ESC schools: {len(chosen_non_esc):,} ({100*len(chosen_non_esc)/len(chosen):.1f}%)")

    print(f"\nPrediction quality by school type:")
    if len(chosen_esc) > 0:
        print(f"  ESC schools:")
        print(f"    Mean predicted probability: {chosen_esc['predicted_prob'].mean():.4f}")
        print(f"    Rank 1 accuracy: {100*(chosen_esc['rank'] == 1).sum()/len(chosen_esc):.1f}%")
    else:
        print(f"  ESC schools: No data")

    if len(chosen_non_esc) > 0:
        print(f"  Non-ESC schools:")
        print(f"    Mean predicted probability: {chosen_non_esc['predicted_prob'].mean():.4f}")
        print(f"    Rank 1 accuracy: {100*(chosen_non_esc['rank'] == 1).sum()/len(chosen_non_esc):.1f}%")
    else:
        print(f"  Non-ESC schools: No data")

    # Beneficiaries choosing ESC schools
    ben_esc = chosen[(chosen['is_beneficiary'] == 1) & (chosen['alt_is_esc'] == 1)]
    if len(ben_esc) > 0:
        print(f"\nBeneficiaries choosing ESC schools:")
        print(f"  Count: {len(ben_esc):,}")
        print(f"  Mean predicted probability: {ben_esc['predicted_prob'].mean():.4f}")
        print(f"  Rank 1 accuracy: {100*(ben_esc['rank'] == 1).sum()/len(ben_esc):.1f}%")
    else:
        print(f"\nBeneficiaries choosing ESC schools: No data")
else:
    print("\nWARNING: 'alt_is_esc' column not found - skipping ESC analysis")

# ============================================================================
# STEP 7: CREATE VALIDATION SUMMARY TABLE
# ============================================================================
print("\n" + "="*80)
print("STEP 7: VALIDATION SUMMARY TABLE")
print("="*80)

validation_summary = pd.DataFrame({
    'Metric': [
        'Overall Accuracy (Rank 1)',
        'Overall Mean Predicted Probability',
        'Beneficiary Accuracy (Rank 1)',
        'Beneficiary Mean Predicted Probability',
        'Non-Beneficiary Accuracy (Rank 1)',
        'Non-Beneficiary Mean Predicted Probability',
        'ESC School Accuracy (Rank 1)',
        'Non-ESC School Accuracy (Rank 1)',
        'Log-Likelihood',
        'Number of Observations',
        'Number of Learners'
    ],
    'Value': [
        f"{100*rank_1/len(chosen):.2f}%",
        f"{mean_pred_prob:.4f}",
        f"{100*ben_rank1/len(ben_ranks):.2f}%",
        f"{ben_mean_prob:.4f}",
        f"{100*nonben_rank1/len(nonben_ranks):.2f}%",
        f"{nonben_mean_prob:.4f}",
        f"{100*(chosen_esc['rank'] == 1).sum()/len(chosen_esc):.2f}%",
        f"{100*(chosen_non_esc['rank'] == 1).sum()/len(chosen_non_esc):.2f}%",
        f"{results.llf:.2f}",
        f"{len(dce_data):,}",
        f"{dce_data['learner_index'].nunique():,}"
    ]
})

print("\n" + validation_summary.to_string(index=False))

# ============================================================================
# STEP 8: EXPORT RESULTS
# ============================================================================
print("\n" + "="*80)
print("STEP 8: EXPORTING VALIDATION RESULTS")
print("="*80)

BASE_DIR = Path('/workspace/innovation-projects/project_paaral')
output_dir = BASE_DIR / 'output/rizal_choice_simulation'
output_dir.mkdir(parents=True, exist_ok=True)

# Export predictions
predictions_path = output_dir / 'dce_predictions_with_beneficiary_model.csv'
output_cols = [
    'learner_index', 'lrn', 'school_id_origin', 'school_id_alternative',
    'chosen', 'is_beneficiary', 'alt_is_esc', 'distance_to_alternative_km',
    'utility', 'predicted_prob', 'rank'
]
existing_output_cols = [col for col in output_cols if col in dce_data.columns]
dce_data[existing_output_cols].to_csv(predictions_path, index=False)
print(f"✓ Predictions exported to: {predictions_path}")

# Export validation summary
summary_path = output_dir / 'validation_summary_beneficiary_model.csv'
validation_summary.to_csv(summary_path, index=False)
print(f"✓ Validation summary exported to: {summary_path}")

# Export chosen alternatives with predictions
chosen_path = output_dir / 'chosen_alternatives_with_predictions.csv'
chosen_cols = [
    'learner_index', 'lrn', 'school_id_origin', 'school_id_alternative',
    'is_beneficiary', 'alt_is_esc', 'alt_is_public',
    'distance_to_alternative_km', 'alt_tuition_thousands',
    'predicted_prob', 'rank', 'distance_category'
]
existing_chosen_cols = [col for col in chosen_cols if col in chosen.columns]
chosen[existing_chosen_cols].to_csv(chosen_path, index=False)
print(f"✓ Chosen alternatives exported to: {chosen_path}")

# Create detailed validation report
report_path = output_dir / 'validation_report_beneficiary_model.txt'
with open(report_path, 'w') as f:
    f.write("="*80 + "\n")
    f.write("MODEL VALIDATION REPORT - BENEFICIARY-SPECIFIC MODEL\n")
    f.write("="*80 + "\n\n")

    f.write("MODEL SPECIFICATION:\n")
    f.write(f"Features: {len(model_features)}\n")
    for i, feat in enumerate(model_features):
        coef = results.params[i]
        pval = results.pvalues[i]
        sig = '***' if pval < 0.001 else ('**' if pval < 0.01 else ('*' if pval < 0.05 else ''))
        f.write(f"  {feat:30s} = {coef:+.4f} {sig}\n")

    f.write("\n" + "="*80 + "\n")
    f.write("VALIDATION METRICS\n")
    f.write("="*80 + "\n\n")

    f.write(validation_summary.to_string(index=False))

    f.write("\n\n" + "="*80 + "\n")
    f.write("BENEFICIARY-SPECIFIC PERFORMANCE\n")
    f.write("="*80 + "\n\n")

    f.write(f"Beneficiaries (n={len(chosen_beneficiaries):,}):\n")
    f.write(f"  Mean predicted probability: {ben_mean_prob:.4f}\n")
    f.write(f"  Rank 1 accuracy: {100*ben_rank1/len(ben_ranks):.2f}%\n")
    f.write(f"  Mean rank: {ben_ranks.mean():.2f}\n\n")

    f.write(f"Non-beneficiaries (n={len(chosen_nonbeneficiaries):,}):\n")
    f.write(f"  Mean predicted probability: {nonben_mean_prob:.4f}\n")
    f.write(f"  Rank 1 accuracy: {100*nonben_rank1/len(nonben_ranks):.2f}%\n")
    f.write(f"  Mean rank: {nonben_ranks.mean():.2f}\n")

    f.write("\n" + "="*80 + "\n")
    f.write("DISTANCE PERFORMANCE\n")
    f.write("="*80 + "\n\n")

    for cat in ['0-2km', '2-5km', '5-10km', '>10km']:
        cat_data = chosen[chosen['distance_category'] == cat]
        if len(cat_data) > 0:
            f.write(f"{cat:10s}: n={len(cat_data):6,}  ")
            f.write(f"Mean prob={cat_data['predicted_prob'].mean():.4f}  ")
            f.write(f"Rank 1={(cat_data['rank'] == 1).sum()/len(cat_data)*100:5.1f}%\n")

print(f"✓ Validation report exported to: {report_path}")

print("\n" + "="*80)
print("✓ TASK 3.3 COMPLETE (REVISED FOR TASK 3.2b)")
print("="*80)

print("\nValidation complete!")
print(f"  Overall accuracy (Rank 1): {100*rank_1/len(chosen):.2f}%")
print(f"  Mean predicted probability: {mean_pred_prob:.4f}")
print(f"  Beneficiary vs non-beneficiary performance: See validation_report.txt")

print("\nNext steps:")
print("  1. Review validation metrics - are predictions reasonable?")
print("  2. If validation is good, proceed to simulation environment")
print("  3. Use predictions to test policy scenarios")

================================================================================
TASK 3.3: MODEL VALIDATION (REVISED FOR TASK 3.2b)
================================================================================

Verifying prerequisites...
✓ All prerequisites found
  Model: 11 features
  Data: 934,464 observations

================================================================================
STEP 1: COMPUTING PREDICTIONS
================================================================================

[1/4] Calculating utility values...
  ✓ Utilities calculated
    Mean utility: -3.9606
    Std utility: 3.4003

[2/4] Converting utilities to choice probabilities...
  ✓ Probabilities calculated
    Probability sums per learner (should be 1.0):
      Mean: 1.000000
      Min: 1.000000
      Max: 1.000000

================================================================================
STEP 3: CALCULATING ACCURACY METRICS
================================================================================

Calculating ranks for all alternatives...
✓ Ranks calculated for all 934,464 observations

[3/4] Analyzing predictions for 48,585 chosen alternatives...

1. Mean predicted probability (chosen alternatives): 0.9150
   Interpretation: On average, model assigns 91.50% probability to actual choice

2. Rank of chosen alternative within choice set:
   Rank 1 (top predicted): 45,446 (93.5%)
   Rank 1-3: 46,725 (96.2%)
   Rank 1-5: 47,337 (97.4%)
   Mean rank: 1.27
   Median rank: 1

3. Probability distribution (chosen alternatives):
   Min: 0.0001
   25th percentile: 0.9998
   Median: 1.0000
   75th percentile: 1.0000
   Max: 1.0000

4. Model fit statistics:
   Log-likelihood: -10389.59
   Number of observations: 934,464
   Number of learners: 48,585

================================================================================
STEP 4: BENEFICIARY-SPECIFIC VALIDATION
================================================================================

[4/4] Comparing prediction quality by beneficiary status...

Sample sizes:
  Beneficiaries: 5,674 (11.7%)
  Non-beneficiaries: 42,911 (88.3%)

Mean predicted probability of chosen alternative:
  Beneficiaries: 0.6811 (68.11%)
  Non-beneficiaries: 0.9459 (94.59%)
  Difference: -0.2647
  → Model predicts non-beneficiary choices MORE accurately

Rank 1 accuracy (chosen = top predicted):
  Beneficiaries: 4,439 / 5,674 (78.2%)
  Non-beneficiaries: 41,007 / 42,911 (95.6%)

Mean rank of chosen alternative:
  Beneficiaries: 1.67
  Non-beneficiaries: 1.22

================================================================================
STEP 5: PREDICTION QUALITY BY DISTANCE
================================================================================

Prediction accuracy by distance to chosen school:
  0-2km   : n=27,481  Mean prob=0.9815  Rank 1= 99.1%
  2-5km   : n= 8,980  Mean prob=0.9451  Rank 1= 95.7%
  5-10km  : n= 2,699  Mean prob=0.8172  Rank 1= 84.0%
  >10km   : n= 3,234  Mean prob=0.9039  Rank 1= 90.4%

================================================================================
STEP 6: ESC SCHOOL PREDICTION QUALITY
================================================================================

Chosen school type:
  ESC schools: 5,935 (12.2%)
  Non-ESC schools: 42,650 (87.8%)

Prediction quality by school type:
  ESC schools:
    Mean predicted probability: 0.6774
    Rank 1 accuracy: 78.5%
  Non-ESC schools:
    Mean predicted probability: 0.9480
    Rank 1 accuracy: 95.6%

Beneficiaries choosing ESC schools:
  Count: 5,477
  Mean predicted probability: 0.7042
  Rank 1 accuracy: 80.9%

================================================================================
STEP 7: VALIDATION SUMMARY TABLE
================================================================================

                                    Metric     Value
                 Overall Accuracy (Rank 1)    93.54%
        Overall Mean Predicted Probability    0.9150
             Beneficiary Accuracy (Rank 1)    78.23%
    Beneficiary Mean Predicted Probability    0.6811
         Non-Beneficiary Accuracy (Rank 1)    95.56%
Non-Beneficiary Mean Predicted Probability    0.9459
              ESC School Accuracy (Rank 1)    78.52%
          Non-ESC School Accuracy (Rank 1)    95.63%
                            Log-Likelihood -10389.59
                    Number of Observations   934,464
                        Number of Learners    48,585

================================================================================
STEP 8: EXPORTING VALIDATION RESULTS
================================================================================
✓ Predictions exported to: /workspace/innovation-projects/project_paaral/output/rizal_choice_simulation/dce_predictions_with_beneficiary_model.csv
✓ Validation summary exported to: /workspace/innovation-projects/project_paaral/output/rizal_choice_simulation/validation_summary_beneficiary_model.csv
✓ Chosen alternatives exported to: /workspace/innovation-projects/project_paaral/output/rizal_choice_simulation/chosen_alternatives_with_predictions.csv
✓ Validation report exported to: /workspace/innovation-projects/project_paaral/output/rizal_choice_simulation/validation_report_beneficiary_model.txt

================================================================================
✓ TASK 3.3 COMPLETE (REVISED FOR TASK 3.2b)
================================================================================

Validation complete!
  Overall accuracy (Rank 1): 93.54%
  Mean predicted probability: 0.9150
  Beneficiary vs non-beneficiary performance: See validation_report.txt

Next steps:
  1. Review validation metrics - are predictions reasonable?
  2. If validation is good, proceed to simulation environment
  3. Use predictions to test policy scenarios

## END